### ISSUE TITLE
Multi world issues

### ISSUE THREAD

**Issue by Eredrim** [TheNewEconomy/TNE-Bukkit#103]
Hello,

I have two problems with multi-world : 
- The following lines are not generated by default in worlds.yml
>      Format: <symbol><major><decimal><minor><shorten>
>      Conversion: 1.0
>      Symbol: £
>      Decimal: .

- I have this error with account sharing (please see my config in [attachment](https://github.com/TheNewEconomy/TNE-Bukkit/files/571532/worlds.yml.txt))

> [13:42:37 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'bal' in plugin TheNewEconomy v0.0.4.2
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
>         at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
>         at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
> Caused by: java.lang.NullPointerException
>         at com.github.tnerevival.core.currency.CurrencyFormatter.format(CurrencyFormatter.java:39) ~[?:?]
>         at com.github.tnerevival.core.currency.CurrencyFormatter.format(CurrencyFormatter.java:29) ~[?:?]
>         at com.github.tnerevival.commands.money.MoneyBalanceCommand.execute(MoneyBalanceCommand.java:41) ~[?:?]
>         at com.github.tnerevival.commands.money.MoneyCommand.execute(MoneyCommand.java:61) ~[?:?]
>         at com.github.tnerevival.TNE.onCommand(TNE.java:166) ~[?:?]
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
>         ... 15 more

**Comment by creatorfromhell** [comment]
I'm currently out of town for the day, but when I get back later tonight I'll definitely look into the issues you're having.
