### ISSUE TITLE
Problem with PermissionEx in the groups with prefix

### ISSUE THREAD

**Issue by skay1994** [TheNewEconomy/TNE-Bukkit#109]
Crashlog: https://github.com/skay1994/pex_erro_theneweconomy/blob/master/crashlog
Log: https://github.com/skay1994/pex_erro_theneweconomy/blob/master/log

**Comment by creatorfromhell** [comment]
This is caused by pex sending the username with the prefix, not sure why they'd do that... Will fix either way. Also, curious as to why you're using both Essentials Eco and TNE?

**Comment by skay1994** [comment]
thank for fast response.

**Comment by skay1994** [comment]
A suggestion to add an option in the configuration file for the user to indicate the form of the prefix used.
