### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by ColeBoytinck** [TheNewEconomy/TNE-Bukkit#114]
Hello, I used to use CraftConomy, however, they have been inactive for over a year, and their plugin seems broken for 1.11. I have been looking for a new Economy plugin, and this one really looks amazing. However, I can't even seem to get past the startup. Here is my error:

03.12 00:45:30 [Server] INFO ... 12 more
03.12 00:45:30 [Server] INFO at com.github.tnerevival.core.SaveManager.<clinit>(SaveManager.java:24) ~[?:?]
03.12 00:45:30 [Server] INFO at com.github.tnerevival.core.version.impl.Alpha2_2.<init>(Alpha2_2.java:28) ~[?:?]
03.12 00:45:30 [Server] INFO at com.github.tnerevival.core.version.Version.<init>(Version.java:18) ~[?:?]
03.12 00:45:30 [Server] INFO at com.github.tnerevival.core.configurations.ConfigurationManager.getString(ConfigurationManager.java:124) ~[?:?]
03.12 00:45:30 [Server] INFO at com.github.tnerevival.core.configurations.ConfigurationManager.getString(ConfigurationManager.java:144) ~[?:?]
03.12 00:45:30 [Server] INFO Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
03.12 00:45:30 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
03.12 00:45:30 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.0-20161129a.jar:git-Spigot-f950f8e-41ade2f]
03.12 00:45:30 [Server] INFO at com.github.tnerevival.TNE.onEnable(TNE.java:96) ~[?:?]
03.12 00:45:30 [Server] INFO java.lang.ExceptionInInitializerError
03.12 00:45:30 [Server] ERROR Error occurred while enabling TheNewEconomy v0.0.5.0 (Is it up to date?)
03.12 00:45:30 [Server] WARN Plugin TheNewEconomy attempted to establish connection socket://creatorfromhell.com:443 in main server thread
03.12 00:45:30 [Server] WARN Plugin TheNewEconomy attempted to establish connection https://creatorfromhell.com/tne/tnebuild.txt in main server thread
03.12 00:45:30 [Server] INFO Enabling TheNewEconomy v0.0.5.0

**Comment by creatorfromhell** [comment]
Have you used TNE previously? IT looks as though it's trying to convert form Alpha 2.2, but pre Alpha 3.0 builds are not compatible with 3.0+ so you'll need to convert using Alpha 2.4 first.

**Comment by ColeBoytinck** [comment]
I seem to have found my issue. A fresh config file works, it is when I try and hook up TNE to MySql that it breaks. Both my user and db name are both numbers, so it causes a ClassCastException because in the config, it is set as an int, and it tries to cast that as a string.

My java knowledge is fairly limited. Would you be able to add a String cast to getString in the ConfigurationManager, as it seems that is where the problem is coming from.

**Comment by creatorfromhell** [comment]
That error is due to a cast, which you can't do from int to string, because they're not in the same class hierarchy. Simply adding quotes around them should please the YAML gods.

**Comment by ColeBoytinck** [comment]
Of course it is that simple, thank you kind sir!
