### ISSUE TITLE
Database erro on load

### ISSUE THREAD

**Issue by skay1994** [TheNewEconomy/TNE-Bukkit#115]
After a while using the plugin it presents this error while loading the db using mysql. Works again by recreating the database.

Includes sql database to be able to parse

https://github.com/skay1994/tne_error_mysql

**Comment by skay1994** [comment]
in my tests the table tne_USER not needed reset to plugin works

**Comment by creatorfromhell** [comment]
From the error you posted it appears that somehow it got saved incorrectly... Have you created all banks via command? Or have some been created by other plugins?

**Comment by skay1994** [comment]
By command, I have no other plugin that uses the same commands as tne

**Comment by creatorfromhell** [comment]
I meant plugins that would create one through vault.

**Comment by creatorfromhell** [comment]
I haven't been able to recreate this error yet, and the TNE installation I have been using on my test server has been running since Alpha 3.

**Comment by creatorfromhell** [comment]
My suggestion, since I haven't been able to recreate this error yet would be to remove the third row(
('0faae232-48d4-39ee-805c-3e7a01fcc303', '6d04ff6d-8b46-3353-9c8d-d49f6ee5c309', 'N/A')), and it should load fine.

**Comment by skay1994** [comment]
thank you anyway

**Comment by creatorfromhell** [comment]
No problem, if the issue returns please let me know, and what you did up to the point of the error.

**Comment by skay1994** [comment]
I also do not know what was done to cause the error, it has already happened other times, only now that I have been able to capture what is written in the console
