### ISSUE TITLE
Enabled: False

### ISSUE THREAD

**Issue by zerafox** [TheNewEconomy/TNE-Bukkit#117]
Despite having set the configuration file:

    Chest:
      Enabled: false
      Timed: false
      Cost: 200.0
      Packages:
        DefaultPackage:
          Time: 600
          Cost: 20.0

I was still charged $200 for accessing another plugin's "chest inventory". I was surprised by this, considering again, I had disabled these charges.

I even double checked to ensure this:
  Inventories:
    Enabled: false
    PerWorld: false
    ZeroMessage: false

Though I am still charged for each use.

**Comment by creatorfromhell** [comment]
Please post your full objects.yml using http://paste.ubuntu.com.

**Comment by zerafox** [comment]
Really.. You need a full file to determine that the settings for disabling, isn't working... -.-
http://paste.ubuntu.com/23581071/

**Comment by creatorfromhell** [comment]
Everything's working fine on my end, without knowing the plugin with the "chest inventory" it's hard to debug it on my end, but with the response you gave for a simple configuration file I don't wish to continue this ticket anymore. Bug reports are greatly appreciated, but not being cooperative, and/or giving attitude when asked for cooperation won't be tolerated, nor does it have to be. TNE is provided for free. If you wish to cooperate this ticket may be reopened, but for now it'll be closed.

**Comment by zerafox** [comment]
There isn't adequate documentation on this plugin anyway, as awesome as it sounds, there's a serious lack of information to make it work to what it claims to be designed for.
For the plugin in question, it's MyPet.. Any MyPet inventory uses the Chest GUI, as many other Chest GUI plugins do.

As for the 'attitude' given, I saw no reason to see the rest of the configuration file when the parts in question were provided. It seemed like an unnecessary step.
I've no problems helping out testing, bug reporting and offering inputs but I'm not new to this bug-report and error finding game either. So I apologize for attitude, but I didn't appreciate an essential "not enough info, i need the whole file". Did you do your test with a Chest GUI plugin? Something like MyPet, BossShop, something? I couldn't even access half of my setups on server due to this little 'bug' as most of them are GUI based. :\

I do hope you find out whatever it is and get it fixed. Anyone out there using something GUI based like I do is going to have struggle otherwise.

**Comment by creatorfromhell** [comment]
http://prntscr.com/dfge00 It doesn't seem to charge me for any inventories in MyPet when disabled. You could try an Alpha 5.1 snapshot, but I tested with both versions. Attached is an Alpha 5.1 snapshot.
[TNE.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/630103/TNE.zip)
