### ISSUE TITLE
Not working with prefixes

### ISSUE THREAD

**Issue by zankia** [TheNewEconomy/TNE-Bukkit#119]
Hello,

I want to re open #109 because I have the same problem and found a solution (sorry, don't want to fork, only for changing one line). The problem is not about the permission plugin but the chat plugin. I am using EssentialsChat and when I disable it, it works fine.

When you try to get the UUID of the player, you send its all displayname instead of sending its nickname.

This can be fixed really easily by changing `player.getDisplayName()` into `player.getName()` on [IDFinder:68](https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/src/com/github/tnerevival/account/IDFinder.java#L68)

Thank you

**Comment by creatorfromhell** [comment]
Fixed locally, didn't notice I had used the display name there. Thanks for pointing that out.
