### ISSUE TITLE
Make all configs on a world basis

### ISSUE THREAD

**Issue by zankia** [TheNewEconomy/TNE-Bukkit#122]
Hello,

It would be great to be able to configure **every** option from every file in _worlds.yml_ instead of just Currency and Bank. Of course, it should keep the same behaviour : if its not if _worlds.yml_, the default configuration is applied.

I am thinking of creating a world where players earn money from killing mobs, but I don't want this be possible in other worlds. We can also imagine a world where every action is free or really expensive

Thank you

**Comment by creatorfromhell** [comment]
This should be possible, but I'll double check on the mob rewards support. Everything except for database configurations should be able to be set on a per-world/player basis. This includes messages, just make sure to include the full path i.e. Mobs.Bat.Enabled, etc
