### ISSUE TITLE
Please add EssentialsX compatibility

### ISSUE THREAD

**Issue by Sitmobedaf** [TheNewEconomy/TNE-Bukkit#123]
When i use Essentials with TNE, i watch that TNE can not change his balance.

**Comment by creatorfromhell** [comment]
Please use the updated bug report format. https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/Report%20Format.md

**Comment by creatorfromhell** [comment]
Closed. Insufficient information, and failure to comply with new report format.

**Comment by Sitmobedaf** [comment]
Via use Essentials signs (buy, sell). Just, with iConomy no such this problem.

**Comment by creatorfromhell** [comment]
Please use the updated bug report format. https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/Report%20Format.md After you submit using the right format, we can continue with this report.
