### ISSUE TITLE
Inventory Cost

### ISSUE THREAD

**Issue by Techniker17** [TheNewEconomy/TNE-Bukkit#128]
Hi,

this is a faboulus plugin!
We wnat to start our own server and installed it. It is all working fine, but there is one problem:
Is there the possibility to disable the cost for opening inventories like hoppers and furnaces?
I couldn`t find a option in the config.
Thank you in advance

**Comment by creatorfromhell** [comment]
What you're looking for is the objects.yml file. https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/objects.yml#L36
