### ISSUE TITLE
Feature Request: Chests can contain items as part of the players balance

### ISSUE THREAD

**Issue by TomberWolf** [TheNewEconomy/TNE-Bukkit#129]
It would be a perfect roundup for this plugin playsers can use chest that contains item for their balance (not just in their inventory).

You may want to take a look at "Gringotts" that makes that possible but has many issues.
https://dev.bukkit.org/projects/gringotts

**Comment by creatorfromhell** [comment]
Will look into this as a configurable feature.

**Comment by creatorfromhell** [comment]
I'm assuming it works by just putting x amount of item currency in a chest with a sign attached, am I correct?

**Comment by TomPiXX** [comment]
Yes. With Gringotts you have to place a sign above the chest - Vault has to be installed, to - and write [Vault] on it.
The sign adds the playername automatically at the second line and applies the sign to the chest.
If you can get it work more comfortable (without the need of a sign, just a chest, maybe?) it would be great.
As you know: Users are lazy... ;-)

Thanks for you work and time!

**Comment by TomPiXX** [comment]
Oh damn, I can't wait for it :D *happy*
