### ISSUE TITLE
Bank: Unknown Player bug

### ISSUE THREAD

**Issue by Volander** [TheNewEconomy/TNE-Bukkit#131]
Issue:
Console error spam and in game internal error
Reproduced by:
/bank balance <player who dosent have a bank account>

Using: 
The New Economy 0.0.5.1 (unmodified)
Spigot 1.11.2 (unmodifed)

Server is running in offline mode behind a bungee server

config.yml: http://paste.ubuntu.com/23909668/
Server log: http://paste.ubuntu.com/23909700/

**Comment by creatorfromhell** [comment]
My result is this: http://prntscr.com/e3m95v. It's working as intended by saying "unable to location player". Unless I read your issue wrong?

**Comment by Volander** [comment]
I'm not getting that result but will check up when i get off work.

Sendt fra min iPhone

**Comment by creatorfromhell** [comment]
Again I'm using my source to test so, which among other things, has rewritten bank commands. It was probably an issue that I've already fixed for the next release
