### ISSUE TITLE
Pay command not working

### ISSUE THREAD

**Issue by Volander** [TheNewEconomy/TNE-Bukkit#132]
Issue:
Using the /pay command simply gives a feedback of unknown command
I have set the command PayShort to true in the config file.
Reproduced by:
/pay <name> 20

Using:
The New Economy 0.0.5.1 (unmodified)
Spigot 1.11.2 (unmodifed)

Server is running in offline mode behind a bungee server

config.yml: http://paste.ubuntu.com/23909668/

**Comment by creatorfromhell** [comment]
Fixed, thanks for the report. http://prntscr.com/e3mawl
