### ISSUE TITLE
Some compatibility problems with EssentialsX

### ISSUE THREAD

**Issue by Eredrim** [TheNewEconomy/TNE-Bukkit#140]
Hello,
I have some compatibility problems with essentialsX. I use the latest build (#468) which you could download here : https://ci.drtshock.net/job/essentialsx/468/

Note: In the following lines, I consider a TNE balance which is the result of the /money or /bal command and an Essentials balance which is the result of the /ebal command.

This is a list of the problems I observe : 
- The /pay command is no longer overridden by /money pay
- When a user do a /money pay, the essentials balance is impacted for the payer and for the receiver instead of the TNE balance
- When I type /tne balance <username> <world>, I get the essentials balance instead of the TNE balance
- When I buy something with essentials shop (signs with the [buy] line), the amount is taken in my essentials balance.

The is no error in the log.
My Spigot version : 1.11.2 git-Spigot-65a0347-a552117
My TNE version : the snapshot you gave me in ticket https://github.com/TheNewEconomy/TNE-Bukkit/issues/139
My config.yml : http://paste.ubuntu.com/24035482/

**Comment by creatorfromhell** [comment]
[TNE.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/791693/TNE.zip)
This seems to work for me. The issue was Essentials was loading after TNE, and removing it from Vault, and command handling.

**Comment by Eredrim** [comment]
I don't see any difference but in my test Vault doesn't notify that TNE is linked. So I think your idea of priority in plugin loading is the good. This is my start log : http://paste.ubuntu.com/24043143/

**Comment by creatorfromhell** [comment]
When you say "doesn't notify you" are you referring to the startup messages of Vault? If so this won't be accurate as Vault is loaded before TNE, you'd need to use the actual in-game command provided by Vault to retrieve the answer for this.

**Comment by creatorfromhell** [comment]
Results with jar given in this issue are works as intended http://prntscr.com/ebs8dc.

**Comment by Eredrim** [comment]
To reply to your second to last message, yes I refer to the startup messages. However, I don't know the Vault command you talk about, what is it ?

**Comment by creatorfromhell** [comment]
The command is /vault-info

**Comment by Eredrim** [comment]
The command result is : 
```
[19:16:17 INFO]: [Vault] Vault v1.5.6-b49 Information
[19:16:17 INFO]: [Vault] Economy: TheNewEconomy [TheNewEconomy, Essentials Economy]
[19:16:17 INFO]: [Vault] Permission: GroupManager [GroupManager, SuperPerms]
[19:16:17 INFO]: [Vault] Chat: GroupManager - Chat [GroupManager - Chat]
```
In your screenshot, I can see you doesn't have the latest version of Vault. It is maybe the problem cause ?

**Comment by creatorfromhell** [comment]
I'll test when I get home, but the different versions of Vault usually don't change anything major that would affect it

**Comment by creatorfromhell** [comment]
After testing with the latest Vault, the issues still cannot be reproduced.

**Comment by Eredrim** [comment]
I created a mini spigot test server with Essentials, Chestshop, Vault and some other basic plugins. I removed all my personal configuration except for Essentials and TNE. And with that, I continue to have the problem. So I sent you a link by e-mail to download this spigot server and show yourself the issues. It is really light (~33MB).

**Comment by creatorfromhell** [comment]
Alright, I've done my testing and here are the results, IT does use TNE for money balance, however it's not showing it in the money command. However, it shows up in the admin balance(tne balance) and the developer commands. http://prntscr.com/ecp6li I'm not entirely sure why it's not formatting it properly, but will look into it. However, it is definitely using the TNE balance for both signs.

Thanks,
  Daniel "creatorfromhell" Vidmar

**Comment by Eredrim** [comment]
Hello, I tested the latest version of TNE and I meet exactly the same error than the last time (described in this ticket).

Regards,

**Comment by creatorfromhell** [comment]
Still haven't been able to reproduce but I'll see if I can figure anything out
