### ISSUE TITLE
TNE related issue with Factions

### ISSUE THREAD

**Issue by TomberWolf** [TheNewEconomy/TNE-Bukkit#142]
Please take a look at this TNE related issue:

https://github.com/MassiveCraft/Factions/issues/1200#event-997077542

**Comment by creatorfromhell** [comment]
Is your currency item-based?  If so that's probably the reason since it attempts to check an inventory with the item, and factions have no inventory...

**Comment by creatorfromhell** [comment]
Alright this seems to have fixed the incompatibilities.
