### ISSUE TITLE
Async World Edit Free Incompatibility

### ISSUE THREAD

**Issue by creatorfromhell** [TheNewEconomy/TNE-Bukkit#145]
We need to determine what causes this incompatibility, and if this is something that TNE will be able to work around, or if AWE's developers will need to fix.

**Comment by EvilOlaf** [comment]
No idea what AWE is related to a currency management plugin but you may consider to take a look at FAWE as well. https://github.com/boy0001/FastAsyncWorldedit

**Comment by creatorfromhell** [comment]
I wasn't either, but I will definitely take a look at FAWE.
