### ISSUE TITLE
Shops do not work.

### ISSUE THREAD

**Issue by Kushbird** [TheNewEconomy/TNE-Bukkit#151]
I'm on TNE version 5.4 and Spigot version 1.11.2-R0.1-SNAPSHOT.

Shops are user unfriendly to set up, and simply do not work. You can infinitely drag out stacks of items without stock ever depleting and never being charged.

**Comment by creatorfromhell** [comment]
Shops are currently pending a complete overhaul, as the command-based system is indeed not user friendly

**Comment by creatorfromhell** [comment]
This will be covered by issue #153
