### ISSUE TITLE
Error when displaying large amounts.

### ISSUE THREAD

**Issue by Kushbird** [TheNewEconomy/TNE-Bukkit#152]
I'm on TNE version 5.4 and Spigot version 1.11.2-R0.1-SNAPSHOT.

Large amounts can not be displayed by the plugin, most likely caused by the plugin not knowing what formatting to use as it hasn't been coded in. It also seems to have wrong formatting, as one or multiple billions shows up as "G" (I presume gajillion?). Any amount larger than about 2,000,000,000 seems to result in an error. This means that the account becomes useless without editing it to have a lower amount of money, as any transaction will not be printed out.

https://paste.ubuntu.com/24366549/

**Comment by creatorfromhell** [comment]
I have fixed the error-related issue, and will move towards fixing the formatting-related things now. http://prntscr.com/ewrlb5 is now the max value that may be displayed.

**Comment by creatorfromhell** [comment]
Everything relating to this error has been fixed.
