### ISSUE TITLE
Error when player dies.

### ISSUE THREAD

**Issue by Kushbird** [TheNewEconomy/TNE-Bukkit#154]
I'm on TNE version 5.4 and Spigot version 1.11.2-R0.1-SNAPSHOT.

The plugin seems to print out an error each time a player dies, it doesn't cause any major issues from what I've seen, but it is annoying to have a log spammed full of errors nonetheless.

https://paste.ubuntu.com/24385813/

**Comment by JustINaVW** [comment]
I'm also having this issue. Was there a fix?

**Comment by creatorfromhell** [comment]
Yes it was fixed on the repository already, await the 5.5 release. It wasn't anything major so there's nothing to worry about. Just annoying console spam.
