### ISSUE TITLE
Great plugin so far

### ISSUE THREAD

**Issue by JustINaVW** [TheNewEconomy/TNE-Bukkit#155]
Is there a tutorial on setting up admin shops? I cant seem to figure it out. My ultimate goal is to just have admin shops and players cannot make shops. Only use them at spawn.

**Comment by creatorfromhell** [comment]
Currently there is no tutorial for this. However, for sign shops you simply write Admin on line 4 of the sign. Normal shops are currently undergoing a rewrite so any information on them would be outdated. 

Thanks, 
   Creatorfromhell

**Comment by JustINaVW** [comment]
sweet. Thanks for the fast reply
