### ISSUE TITLE
Bank and interest issues.

### ISSUE THREAD

**Issue by JakeYde** [TheNewEconomy/TNE-Bukkit#159]
First issue When players purchase a bank, it does not deduct money from their balance. 
`  Bank:
    Enabled: true
    Connected: true
    Cost: 20.0
    MultiManage: true`

Then when I enable interest in the configuration file via:
`      Interest:
        Enabled: false
        Rate: 0.1
        Interval: 1800`
Once the player deposits money into the bank the interest somehow makes their money increase exponentially.

**Comment by creatorfromhell** [comment]
For the first issue, a lot of times this happens with permissions misconfiguration, giving the bank purchasing override permission node. 

Secondly, are you using their retest rate configurations located under each individual currency?

**Comment by creatorfromhell** [comment]
Closing since this issue is not formatted correctly, and no response for 8 days.
