### ISSUE TITLE
Plugin is ignoring update option

### ISSUE THREAD

**Issue by leesiuu** [TheNewEconomy/TNE-Bukkit#162]
I set in configuration file this:
````
  Update:
    Check: false
    Notify: false
````

But plugin still is checking updates (console from server):
````
[15:14:21 WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection https://creatorfromhell.com/tne/tnebuild.txt in main server thread
[15:14:21 WARN]: [AutoSaveWorld] Plugin TheNewEconomy attempted to establish connection socket://creatorfromhell.com:443 in main server thread
````

I am using the latest version of plugin: 0.0.5.4

Okay... I resolved this problem:
TNE sending now only once (on start) request for update (but shouldn't).

BUT, problem on my server was with metrics data. After trying connection with metrics data my server every time not responding after that action. Do you know what is wrong with metrics?
There is crash log: http://s000.tinyupload.com/?file_id=43293726401715367779

**Comment by creatorfromhell** [comment]
Metrics may be turned off, there's a Metrics configuration option in the config.yml, as the metrics site is no longer maintained, and we will be switching services in Alpha 5.5

**Comment by leesiuu** [comment]
I switched metrics off, but plugin still connecting with update service on server's start. Please tell me what I need to do becouse it crashes my server :(

**Comment by creatorfromhell** [comment]
Some how the configuration check for the updater was removed, I have readded it. From the brief overview I had of the server log, it seemed as though everything revolved around the statistics issue.

**Comment by leesiuu** [comment]
Okay I will wait for update!
When can I expect it? :)

**Comment by creatorfromhell** [comment]
It has no ETA yet, but no later than June 6th.
