### ISSUE TITLE
/money set not working

### ISSUE THREAD

**Issue by zAxny32** [TheNewEconomy/TNE-Bukkit#170]
Hello,
I've just installed your plugin instead of iConomy in a Spigot 1.12 server (offline mode) but I have a problem: when I run the command /money set zAxny32 10000 (as op player or from the console) and then I write /money (as zAxny32), I get the default balance ($ 200). Then, if I run /money top, I see zAxny32 two times: one with $ 200 and one with $ 10k. It seems like there are two accounts, in fact when I run /tne balance zAxny32, I get $ 10k. Finally, when I buy something in a shop (plugin ShopChest), it takes the money from the account with $ 200.
I didn't modify the configuration files.

**Comment by creatorfromhell** [comment]
Try this jar, it has a lot of the fixes for issues such as this that have been found in the past few days.
[TNE.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/1093238/TNE.zip)

**Comment by zAxny32** [comment]
Ok, I tried your jar but now there's a different problem: when I do /money set it returns an error: The currency "Default" could not be found in "world". In addiction to this when I write /money I get always the default balance, even if I buy something in a shop. I have to do /money top to view my real balance, and I see 2 accounts: one with the default balance and one with my real balance.
My configuration: [config.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/1095627/config.zip)

**Comment by creatorfromhell** [comment]
This will be paired under #171
