### ISSUE TITLE
NPE When Transacting with Offline Player in Item Economy

### ISSUE THREAD

**Issue by Spearhartt** [TheNewEconomy/TNE-Bukkit#173]
When not using banks or vaults and transacting an item with an offline player, the plugin throws the below NPE.

NPE: https://hastebin.com/yaduqevuru.vbs
Config: https://hastebin.com/zejazadedu.bash

**Comment by Spearhartt** [comment]
Working on a solution on my fork.

**Comment by creatorfromhell** [comment]
Moved to issue #174
