### ISSUE TITLE
/money set {player} {amount} (world)

### ISSUE THREAD

**Issue by Future-Force** [TheNewEconomy/TNE-Bukkit#194]
1> if i do /money set {player} {amount} (world) it gives errors in console
2> /money set {player} {amount} (world)
3> tne Version 0.0.5.5
4> Spigot 1.12
5> /money set FutureForce 1000 syblock
6>  http://paste.ubuntu.com/25235026/
7> http://paste.ubuntu.com/25235041/

**Comment by creatorfromhell** [comment]
All pre-beta 1 issues will now be getting closed as we near the end of beta testing.
