### ISSUE TITLE
Multi world-Multi currency

### ISSUE THREAD

**Issue by CnocBride** [TheNewEconomy/TNE-Bukkit#196]
Your plugin is by far the cleanest and easiest to use plugin on the market. I would consider Craftconomy3 the next best choice but that plugin is badly documented and confusing to set up and I love this economy plugin except for the astounding lack of support for **Multi currency**.

I run a server and we have 3 worlds: **Factions, Creative and Survival**. People on the creative server like to buy and sell they're houses but I want to keep their balance separate from their Faction and Survival balance. Sadly your plugin does not offer that feature so the creative economy is pretty much ruined. I know you will say "Why does creative need a balance?" well our community is unique and likes it that way. Also some of our Survival and Faction players are unhappy with having to share their balance with the balance in Factions.

**Comment by creatorfromhell** [comment]
I think there's a few exceptions to this issue, mainly the suggested "support for multi currency". Most of this may be answered by simply reading the configuration documentation(https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/Docs/Configurations/Main.md), but I will provide more specific links for convenience.

First, you'll want to enable the Multiworld configuration(https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/src/com/github/resources/config.yml#L12)

Now you'll want to configuration your currency in the worlds configuration file(worlds.yml):
https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/src/com/github/resources/worlds.yml#L16

This allows you to have multiple currencies per world, disable the economy in certain worlds, and share balances with worlds, if needed.

**Comment by creatorfromhell** [comment]
No response in over a month, this will now be closed.
