### ISSUE TITLE
StackOverflowError on command /money top (UUID:false)

### ISSUE THREAD

**Issue by plachta11b** [TheNewEconomy/TNE-Bukkit#204]
TheNewEconomy v0.0.5.5
I have problems with setting up TNE with mysql and UUID turned off.
https://pastebin.com/VhfzjCk6

TheNewEconomy v0.1.0.0 (spigot resource page download)
Crash on start up when mysql used.

I only need /money, /money top, /money pay functionality but I am not able to make this plugin work.

**Comment by creatorfromhell** [comment]
0.0.5.5 is no longer maintained, and for good reason. The issue with 0.1.0.0 is because the MySQL module is still in private testing, which is why you don't see it in the public testing zip.
