### ISSUE TITLE
Always have $700 when using /money

### ISSUE THREAD

**Issue by Timon92** [TheNewEconomy/TNE-Bukkit#210]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What is the issue/bug you're experiencing?
When i use the command "/money", it says me "you have 700$ on you" (when i earn money /money says me the same, i have 700$) but when i use the command "/tne balance [myname]", it shows me my real balance account, and the balance account change every time i earn money.
I tryed to set my balance to 0 use "/tne money set [myname] 0".

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
It always happen when i use /money.

#### TNE version?(exact version number), and whether or not you've made modification to it.
TNE version 0.0.5.5-Repost

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No.

#### debug.txt?(use http://paste.ubuntu.com)
I don't have this file.

#### Spigot/Bukkit version?
Spigot 1.12.2

#### Is your server run in online mode?
No.

#### The exact command you ran w/ arguments?
/money

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
It's the default config.yml because i tried re install.

#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/6gbdpNrjKm/

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
Same, it's the default files.

**Comment by creatorfromhell** [comment]
Essentials forces its economy, that's nothing I set out to do with TNE, that's just how Essentials is, as for chest and sign shops, TNE doesn't have both, the chest holds the stock for the sign shop. This will all be changed in the recode though.
