### ISSUE TITLE
TheNewEconomy Light

### ISSUE THREAD

**Issue by zBoringDrop** [TheNewEconomy/TNE-Bukkit#212]
Report Format
=====================
When i start my server the plugin show this, can you fix? I'm using LIGHT version of TNE
https://paste.ubuntu.com/p/H4BRgN43Hv/

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com) None

AND (if you can)

**Comment by creatorfromhell** [comment]
The light version of TNE hasnt been supported for years. I suggest waiting for beta 1 as it aims to be lightweight.

**Comment by zBoringDrop** [comment]
You know when?
