### ISSUE TITLE
Infinite money problem

### ISSUE THREAD

**Issue by Hanarion** [TheNewEconomy/TNE-Bukkit#217]
Hi, sorry for the last issue, i had not read, so the issue is :
I have a certain amount of money, 500$ for example, when i do /pay  [myname] 500, it gave me 500$ so i have 1000$ in bank, i join a couple of videos with some tests in order to fix the problem but no one worked...
I use TNE version 0.1.0.0
I let the default modules
I use Spigot 1.12.2-R0.1-SNAPSHOT (the latest)
My server is running behind a bungeecord with the server online-mode false
logs with the errors and the pay command : [https://pastebin.com/pQyi4C2E](https://pastebin.com/pQyi4C2E)

The videos :
Base test : [https://youtu.be/49fmBiW3L7M](https://youtu.be/49fmBiW3L7M)
MySql test : [https://youtu.be/peZC4_f-49c](https://youtu.be/peZC4_f-49c)
Default Config + MySql test : [https://youtu.be/5_0QTdWX7Cg](https://youtu.be/5_0QTdWX7Cg)

**Comment by creatorfromhell** [comment]
[Build 2Beta1.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/2072764/Build.2Beta1.zip)
Try using this build, as I am not having the same issue.

**Comment by Hanarion** [comment]
Now it's working fine !
Thanks but in my console i have a lot of :
"[17:41:57] [Craft Scheduler Thread - 4/INFO]: Display: Nahor_Ain
[17:41:57] [Craft Scheduler Thread - 4/INFO]: Handler Contains: town
[17:41:57] [Craft Scheduler Thread - 4/INFO]: Contains?: false"
Messages

And with H2 the baltop still not working

**Comment by Hanarion** [comment]
Also another problem, when i buy something it not take off the money of my account :/

**Comment by Hanarion** [comment]
I think maybe it's my spigot version the problem or my vault version, can i know which version are you using for your tests ?
