### ISSUE TITLE
Support for BungeeCord

### ISSUE THREAD

**Issue by ItzSheldor** [TheNewEconomy/TNE-Bukkit#223]
It would be super if you add Bungeecord Support and support for 1.12.2 :D

**Comment by ItzSheldor** [comment]
How long do u think takes it to integrate this, cause we need a money plugin haha ;D were also willing to pay for this

**Comment by creatorfromhell** [comment]
I wouldn't be able to give a time frame until I started looking into the feature itself. It's definitely a feature I want to take my time on to ensure it's done properly.

**Comment by creatorfromhell** [comment]
https://pastebin.com/TLKbJi85 currency hub
https://pastebin.com/iMv7GVXv currency kingdoms (the one that returns the skript error)

**Comment by 830008** [comment]
This would be a great feature.

**Comment by creatorfromhell** [comment]
Support added.
