### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by creatorfromhell** [TheNewEconomy/TNE-Bukkit#23]
TNE needs a web companion to display user information, and possibly tie-in some web administration too.

**Comment by growlf** [comment]
I, for one would rather expose this data through exterior tools.  For example, if I am using Wordpress, a plugin that simply maps the MYSQL data to fields (post-fields from types is a quick and simple solution).  This will allow greater flexibility and keep your code base smaller and easier to manage. Just my two cents.

**Comment by creatorfromhell** [comment]
The web companion will include a front end and back end(mostly to protect from people selling front end versions) but they will be separated by means of a template engine. This way you could use solely the back end or both the back end and front end.

**Comment by creatorfromhell** [comment]
Closing as this is currently out of scope until we are able to switch to mainly SQL DBs.

**Comment by creatorfromhell** [comment]
Reopening as this will be mainly a PHP Library for reading data from a TNE SQL save.

**Comment by skay1994** [comment]
i can help with php
