### ISSUE TITLE
MySQL error in 1.1.2 beta version

### ISSUE THREAD

**Issue by Momshroom** [TheNewEconomy/TNE-Bukkit#236]
#### What is the issue/bug you're experiencing?
When running 1.1.2 and MySQL, I get a console error on startup: https://pastebin.com/zrjKh1dt
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Update to 1.1.2 Beta and set it to use MySQL
#### TNE version?(exact version number), and whether or not you've made modification to it.
1.1.2 Beta, no modifications
#### TNE build?(/tne build), and whether or not you've made modification to it.
http://prntscr.com/kgfn5o
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
no modifications. The modules that were in the 1.1.2 zip file.  No additions.
#### Spigot/Bukkit version?
1.13
#### Is your server run in online mode?
yes
#### The exact command you ran w/ arguments?
No command needed... error is on startup
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/WsgppFcT
#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/SgMgcMrV
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

Everything works great in 1.1.1 Beta, when I update, whether or not I update the config, I get this error as long as I use MySQL, but NOT if I don't.

**Comment by creatorfromhell** [comment]
Remove the signs module from your modules directory.

**Comment by Momshroom** [comment]
There isn't a signs module there: http://prntscr.com/kh8afg
