### ISSUE TITLE
Can send money to non-excisting accounts

### ISSUE THREAD

**Issue by Nesseley** [TheNewEconomy/TNE-Bukkit#239]
#### What is the issue/bug you're experiencing?
You can use /money pay and send money to players that dont excist. Efficiently losing all your money for good.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Send money to a player that does not excist. "Nesly instead of nesseley"

#### TNE version?(exact version number), and whether or not you've made modification to it.
TheNewEconomy version 0.1.1.2
No modification

#### TNE build?(/tne build), and whether or not you've made modification to it.
You're currently running TNE build 3Beta1
No modification

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
I don't know what this means.

#### Spigot/Bukkit version?
This server is running CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

#### Is your server run in online mode?
Yes

#### The exact command you ran w/ arguments?
/money pay user anynumber

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/KiCNiLhQ

#### Your latest server log file?(use http://paste.ubuntu.com)
dont think this is needed

**Comment by creatorfromhell** [comment]
Is there a reason this is needed? I feel that this functionality could be argued that it's useful for servers to give money to players after a map reset, etc.

**Comment by ArZorMC** [comment]
I know this issue is closed but i am curious what the final verdict was. As I too agree with Nesseley on this one, and i too think a permission to send to accounts that don't exist could be a very elegant solution.

**Comment by creatorfromhell** [comment]
https://github.com/TheNewEconomy/TNE-Bukkit/commit/da5f85669ecbdab440647c7dfc3b7ea5062c9c6d
