### ISSUE TITLE
Server crash [1.13]

### ISSUE THREAD

**Issue by Nesseley** [TheNewEconomy/TNE-Bukkit#243]
#### What is the issue/bug you're experiencing?
Server crash: https://pastebin.com/JyG0D4mj

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
No clue. I have my TNE connected to MYSQL. 

TNE version?(exact version number), and whether or not you've made modification to it.
TheNewEconomy version 0.1.1.2
No modification

TNE build?(/tne build), and whether or not you've made modification to it.
You're currently running TNE build 3Beta1
No modification

Modules Loaded?(exact version number), and whether or not you've made modification to it.
I don't know what this means.

Spigot/Bukkit version?
This server is running CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Is your server run in online mode?
Yes

The exact command you ran w/ arguments?
Ran no command.

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/KiCNiLhQ

**Comment by creatorfromhell** [comment]
Asked for full error log on discord without response. Closing as this was needed for this issue to be investigated.
