### ISSUE TITLE
Player missing from /money top

### ISSUE THREAD

**Issue by Nesseley** [TheNewEconomy/TNE-Bukkit#245]
#### What is the issue/bug you're experiencing?
Player with the most money doesnt show on /money top

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
I don't really know. We used to see him, now hes just gone.

#### TNE version?(exact version number), and whether or not you've made modification to it.
TheNewEconomy version 0.1.1.2

#### TNE build?(/tne build), and whether or not you've made modification to it.
You're currently running TNE build 3Beta1

#### Spigot/Bukkit version?
This server is running CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

#### Is your server run in online mode?
Yes.

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/ZP8U1KYD

#### Your latest server log file?(use http://paste.ubuntu.com)

![image](https://user-images.githubusercontent.com/11998470/44985162-962c6780-af7f-11e8-94a6-4c112e0660c5.png)

**Comment by creatorfromhell** [comment]
This is a known issue.
