### ISSUE TITLE
Lag when transferring money. [MySQL]

### ISSUE THREAD

**Issue by Nesseley** [TheNewEconomy/TNE-Bukkit#249]
#### What is the issue/bug you're experiencing?
When transferring money between accounts the whole server lags for a few seconds. This includes /pay, putting money into towny-accounts(towns) and claiming with towny lags the server.

I saw that this has been reported, but it's not using the setup to report and haven hotten a response - so I'm making this anyway.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
This happens everytime players transfer money.

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.3

#### TNE build?(/tne build), and whether or not you've made modification to it.
7Beta113

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Conversion 0.1.0
H2 0.1.0
Mobs 0.1.0
MySQL 0.1.0
 
#### Spigot/Bukkit version?
CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

#### Is your server run in online mode?
Yes.

#### The exact command you ran w/ arguments?
/pay user 100

#### config.yml?
https://pastebin.com/fDBjwqys

**Comment by creatorfromhell** [comment]
duplicate issue.

**Comment by Nesseley** [comment]
I did. But the other report doesnt use the form. And it states that reports not using the form will be ignored.

**Comment by creatorfromhell** [comment]
Should be fixed in Beta 1.1.4.
