### ISSUE TITLE
Not Hooking into Vault and error.

### ISSUE THREAD

**Issue by RustyDagger** [TheNewEconomy/TNE-Bukkit#25]
I just dropped this into my server to test it out.
All my plugins that rely on vault economy plugin have disabled them self. ( can see in the log )
TNE is spitting an error.

The Log

http://pastebin.com/APPJ22XC

Server version: See line 4 of server log.
Vault Version: Line 20 of log. ( yep its 1 version behind the version only changes banner colors. )

Other line Numbers:

TNE starts loading at Line 29
Line 238 it creates an error then loads...

**Comment by creatorfromhell** [comment]
TNE correctly hooks into Vault as seen here: http://i.imgur.com/OEveTzN.png. There's just no confirmation message for such. Also, I've been unable to reproduce your error, but it's not really an error just a warning that the file trying to be read is more or less empty.

**Comment by RustyDagger** [comment]
Line 179 Ez ranks disables.
Line 174 and 175 vault Lists What it connects too. Note it fails to mention TNE.

DID you test Another PLugin that requires an econ plugin Via Vault. All mine disable. TNE loads But it seems to be Too Late for the other plugins to realise TNE is hooked as the econ plugin.

**Comment by RustyDagger** [comment]
My vault-info command Lists the same as yours BUT all plugins that require an econ plugin disable.

TNE is Hooking into vault Too Late.

**Comment by creatorfromhell** [comment]
The reason TNE isn't in the console is because of the fact it uses the RegisteredServiceProvider to hook into vault, which is the only way you can do this anymore.

**Comment by RustyDagger** [comment]
DID you or did You not test it with a shop Plugin that requires vault?
You can registrar your plugin as vaults econ plugin its Not Impossible what you have now Does not and will not work with other vault plugins. Unless they Load after your Plugin has finished hooking into vault.

Do i need to get a dev to review your code for you and Point out where you have gone wrong.

Iv been running servers since before Hmod and Bukkit. Iv seen this before. 

Test your bloody plugin. before telling me im wrong.

**Comment by creatorfromhell** [comment]
I tested it with BetterShops, and everything worked fine. So, before you go raging about I think you should start checking to make sure the other plugins you use are working fine. I just told you I integrated Vault Support via the RegisteredServiceProvider and not a PR as some plugins have done, I'm well aware of the Vault API as TNE implements it, which maybe you could've seen if you read through the source some. I don't appreciate people leaving nasty comments on my github repos, especially on something that revolves around Minecraft as I do it purely for fun, and nothing more. I will not tolerate nasty comments either.

**Comment by creatorfromhell** [comment]
Also, here's something for your information: http://i.imgur.com/NzQFoM9.png. Works fine with EZRanksLite

**Comment by RustyDagger** [comment]
As you can see from my startup It fails to work. Iv been using the same plugins with gringotts for months Nothing in them has changed not even the config. every other econ plugin iv tested works. 
Its a real shame yours does not. Im at a loss as to how to explain it. and its really frustrating as iv tried every other econ plugin and they all have issues. I could list them but this is hardly the place for that.

Would editing some plugin.yml's of my shop and ranks plugin to soft depend or depend on the econ plugin help I doubt it...

**Comment by creatorfromhell** [comment]
Changing the plugin's YAML file wouldn't help in this situation. Have you tried to copy over each of your plugins into a fresh bukkit server to see if there might be a conflict with any of them?

**Comment by creatorfromhell** [comment]
Could you try using this modified version of TNE and telling me if it works for you? https://dl.dropboxusercontent.com/u/33109032/TNE.jar

**Comment by RustyDagger** [comment]
That version has fixed my issue.

Pro is very much the same as Lite it just has a few more features its only been changed over about a month. most the features is just cosmetic.

**Comment by creatorfromhell** [comment]
That's good to know, and I'll make sure to include it in the 2.2 release, which you now have an early version of. x3

**Comment by RustyDagger** [comment]
Thank you!. I look forward to A Lang file to edit. The white kills me :( I have a Green gold and gray theme in my chat. Im an aussie server.

**Comment by creatorfromhell** [comment]
That's high up on my priority list.
