### ISSUE TITLE
Minor currency dupe.

### ISSUE THREAD

**Issue by En0tS** [TheNewEconomy/TNE-Bukkit#250]
When players have on hands money for example 0.50 (item currenncy, only minor), he get full inventory of minor currency items after rejoin

before rejoin: https://ibb.co/mK7WT0 (balance: 0.5)
after rejoin: https://ibb.co/ind21L (balance: 0.24)

Config: https://pastebin.com/7Da5Mh71
spigot 1.12.2 b1648, latest TNE for 1.12, bungeecord, no errors in console, offline mode.

Offtop: messages spam on player join https://ibb.co/esNWT0

**Comment by creatorfromhell** [comment]
Please use the correct format.

**Comment by En0tS** [comment]
What is the issue/bug you're experiencing?
When players for example 0.50 (item currenncy, only minor), he get full inventory of minor currency items after rejoin

How can the issue be reproduced?(i.e. the steps to make the issue occur again)
just use itemcurrency and rejoin with minor currency in inventory

TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.4

TNE build?(/tne build), and whether or not you've made modification to it.
1Beta114

Modules Loaded?(exact version number), and whether or not you've made modification to it.
only H2

Spigot/Bukkit version?
spigot 1.12.12, build 1648

Is your server run in online mode?
No

The exact command you ran w/ arguments?
no commands

config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/7Da5Mh71

Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/aCBL7tbq

If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

**Comment by En0tS** [comment]
P.S. Sorry for my english....

**Comment by creatorfromhell** [comment]
Fixed in latest commits, arriving in Beta 1.1.5.

**Comment by En0tS** [comment]
Can I get dev build?

**Comment by En0tS** [comment]
Can I get dev build?

**Comment by creatorfromhell** [comment]
Just saw your comment. Here's a beta build for 1.13.2
[TNE-0.1.1.5-Build-1-MC-1.13.2.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/2520164/TNE-0.1.1.5-Build-1-MC-1.13.2.zip)
