### ISSUE TITLE
Give command doesn't work

### ISSUE THREAD

**Issue by Yvharos** [TheNewEconomy/TNE-Bukkit#253]
#### What is the issue/bug you're experiencing?
Give command doesn't work
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
/money give
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.4
#### TNE build?(/tne build), and whether or not you've made modification to it.
TNE Build 1beta114
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Conversion, H2, Mobs, MySQL all in the latest version
#### Spigot/Bukkit version?
1.12.2
#### Is your server run in online mode?
No
#### The exact command you ran w/ arguments?
money give Yvharos 10000
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/mKt6JfpwtH/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/BSMwcjFVDd/

**Comment by creatorfromhell** [comment]
This is a known issue with the "," decimal point. Beta 1.1.5 will be out tomorrow to fix the issue, until then the workaround is to switch back to "." for decimals.
