### ISSUE TITLE
Minor currency having wrong value

### ISSUE THREAD

**Issue by OmegaJT22** [TheNewEconomy/TNE-Bukkit#254]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What is the issue/bug you're experiencing?
I created a minor currency called "Iron" with a weight of 1. With Minor weight set at 10, and decimal places set at 1. However in game it shows the item to have a value of 0.01 when I want it to have a value of 0.1.
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Minor: weight = 1
Minor_weight: 10
DecimalPlaces: 1
#### TNE version?(exact version number), and whether or not you've made modification to it.
1.1.5
#### TNE build?(/tne build), and whether or not you've made modification to it.
2beta115, no modification
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Conversion.jar, No modification to any
H2.jar
Mobs.Jar
MySQL.jar
#### Spigot/Bukkit version?
Spigot 1.13.2
#### Is your server run in online mode?
No
#### The exact command you ran w/ arguments?
N/A
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/QryrmbnZ
#### Your latest server log file?(use http://paste.ubuntu.com)
^^^
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

**Comment by creatorfromhell** [comment]
This is due to a misconfiguration. Minor: weight is the value of the minor currency, while minor_weight is how the amount of minor it takes to make one major.

in order to do what you want, you should set Minor: to 10 and minor_weight to 100

**Comment by OmegaJT22** [comment]
I did what you said, and it still shows up as a value of 0.01.

**Comment by OmegaJT22** [comment]
![image](https://user-images.githubusercontent.com/24376568/47886240-e9e3f180-de06-11e8-86e8-745993e60ea0.png)
![image](https://user-images.githubusercontent.com/24376568/47886250-f36d5980-de06-11e8-9043-3de531e87eb1.png)
![image](https://user-images.githubusercontent.com/24376568/47886261-041dcf80-de07-11e8-86cd-d95ddd2653a2.png)
Here are some pictures for context.

**Comment by creatorfromhell** [comment]
What happens when you set iron to 10?

**Comment by OmegaJT22** [comment]
When I set iron to 10 it acts like $10.00 each.
![image](https://user-images.githubusercontent.com/24376568/47923111-8e594880-de86-11e8-899d-888caf6282bb.png)

**Comment by creatorfromhell** [comment]
.10 not just 10

**Comment by OmegaJT22** [comment]
I've done that before, and it still shows as $0.01. I'll try without the zero in front to see if that makes a difference somehow.

**Comment by OmegaJT22** [comment]
It doesn't. Still shows as $0.01

**Comment by creatorfromhell** [comment]
Ok, I'll look into this one.

**Comment by creatorfromhell** [comment]
Have you tested this in Beta 1.1.6?
