### ISSUE TITLE
TNE verbose toggle

### ISSUE THREAD

**Issue by OpalMoonstride** [TheNewEconomy/TNE-Bukkit#260]
#### What feature are you suggesting be added?
a "/tne verbose" toggle to turn on/off saving, account checks, and player actions. 
#### Expected use-case for said feature?
I have a few other plugins which list which permission is missing, during verbose mode, if a player uses a command, but does not have the corresponding permission.
#### Why should this feature be added to TNE?
 This may reduce TNE-"spam" in my console with my small server (as it shows accounts, and  when it saves), and let me see what's happening for testing purposes. 
Usually this is what I'm seeing "spammed":
[TheNewEconomy] Null Account Count: #
[TheNewEconomy] Finished saving data!

Apologies if this is already available, and I missed it.

**Comment by creatorfromhell** [comment]
The saving data messages will be removed, as for player actions, there's not really a need for it as we maintain permissions nodes in our commands and permissions documentation: https://github.com/TheNewEconomy/TNEDocumentation/blob/master/Commands.md

**Comment by creatorfromhell** [comment]
I don't think this feature will be added as we have our online documentation, and Permissions plugins such as LuckPerms do this for all plugins.
