### ISSUE TITLE
/money set doesn't work

### ISSUE THREAD

**Issue by OpalMoonstride** [TheNewEconomy/TNE-Bukkit#261]
#### What is the issue/bug you're experiencing?
/money set [player] [$] does not work. I see no error messages. Player's money is not reset; output is just a repeat of the current balance - unchanged. Admin has permission "tne.money.set". Does not work from console, either.
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
type /money set [player] [$]
#### TNE version?(exact version number), and whether or not you've made modification to it.
TNE version 0.1.1.7
#### TNE build?(/tne build), and whether or not you've made modification to it.
TNE build 3Beta115
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No modules.
#### Spigot/Bukkit version?
Server version: Paper("684bd2a") 1.13.2-R0.1-SNAPSHOT
#### Is your server run in online mode?
offline with bungee auth
#### The exact command you ran w/ arguments?
/money set Cuppa_Cocoa 0
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/sKjSjyhJ
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/nTSmG959yJ/

**Comment by creatorfromhell** [comment]
Do you have a server ip I could connect to to test this as this seems very strange.

**Comment by OpalMoonstride** [comment]
Yeah: play.tericlya.com. 
Let me know your username and I can whitelist you
can also ping cocoa on the discord https://discord.gg/UnPephF

**Comment by OpalMoonstride** [comment]
Oh, fixed! Thanks creatorfromhell! 
CMI has commands which override TNE. Just have to set them to /cmi bal etc. Closing for you :D
