### ISSUE TITLE
tne_balances_history table is growing very quickly

### ISSUE THREAD

**Issue by oranges13** [TheNewEconomy/TNE-Bukkit#263]
# Bug Report Format
#### What is the issue/bug you're experiencing?
tne_balances_history table is growing very quickly

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
We just enabled the module on our server and have noticed the issue. Plugin has been running ~7 hours and the tne_balances_history table has 300k records already

#### TNE version?(exact version number), and whether or not you've made modification to it.
Beta 1.17

#### TNE build?(/tne build), and whether or not you've made modification to it.
3beta115

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
`This server is currently uses these TNE Modules: MySQL, Mobs, H2, Conversion.`

#### Spigot/Bukkit version?
1.13.2-R0.1-SNAPSHOT

#### Is your server run in online mode?
Yes.

#### The exact command you ran w/ arguments?
n/a

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/8gQYf2tbr6/

#### Your latest server log file?(use http://paste.ubuntu.com)
n/a (no error in log)

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
n/a

**Comment by creatorfromhell** [comment]
This is mainly due to the nature of the table itself; most likely itll be removed entirely from beta 1.1.8, but this isnt a bug.

**Comment by oranges13** [comment]
Is there any way to slow the growth of the table? It seems to be creating multiple records per player every second, and I'm not sure what use that could be. Let me know if there's a config setting or something we can do to make it stop updating as often.
