### ISSUE TITLE
REQUEST: lowercase mysql table names

### ISSUE THREAD

**Issue by Azotorp** [TheNewEconomy/TNE-Bukkit#264]
Instead of BALANCES, CHARGES etc, could we have them in lowercase?
MySQL with linux sees tables named "BALANCES" and "balances" as separate tables and not the same.

So in a typical SQL query we have to put quotes around the table names like `BALANCES` etc

**Comment by creatorfromhell** [comment]
There's no plans to modify the table naming scheme in terms of upper vs lower case.
