### ISSUE TITLE
/convert iconomy --> ClassNotFoundException

### ISSUE THREAD

**Issue by KleinDevDE** [TheNewEconomy/TNE-Bukkit#265]
#### What is the issue/bug you're experiencing?
Converting from iConomy to TheNewEconomy

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
/convert iconomy

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.7

#### TNE build?(/tne build), and whether or not you've made modification to it.
3Beta115

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Mobs (0.1.0)
MySQL (0.1.1)
H2 (0.1.1)
Conversion (0.1.0) 

#### Spigot/Bukkit version?
Paperclip 476 (MC 1.13.2)
'
#### Is your server run in online mode?
yes

#### The exact command you ran w/ arguments?
/convert iconomy

#### config.yml?
https://pastebin.com/C2NfZWZN

#### Your latest server log file?
https://pastebin.com/PkjaWLBp

#### If this is to do with messages/world/player configurations, please include the YAML file for such
https://pastebin.com/gQbqs1HS

**Comment by creatorfromhell** [comment]
This mainly looks like an issue with the conversion module not being updated when I redid the database code. Will have a fix for this later today.

**Comment by creatorfromhell** [comment]
[Conversion.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/2708093/Conversion.zip)
Try this updated conversion module.
