### ISSUE TITLE
Repeating MYSQL related console errors leading to crashes after updating to 0.1.1.17

### ISSUE THREAD

**Issue by Momshroom** [TheNewEconomy/TNE-Bukkit#266]
#### What is the issue/bug you're experiencing?
The server is periodically crashing with mysql errors mentioning TNE and CMI.  I've recently updated from TNE 0.1.1.3 to 0.1.1.7, which I think is the precipitating event.  I have tried updating the server to 1.13.2 (we had been running 1.13.1), but it didn't help.  
We had previously had occasional console errors mentioning both plugins, but they were only on login before this and never led to a crash.  Now the new errors always do.  The errors/crashes occur more often if someone spams logins and happen every time we get to ten players.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Have 10 people log in or have someone log in and out repeatedly.

Report Description: 
TNE Version: 0.1.1.7
TNE Build: 3Beta115
Modules Loaded: Tutorial, MySQL, Conversion
API: CraftBukkit
API Version: git-Spigot-518206a-a5b9c7b (MC: 1.13.2)
Online Mode: true
config.yml: https://pastebin.com/KJ2hxfKs
latest.log: https://pastebin.com/tLj6N49F
log showing errors and crash: https://pastebin.com/iy9gtnik

**Comment by Momshroom** [comment]
Update: resetting the economy didn't fix the issue, removing TNE did.  So did removing CMI.  The server runs fine with one or the other, but crashes with both loaded.  Economy in CMI is disabled.

**Comment by Momshroom** [comment]
Update: resetting the economy didn't fix the issue, removing TNE did.  So did removing CMI.  The server runs fine with one or the other, but crashes with both loaded.  Economy in CMI is disabled. Both are using mysql

**Comment by Momshroom** [comment]
https://github.com/Zrips/CMI-API/issues/7  The CMI ticket for this issue.

https://github.com/Zrips/CMI-API/issues/7 Where the error passes from TNE to CMI.  I have econ disabled in CMI, so I'm not even sure why a CMI econ module call would be used.

**Comment by creatorfromhell** [comment]
I started looking into pausible causes for this and will update this ticket as needed.

**Comment by Momshroom** [comment]
For what it's worth, I DID have console errors mentioning both TNE and CMI in TNE 0.1.1.13 and 0.1.1.14, but they didn't lead to a crash... I'll test with 0.1.1.15 and 16 shortly.
