### ISSUE TITLE
Faction Issue with Economy

### ISSUE THREAD

**Issue by lueljohn** [TheNewEconomy/TNE-Bukkit#27]
Good day sir!

Perhaps hook it up with the Factions Plugin, that would be nice. thank you!

18.10 08:21:00 [Multicraft] Skipped 6 lines due to rate limit (30/s)
18.10 08:20:51 [Server] INFO at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:617) ~[?:?]
18.10 08:20:51 [Server] INFO at com.massivecraft.factions.cmd.CmdFactionsMoneyDeposit.perform(CmdFactionsMoneyDeposit.java:49) ~[?:?]
18.10 08:20:51 [Server] INFO at com.massivecraft.factions.integration.Econ.transferMoney(Econ.java:101) ~[?:?]
18.10 08:20:51 [Server] INFO at com.massivecraft.factions.integration.Econ.transferMoney(Econ.java:142) ~[?:?]
18.10 08:20:51 [Server] INFO at com.massivecraft.massivecore.money.Money.move(Money.java:146) ~[?:?]
18.10 08:20:51 [Server] INFO at com.massivecraft.massivecore.money.MoneyMixinAbstract.move(MoneyMixinAbstract.java:58) ~[?:?]
18.10 08:20:51 [Server] INFO at com.massivecraft.massivecore.money.MoneyMixinVault.move(MoneyMixinVault.java:165) ~[?:?]
18.10 08:20:51 [Server] INFO at com.massivecraft.massivecore.money.MoneyMixinVault.ensureExists(MoneyMixinVault.java:201) ~[?:?]
18.10 08:20:51 [Server] INFO at com.github.tnerevival.core.TNEVaultEconomy.hasAccount(TNEVaultEconomy.java:294) ~[?:?]
18.10 08:20:51 [Server] INFO at com.github.tnerevival.core.api.TNEAPI.accountExists(TNEAPI.java:21) ~[?:?]
18.10 08:20:51 [Server] INFO at com.github.tnerevival.core.api.TNEAPI.getAccount(TNEAPI.java:61) ~[?:?]
18.10 08:20:51 [Server] INFO Caused by: java.lang.NullPointerException
18.10 08:20:51 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_85]
18.10 08:20:51 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_85]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit_beta.jar:git-Spigot-5f38d38-12698ea]
18.10 08:20:51 [Server] INFO at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:99) ~[?:?]
18.10 08:20:51 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'f money deposit 10' in com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand(f)
18.10 08:20:51 [Server] ERROR null

**Comment by creatorfromhell** [comment]
This is next in my queue of things to do today. Shouldn't be long, but I'll probably give a test be to make sure it works before releasing the fix.

**Comment by creatorfromhell** [comment]
BTW, quick question, at what point does it throw this error? Were you using a particular factions command?

**Comment by creatorfromhell** [comment]
As a note MassiveCraft Factions is making use of deprecated Vault API methods, which TNE will most likely stop supporting in the near future, but I'll still fix this issue.

**Comment by creatorfromhell** [comment]
Patch released. https://www.spigotmc.org/resources/the-new-economy.7805/update?update=50114

**Comment by lueljohn** [comment]
Thank you sir, I owe you one <3
