### ISSUE TITLE
Balance did not shared between worlds expectedly.

### ISSUE THREAD

**Issue by MonikaCODE** [TheNewEconomy/TNE-Bukkit#273]
Issues: Balance did not shared between worlds expectedly.
TNE version: 0.1.1.6-1.12.2
TNE build: 2Beta115
Loaded Modules: 
- Conversion 0.1.0
- H2 0.1.1
- Mobs 0.1.0
- MySQL 0.1.1

API: CraftBukkit
Spigot/Bukkit version: CatServer version Personal-289f343 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Online-mode: true
config.yml: https://paste.ubuntu.com/p/cxSWMNC7gV/
worlds.yml: https://paste.ubuntu.com/p/P4ckmFdRSb/
lastes.log: https://paste.ubuntu.com/p/PNnDTv5Gtc/

**Comment by creatorfromhell** [comment]
This has been fixed in the latest 0.1.1.8 beta build
