### ISSUE TITLE
Server Freezes

### ISSUE THREAD

**Issue by freethemice** [TheNewEconomy/TNE-Bukkit#275]
I have version 0.1.1.8 running on 1.13.2 of and the server got slower and slower on start up until now it freezes
`09.02 15:29:17 [Server] INFO [TheNewEconomy] Enabling TheNewEconomy v0.1.1.8
09.02 15:29:17 [Server] INFO [TheNewEconomy] Found module: Tools version: 0.1.0
09.02 15:29:17 [Server] INFO [TheNewEconomy] Found module: MySQL version: 0.1.1
09.02 15:29:17 [Server] INFO [TheNewEconomy] Found module: Mobs version: 0.1.0
09.02 15:29:17 [Server] INFO [TheNewEconomy] Found module: Signs version: 0.1.0
09.02 15:29:17 [Server] INFO [TheNewEconomy] Found module: H2 version: 0.1.1
09.02 15:29:17 [Server] INFO [TheNewEconomy] Found module: Conversion version: 0.1.0
09.02 15:29:17 [Server] INFO Signs Module loaded!
09.02 15:29:17 [Server] INFO MySQL Module loaded!
09.02 15:29:17 [Server] INFO Mobs Module loaded!
09.02 15:29:17 [Server] INFO Tools Module loaded!
09.02 15:29:17 [Server] INFO H2 Module loaded!
09.02 15:29:17 [Server] INFO [TheNewEconomy] Conversion Module loaded!
09.02 15:29:17 [Server] INFO Loading Configurations.
09.02 15:29:17 [Server] INFO Initializing Configurations.`

**Comment by creatorfromhell** [comment]
Please use the correct format, and make a new ticket. The format is there for a reason and is not negotiable
