### ISSUE TITLE
Players loosing all gold when logging back on to server

### ISSUE THREAD

**Issue by bunny119** [TheNewEconomy/TNE-Bukkit#278]
#### The exact command you ran w/ arguments? No command being runned
 
28.02 22:50:22 [Server] INFO AccountListener ID? 3133edfb-a0fe-4bb1-aed7-1b5020d40f8e
28.02 22:50:22 [Server] INFO AccountListener Account null? false
28.02 22:50:22 [Server] INFO AccountListener ID? 3133edfb-a0fe-4bb1-aed7-1b5020d40f8e
28.02 22:50:22 [Server] INFO AccountListener Account null? false
28.02 22:50:22 [Server] INFO Return World Manager for world Earth 1.0
28.02 22:50:22 [Server] INFO =====START Account.setItems =====
28.02 22:50:22 [Server] INFO Holdings: 0
28.02 22:50:22 [Server] INFO Old: 0.00
28.02 22:50:22 [Server] INFO difference: 0.00
28.02 22:50:22 [Server] INFO difference: 0.00
28.02 22:50:22 [Server] INFO differenceString: 0.00
28.02 22:50:22 [Server] INFO =====START WorldFinder.getWorld =====
28.02 22:50:22 [Server] INFO Player is null
28.02 22:50:22 [Server] INFO workingAmount: 0
28.02 22:50:22 [Server] INFO itemAmount: 0
28.02 22:50:22 [Server] INFO itemActual: 0
28.02 22:50:22 [Server] INFO actualAmount: 0
28.02 22:50:22 [Server] INFO workingAmount: 0
28.02 22:50:22 [Server] INFO ADDDING MAJOR!!!!!!!!!!!!!!!!!!!!
28.02 22:50:22 [Server] INFO STRING: 0.00
28.02 22:50:22 [Server] INFO Split Length: 2
28.02 22:50:22 [Server] INFO SPLIT2: 0
28.02 22:50:22 [Server] INFO SPLIT2: 00
28.02 22:50:22 [Server] INFO Minor Amount: 0
28.02 22:50:22 [Server] INFO MajorChange: 0
28.02 22:50:22 [Server] INFO MinorChange: 0
28.02 22:50:22 [Server] INFO =====END Account.setItems =====
28.02 22:50:22 [Server] INFO Saving account: bunny119
28.02 22:50:22 [Server] INFO TNEUUIDManager.addUUID(username: bunny119, uuid: 3133edfb-a0fe-4bb1-aed7-1b5020d40f8e)
28.02 22:50:22 [Server] INFO IDListener.put

**Comment by creatorfromhell** [comment]
V 0.1.1.1 is way out of date.
