### ISSUE TITLE
Error when updating plugin

### ISSUE THREAD

**Issue by bunny119** [TheNewEconomy/TNE-Bukkit#279]
When I got to update my current TNE Plugin, (which is 1.1.1) to (1.1.7) the config files from 1.1.1 stay there even when I delete them. The config files 1.1.7 generates when the server opens is the same as the 1.1.1 config. It even says "Version 1.1.1" even know I change it to 1.1.7. The config files don't even work on the server because it's outdated. I deleted the old configs from 1.1.1 but the 1.1.7 plugin generates my old 1.1.1 configs and they don't even work in-game. 

The version is 1.1.7 
I have not made any modications 
Spigot 13.2
#### The exact command you ran w/ arguments? No commands begin runned

Here are the configs made by the 1.1.7 TNE, As you can see it's the same as my old 1.1.1 configs and even says "1.1.1" at the top. These configs don't work in-game and they go to the default 1.1.7 configs, I would like to change it but I can't because this is what I get when going into my config files. 

# The New Economy v0.1.1.1
# Author: creatorfromhell
# License: http://creativecommons.org/licenses/by-nc-nd/4.0/
# If you would like to contribute to the plugin
# you can do so via Github at https://github.com/TheNewEconomy/TNE-Bukkit
# To donate to the continued development of TNE with perks, https://patreon.com/creatorfromhell
# To view a commented version of this file, visit https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/TNE/src/net/tnemc/resources/config.yml.
Core:
  UUID: true
  Multiworld: false
  Server:
    MenuMaterial: GOLD_INGOT
    MobDrop: true
    Consolidate: false
    ExperienceGain: false
    CurrencyTrading: true
    Name: Main Server
    Account:
      Enabled: true
      Name: Server_Account
      Balance: 500
    ThirdParty:
      Stats: true
      Town: town-
      Nation: nation-
      Faction: faction-
      McMMORewards: true
      TopThirdParty: true
    TNEMod: false
    CurrencyCrafting: true
  Commands:
    Triggers: /
    PayShort: true
    BalanceShort: true
    TopShort: true
  Update:
    Check: true
    Notify: true
  Transactions:
    Format: M, d y
    Timezone: US/Eastern
  AutoSaver:
    Enabled: true
    Interval: 600
  Currency:
    Info:
      Advanced: false
    Basic:
      Major_Single: Dollar
      Major_Plural: Dollars
      Minor_Single: Cent
      Minor_Plural: Cents
      Prefixes: kMGTPEZYXWVUN₮
      Symbol: $
      ItemCurrency: false
      ExperienceCurrency: false
      Items:
        GOLD_INGOT: 1
        GOLD_NUGGET: 0.01
      Virtual:
        Dollar: 1
        Cent: 0.01
      Options:
        Format: <symbol><major.amount><decimal><minor.amount>
        MaxBalance: 900000000000000000000000000000000000000000000
        Balance: 200.0
        Decimal: .
        EnderChest: true
        Major_Separate: true
        Major_Separator: ','
        Minor_Weight: 100
      Note:
        Notable: false
        Fee: 0.0
        Minimum: 0.0
      Server: Main Server
  World:
    EnableChangeFee: false
    ChangeFee: 5.0
  Database:
    Type: h2
    Prefix: TNE
    Backup: true
    File: Economy
    MySQL:
      Host: localhost
      Port: 3306

**Comment by creatorfromhell** [comment]
The version in the configuration file doesn't reflect the current version.....
