### ISSUE TITLE
PlayerInteractEvent Error

### ISSUE THREAD

**Issue by Doxify** [TheNewEconomy/TNE-Bukkit#280]
#### What is the issue/bug you're experiencing?
PlayerInteractEvent error
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Right click a Citizens NPC and utilizing the GOLD_INGOT. There's possibly more ways to trigger this.
#### TNE version?(exact version number), and whether or not you've made modification to it.
Beta 1.1.8 Vanilla
#### TNE build?(/tne build), and whether or not you've made modification to it.
no
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
The ones that come with Beta 1.1.8
#### Spigot/Bukkit version?
CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
#### Is your server run in online mode?
No, but I'm running Bungee which is in online mode.
#### The exact command you ran w/ arguments?
None.
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
default
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/B3sPwtMyrX/

**Comment by creatorfromhell** [comment]
This has already been patched for inclusion in the next release
