### ISSUE TITLE
Error on startup. Hope this is useful :)

### ISSUE THREAD

**Issue by Patrick-van-Halm** [TheNewEconomy/TNE-Bukkit#283]
#### What is the issue/bug you're experiencing? 
An error on startup (not breaking the plugin just annoying)
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Unknown
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.7-Repost
#### TNE build?(/tne build), and whether or not you've made modification to it.
3Beta115
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
none
#### Spigot/Bukkit version?
Spigot-1.13.2-0c02b0c-20190425-0538
#### Is your server run in online mode?
yes
#### The exact command you ran w/ arguments?
none
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
default just mysql connected
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/fyYr9CGV6h/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
nope

**Comment by creatorfromhell** [comment]
This is an issue pertaining to the configuration file, but as you did not follow the proper reporting format, and failed to include the config.yml this issue will now be closed.
