### ISSUE TITLE
Error on startup (repost with config now)

### ISSUE THREAD

**Issue by Patrick-van-Halm** [TheNewEconomy/TNE-Bukkit#284]
#### What is the issue/bug you're experiencing? 
An error on startup (not breaking the plugin just annoying) (same as my previous issue but with config now as i didnt know it was a problem in there lol)
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Unknown
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.7-Repost
#### TNE build?(/tne build), and whether or not you've made modification to it.
3Beta115
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Found module: Conversion version: 0.1.0
12.05 05:00:17 [Server] INFO [TheNewEconomy] Found module: Mobs version: 0.1.0
12.05 05:00:17 [Server] INFO [TheNewEconomy] Found module: MySQL version: 0.1.1
12.05 05:00:17 [Server] INFO [TheNewEconomy] Found module: H2 version: 0.1.1
12.05 05:00:17 [Server] INFO Mobs Module loaded!
12.05 05:00:17 [Server] INFO MySQL Module loaded!
12.05 05:00:17 [Server] INFO H2 Module loaded!
12.05 05:00:17 [Server] INFO [TheNewEconomy] Conversion Module loaded!
#### Spigot/Bukkit version?
Spigot-1.13.2-0c02b0c-20190425-0538
#### Is your server run in online mode?
yes
#### The exact command you ran w/ arguments?
none
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/QT5zNnxwPf/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/fyYr9CGV6h/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
nope

**Comment by creatorfromhell** [comment]
Change line 19 of your config.yml
It is currently `Enabled: fold` and should be `Enabled: false`
