### ISSUE TITLE
Supporting 1.14.1

### ISSUE THREAD

**Issue by ziemniok99** [TheNewEconomy/TNE-Bukkit#285]
Is this plugin supports 1.14.1

**Comment by creatorfromhell** [comment]
The 1.14 supporting version of tne will be out Monday around 11pm EST.

**Comment by ziemniok99** [comment]
Great

**Comment by creatorfromhell** [comment]
Check out https://www.spigotmc.org/resources/the-new-economy.7805/update?update=278544
