### ISSUE TITLE
Request: Console Commands in server sign shops

### ISSUE THREAD

**Issue by ElKayMa** [TheNewEconomy/TNE-Bukkit#286]
#### What feature are you suggesting be added?
I like the sign shops have the feature of execute console commands. For example, with a reward currency the player do a click on the sign and obtain a special rank.

#### Expected use-case for said feature?
I want  to  give a bonus or reward coin to my users (for finish quests and stuff like that) so they can buy special stuff like ranks, cusstom weapons etc.

#### Why should this feature be added to TNE?
I guess the capability to "buy commands" have a lot of possibilities. Have  a many currencies as the economy and the players only can buy vanilla stuff? Feels like a huge limitation for a huge plugin as a TNE 

Thanks!

**Comment by creatorfromhell** [comment]
I'm down for adding this.
