### ISSUE TITLE
Vault: Multiworld setting ignored

### ISSUE THREAD

**Issue by EpicEricEE** [TheNewEconomy/TNE-Bukkit#291]
#### What is the issue/bug you're experiencing?
When using the `getBalance(player, world)` function of Vault (the plugin), it does not return the correct balance if `Multiworld` is set to false in TNE's config. Instead, it returns the balance in the given world, which does not equal the balance that would be returned if no world was given.
_(See EpicEricEE/ShopChest#259)_
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Install a plugin that calls the above function `getBalance(player, world)` (in my case [ShopChest](https://ci.codemc.org/job/EpicEricEE/job/ShopChest/lastSuccessfulBuild/)), create an admin shop in the nether and try to buy from it. You'll receive a `Not enough money` message.
As the command `/bal <name> world_nether` shows, you have no money in the nether world.
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.8 without modifications
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta118c without modifications
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
H2 v0.1.1
#### Spigot/Bukkit version?
CraftBukkit version git-Spigot-01d0f04-455023c (MC: 1.14.2)
Vault version 1.7.2-b107
#### Is your server run in online mode?
No
#### The exact command you ran w/ arguments?
--
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/35YrmspJK2/ (default)
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/VsyHrVJkzT/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
`worlds.yml`: https://paste.ubuntu.com/p/PRfT4fjF6K/ (default)
However, when setting it to share balances between worlds (see below), it works. However, that is not what I would expect, since the setting `Multiworld` in `config.yml` is disabled.
https://paste.ubuntu.com/p/6k6j6PJs6r/

**Comment by creatorfromhell** [comment]
If multiworld is set to false it uses the default world as the balance world. This is the intended function

**Comment by EpicEricEE** [comment]
But then Vault should return the balance for the default world and not the one the one that is put in the `getBalance(player, world)` function.

**Comment by creatorfromhell** [comment]
Which is why tne overrides the world variable provided if multiworld is set to false. This is the intended function for the plugin.

**Comment by EpicEricEE** [comment]
Does it really? The world parameter should be overridden, however, the function still returns the balance in the given world, not in the default world.
I've made a quick demo video in case I didn't describe my issue properly: https://www.youtube.com/watch?v=2c4YKAvtc6E

**Comment by creatorfromhell** [comment]
Yes it does, but as you haven't followed the proper report format, I don't have a copy of the configuration to validate proper configuration took place.

**Comment by EpicEricEE** [comment]
Where did I now follow the report format? Did I miss something?

**Comment by creatorfromhell** [comment]
My bad, didn't notice the config file up there. Let me do some local testing on this.

**Comment by creatorfromhell** [comment]
Tested this without issue. Of course, my local jar is miles ahead of the github/official builds. If you could confirm this. The jar I am using is attached.
[TNE-1.1.8.17.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/3254457/TNE-1.1.8.17.zip)

**Comment by EpicEricEE** [comment]
It works kind of with that build. When I enable `Multiworld`, the world is still overridden and when I enter `/bal <player> <world>`, I get this NPE for any entered world (e.g. `world` or `world_nether`):
```
[17:15:13 INFO]: EpicEric issued server command: /bal EpicEric world
[17:15:13 WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.8 generated an exception while executing task 25
java.lang.NullPointerException: null
        at net.tnemc.core.common.currency.CurrencyFormatter.format(CurrencyFormatter.java:46) ~[?:?]
        at net.tnemc.core.common.currency.CurrencyFormatter.format(CurrencyFormatter.java:29) ~[?:?]
        at net.tnemc.core.commands.money.MoneyBalanceCommand.lambda$execute$1(MoneyBalanceCommand.java:146) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.2.jar:git-Paper-65]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.2.jar:git-Paper-65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by creatorfromhell** [comment]
Ok that is an issue I'll have to look into, was only interested in if it was fixed with multiworld sent to false.

**Comment by EpicEricEE** [comment]
Yes, I guess, but since the world override now also takes place with multiworld set to true, I'm not 100% sure.

**Comment by creatorfromhell** [comment]
Just tested this and it works for me? http://prntscr.com/ny0hxf Did you set it to true then start your server or use /tnec set?

**Comment by EpicEricEE** [comment]
I set it to true and then started the server. Also, you don't have the world in your balance message, did you use the same command as me?

**Comment by creatorfromhell** [comment]
That's not how the bal command works.... The first argument is the player name. 

From messages.yml: "/money balance [world] [currency] - Displays your current holdings."

**Comment by EpicEricEE** [comment]
Oh okay, sorry. When using the right command, it seems to work correctly. Thank you
