### ISSUE TITLE
MySQL Error on startup

### ISSUE THREAD

**Issue by ModdyLP** [TheNewEconomy/TNE-Bukkit#30]
I have this error on startup. 
Enabling TheNewEconomy v0.0.2.3
[17:01:28 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

Best Regards
ModdyLP

**Comment by creatorfromhell** [comment]
Could you paste the full error?

**Comment by creatorfromhell** [comment]
Should be fixed in the next commit, which will be dropping tonight.

**Comment by ModdyLP** [comment]
Sorry that i didnt answer. I was away for a few days. I will now take a look if i can find the complete error log and if i didnt find it i will try to reproduce it.

**Comment by ModdyLP** [comment]
Here is the complete error: http://pastebin.com/50UDGXAW

Sorry that i didnt copy the complete error last time.

**Comment by creatorfromhell** [comment]
Should be fixed in Alpha 2.4 https://www.spigotmc.org/resources/the-new-economy.7805/update?update=53941

**Comment by ModdyLP** [comment]
Hello
i have setup the mysql connection now with no errors but if i want to buy a bank(price: 500) there came the congrualiations message and i have no bank. Becouse i proof that with /bank view. Also if i look in the MySQl Database there is no bank saved and no money saved for my useraccount. In the console is no error so i cant post some.

**Comment by creatorfromhell** [comment]
Without an error message, or information to reproduce the error there isn't much to go on. I've tested banks with MySQL on the latest commit and everything worked as suspected.

**Comment by ModdyLP** [comment]
i am using spigot 1.8.8 and mysql v.5.3
If there an option to turn debug messages on, so i can see where the error is?

**Comment by creatorfromhell** [comment]
Apparently there is no error or it would've printed a stacktrace out. I double checked on my end and everything works with MySQL, SQLite, and FlatFile.
