### ISSUE TITLE
My friends can't access /money

### ISSUE THREAD

**Issue by LittleDanGaming** [TheNewEconomy/TNE-Bukkit#300]
My friends and I started what we call a 'Currency World' with this plugin, my friends can't access /money and it comes up the server command in config.yml (or whatever) which says they can't access it. **IM VERY NEW TO THIS CODING STUFF FOR PLUGINS** So I really need help with this so we can start it.

**Comment by creatorfromhell** [comment]
Youll need a permissions plugin, and then youll have to configure the permissions nodes from the wiki
