### ISSUE TITLE
MobDrop: true is not functioning properly with physical currencies

### ISSUE THREAD

**Issue by ChaseIzKing** [TheNewEconomy/TNE-Bukkit#313]
#### What is the issue/bug you're experiencing?
This config option:
```
#Whether or not mob drops that are a currency item should be disabled.
MobDrop: true
```

Is not working. I use gold as my server currency, and zombie pigmen still drop gold nuggets.
I have tried:
- Disabling the mob module
- Enabling the mob module and setting rewards to 0
- Removing the mob module
- Using a completely fresh config file (altered to accept physical gold) and server with no other plugins

Nothing so far has worked and I had to disable pigmen on my server until this is fixed

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)

Simply enable this config option and use gold as a physical currency (nuggets included)
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.8e
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta118e
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Signs, Mobs, and Conversion. There is no way to get the module version that I can tell, but they came with version 0.1.1.8e
#### Spigot/Bukkit version?
git-Paper-126 for MC 1.14.3
#### Is your server run in online mode?
Yes
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/MbNKtk5yb2/

**Comment by creatorfromhell** [comment]
Tested this and it works as is without the Mobs module, so simply remove Mobs.jar from plugins/TheNewEconomy/modules until the rewrite of it is out.

**Comment by ChaseIzKing** [comment]
I removed the jarfile, and pigmen still drop gold nuggets. Everything else works fine, but the drops do not work correctly.

**Comment by ChaseIzKing** [comment]
https://pastebin.com/yWLVTSJv
^ config file

**Comment by creatorfromhell** [comment]
Did you restart the server after removing the jar file?

**Comment by ChaseIzKing** [comment]
Yes. I have several plugins on my server, but none of them modify anything with mobs. If you have tested version 0.1.1.8e and it works for you, it may be a plugin conflict.

**Comment by creatorfromhell** [comment]
Test the latest beta build from the discord to resolve this.
