### ISSUE TITLE
Issue with item currencies

### ISSUE THREAD

**Issue by thanasishadow** [TheNewEconomy/TNE-Bukkit#317]
#### What is the issue/bug you're experiencing?
When ModelData is set to 0, only items with that model data count as currency instead of items with any modeldata. For example, I am using gold ingots as currency and I want gold ingots to count as currency regardless of any nbt. Golden ingots obtained the vanilla way do not count as currency but the ones I get from the /tne menu command do count and have an nbt (CustomModelData: 0) and they do count as currency.

I am no expert but I think the plugin just makes the currency items require a modeldata nbt even though it is set to 0.
#### How can the issue be reproduced?
Create an item currency.
#### TNE version?
0.1.1.8j (Latest as of 20/7/2019)
Unmodified
#### TNE build?
0.1.1.8j (Latest as of 20/7/2019)
Unmodified
#### Modules Loaded?
All of the defaults which came with that version.
#### Spigot/Bukkit version?
The /version command gives me this
CraftBukkit version git-Spigot-5e4e7f3-2349feb (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
#### Is your server run in online mode?
Yes
#### config.yml
[config.yml](https://paste.ubuntu.com/p/2cCJf38bFq/) [currency.yml](https://paste.ubuntu.com/p/SNxnSqkx38/)
#### Your latest server log file?
https://paste.ubuntu.com/p/BPwVSw5tDH/

**Comment by creatorfromhell** [comment]
I'll have a look at this tomorrow after work.

**Comment by creatorfromhell** [comment]
I have fixed, and tested this with the following jar. https://file.io/29IwZU

**Comment by thanasishadow** [comment]
This link gives me a 404 error

**Comment by creatorfromhell** [comment]
https://www.dropbox.com/s/o99ycxlgm2e4dhe/TNE.jar?dl=0

**Comment by thanasishadow** [comment]
Alright, thank you. It works perfectly!

**Comment by creatorfromhell** [comment]
Cheers
