### ISSUE TITLE
Using MySQL database unloads plugin

### ISSUE THREAD

**Issue by Auntex** [TheNewEconomy/TNE-Bukkit#320]
**ISSUE I AM EXPERIENCING:** Plugin not Loading when using MySQL database.

**HOW TO REPRODUCE IT:** Use MySQL database, on startup it appears error when trying to connect to the database (Btw: using the same information of other plugins using mysql, works perfectly, just here's the problem)

**TNE Version:** 0.1.1.8

**Modules Loaded:** Conversion, not modified.

**Spigot/Bukkit version:**  Using Paper 1.8, latest. (1.8.8-R0.1-SNAPSHOT)

**Server Online/Offline mode:** Using Offline mode on the server.

**config.yml:** https://paste.ubuntu.com/p/Sj9wzjHDcb/

**Latest log:** https://paste.ubuntu.com/p/KfWFYxNmR8/

**Comment by creatorfromhell** [comment]
From what I've researched into this issue, it seems like an incompatibility between the MySQL connector used in paper 1.8.8 and the MySQL version you're using due to the character set TNE utilizes.

**Comment by Auntex** [comment]
Ugh, I understand.. Is there any way to fix this? I mean, if this can be solved by doing some thing with the 1.8.8 MySQL connector  or I only can downgrade the MySQL to make it work?

**Comment by creatorfromhell** [comment]
> Ugh, I understand.. Is there any way to fix this? I mean, if this can be solved by doing some thing with the 1.8.8 MySQL connector or I only can downgrade the MySQL to make it work?

I'll have a look at it, but I don't think there'll be much I could do for it.
