### ISSUE TITLE
Unable to unload modules

### ISSUE THREAD

**Issue by AryToNeX** [TheNewEconomy/TNE-Bukkit#321]
#### What is the issue/bug you're experiencing?
I am unable to unload a module from the Console
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
From the console, do "tnem unload Signs"
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.8L
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta118L
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
- Signs 0.1.0
- Mobs 0.1.0
- Discord 0.1.0
- Conversion 0.1.1
#### Spigot/Bukkit version?
PaperSpigot 1.14.4 build number 156
#### Is your server run in online mode?
Nope.
#### The exact command you ran w/ arguments?
tnem unload Signs
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/y9bWJXdYFR/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/9btv4xwQ3V/

**Comment by creatorfromhell** [comment]
The module system is undergoing a revamp, and this issue is no longer an issue.
