### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ziemniok99** [TheNewEconomy/TNE-Bukkit#323]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What is the issue/bug you're experiencing?
Error in console
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Start and stop server
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.8L No modifications
#### TNE build?(/tne build), and whether or not you've made modification to it.
When I type this command it sais it doesn't exist.
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
1
#### Spigot/Bukkit version?
Spigot 1.14.4
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
None
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
Config: https://pastebin.com/auyL7eQe
Messages: https://pastebin.com/1N0FYqRh
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/nTX3HWVyXf/

**Comment by ziemniok99** [comment]
[TheNewEconomy.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/3481899/TheNewEconomy.zip)
Here you have all my plugins files to reproduce it

**Comment by creatorfromhell** [comment]
http://prntscr.com/oq7zlx

Still nothing to reproduce. IT could be an issue of your file line break type not being consistent. This is changeable in notepad++, or any respectable file editing program.

**Comment by ziemniok99** [comment]
Weird

How I do that in notepad++

**Comment by creatorfromhell** [comment]
Right click on file line break type at the bottom of the notepad++ http://prntscr.com/oq9qjz

**Comment by ziemniok99** [comment]
When I did it it is not working either. Messages after start stays in the Unix, but config after start is going back to windows

**Comment by creatorfromhell** [comment]
This is as far as I am able to provide assistance, the issue is not able to be reproduced by myself.
