### ISSUE TITLE
Update Mess

### ISSUE THREAD

**Issue by EnderGamingFilms** [TheNewEconomy/TNE-Bukkit#334]
#### What is the issue/bug you're experiencing?
Console "errors" and no /tne commands can be run.
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
All I did was update to the lastest version.
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.8
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta118L
#### Modules Loaded?(exact version number), and whether or not you've made modification to it. 
Signs
#### Spigot/Bukkit version?
Paper-148 1.14.4
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
/tne
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/xdB8Rsvf
#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/vEfLy1ZC

**Comment by creatorfromhell** [comment]
Closing in favor of https://github.com/TheNewEconomy/TNE-Bukkit/issues/335
