### ISSUE TITLE
GrammarException in config.yml on line 157

### ISSUE THREAD

**Issue by Bloodrayne1995** [TheNewEconomy/TNE-Bukkit#336]
#### What is the issue/bug you're experiencing?
On Startup I got a GrammarException in config.yml.
Full error message: _com.hellyard.cuttlefish.exception.GrammarException: Invalid grammar definition at line 157: :

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Not sure if it can be reproduced. I just started the server with a modified config.yml and on the next run I started with the default config (generated from plugin). Both leads to this error message.

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.8. Not sure which version directly. Acording to the date it shall be Beta 1.1.8L (H2 & Baltop fixes)

#### TNE build?(/tne build), and whether or not you've made modification to it.
Cannot run this command, cause TNE disables with this error

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.

- Conversion
- Discord
- Mobs
- Signs
#### Spigot/Bukkit version?
Paper-175
#### Is your server run in online mode?
Not directly. Its behind a bungeecoord with activated online mode
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/bNCxVf47yQ/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/hQWwNS3jfS/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
We use advanced currencies: https://paste.ubuntu.com/p/hwWbmrmsyx/

**Comment by creatorfromhell** [comment]
The issue is in your currency.yml file at line 157
