### ISSUE TITLE
More placeholders

### ISSUE THREAD

**Issue by ziemniok99** [TheNewEconomy/TNE-Bukkit#341]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What feature are you suggesting be added?
More placeholders
#### Expected use-case for said feature?
Placeholders for:
- last transitions
- top list
- shops owned
- etc
#### Why should this feature be added to TNE?
It would be very useful for using them in other plugins.

**Comment by creatorfromhell** [comment]
I'll most likely add the top list one based on what I believe to be ample functionality for it. The others I'm not entirely convinced on adding.
