### ISSUE TITLE
Invalid permssion

### ISSUE THREAD

**Issue by Reiikz** [TheNewEconomy/TNE-Bukkit#342]
Permission invalid message when trying to create a sign
you can reproduce this by putting the permission wrhongly like it says on the wiki (tne.sign.item insted of what is written in the code tne.item.sign).
TNE Version 0.1.1.8
TNE Build 1Beta118L
TNE Modules Conversion, Signs.
Spigot: git-Spigot-9de398a-9c887d4 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Online mode: false
java -Xmx9G -jar
![Sin nombre](https://user-images.githubusercontent.com/23635530/64481182-19912200-d1ad-11e9-885c-826d49e0ed5e.png)
Guys in the future, remember to update the wiki to not make people like me dig through the code to know what is going on :)

**Comment by creatorfromhell** [comment]
The permission nodes above are 2 separate ones. The one on the left is to create the sign itself, the one on the right is to offer certain items.

**Comment by creatorfromhell** [comment]
This is outlined here http://prntscr.com/p37sif so you don't have to dig through the source.

**Comment by Reiikz** [comment]
me stupid, sorry, problem is not reading with attention, in mi defense I think it could be more clear, anyway still my fault, sorry for wasting your time :c

**Comment by creatorfromhell** [comment]
No worries.
