### ISSUE TITLE
/tne backup not working

### ISSUE THREAD

**Issue by ziemniok99** [TheNewEconomy/TNE-Bukkit#345]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What is the issue/bug you're experiencing?
When I do /tne backup it shows this 
![image](https://user-images.githubusercontent.com/43730820/64914746-b9275500-d757-11e9-8009-c732706510df.png)

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
/tne backup
#### TNE version?(exact version number), and whether or not you've made mBodification to it.
0.1.1.8M4
#### TNE build?(/tne build), and whether or not you've made modification to it.
4Beta118M No i didn't
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Converion (not nececasery version), no didn't
#### Spigot/Bukkit version?
Spigot 1.14.4
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
/tne backup
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/scdnYHUy
#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/9wPDdfRC
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
...

**Comment by creatorfromhell** [comment]
tne backup is getting removed. This bug report is not valid. Use /tne extract instead.
