### ISSUE TITLE
Please add a command to extract to file

### ISSUE THREAD

**Issue by ziemniok99** [TheNewEconomy/TNE-Bukkit#346]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What feature are you suggesting be added?
A command to extarct to a file
#### Expected use-case for said feature?
Automatic backups
#### Why should this feature be added to TNE?
It would be useful for players

**Comment by KarlOfDuty** [comment]
Have you tried /tne extract?

**Comment by creatorfromhell** [comment]
This is already a feature as outlined in the documentation.
