### ISSUE TITLE
multiple  currencies 

### ISSUE THREAD

**Issue by hmmcrunchy** [TheNewEconomy/TNE-Bukkit#352]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What is the issue/bug you're experiencing?
error when using command after adding custom currencies, also featherboard shows <money_rounded> in placeholder

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
type /money or bal etc
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9
#### TNE build?(/tne build), and whether or not you've made modification to it.
1beta119
#### Spigot/Bukkit version?
1.14.4
#### Is your server run in online mode?
no but through bungeecord
#### The exact command you ran w/ arguments?
/money
#### Your latest server log file?(use http://paste.ubuntu.com)
`[18:49:58] [Server thread/INFO]: hmmcrunchy issued server command: /money
[18:49:58] [Craft Scheduler Thread - 22/WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 2491
java.lang.NullPointerException: null
        at net.tnemc.core.commands.money.MoneyBalanceCommand.lambda$execute$1(MoneyBalanceCommand.java:90) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_201]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]`
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

whole zip of TNE folder here 
http://byte.byte-drive.co.uk/

**Comment by hmmcrunchy** [comment]
Hey there, basically I have tried setting up a couple of custom currencies here for our starwars server. I may have this wrong ive included a zip of all the TNE stuff so you can see what ive messed up probably. 

thanks :)

**Comment by creatorfromhell** [comment]
Please include your latest.log as outlined in the bug report format

**Comment by creatorfromhell** [comment]
Also
`Scheduler Thread - 22/WARN]: [TheNewEconomy] Plugin TheNewEconomy v0.1.1.9 generated an exception while executing task 2491 java.lang.NullPointerException: null at net.tnemc.core.commands.money.MoneyBalanceCommand.lambda$execute$1(MoneyBalanceCommand.java:90) ~[?:?] at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-94af569-a3fdef8] at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-94af569-a3fdef8] at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_201] at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_201] at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]`

Is not a complete error, the complete error is located inside your server log.

**Comment by hmmcrunchy** [comment]
Ah sorry I’ll get that over ASAP

**Comment by ziemniok99** [comment]
Hi, I have same issue here, same report arguments (same version etc.) and here is my logs (I don not see any error at all) https://pastebin.com/k2Hh89X8

**Comment by creatorfromhell** [comment]
Closing as the ticket has remained incomplete for over 2 days.
