### ISSUE TITLE
starting balance not working with mysql

### ISSUE THREAD

**Issue by Rmarmorstein** [TheNewEconomy/TNE-Bukkit#354]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What is the issue/bug you're experiencing? 
Starting balances are not working
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Install TNE, connect to MySQL, join server and /balance 
#### TNE version?(exact version number), and whether or not you've made modification to it.
No modifications; 0.1.1.9
#### TNE build?(/tne build), and whether or not you've made modification to it.
1beta119
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No modules loaded
#### Spigot/Bukkit version?
paperspigot 1.14 (git-paper-194)
#### Is your server run in online mode?
No, behind online bungeecord proxy
#### The exact command you ran w/ arguments?
/money balance
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/raw/jgAiHPFW
#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/raw/PjBwYVBB
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
none

**Comment by ziemniok99** [comment]
I have the same problem... But I am not using mysql
