### ISSUE TITLE
Feature-Request: Allowing / Defining usage of your logos

### ISSUE THREAD

**Issue by Bloodrayne1995** [TheNewEconomy/TNE-Bukkit#356]
#### What feature are you suggesting be added?
Defining the usage of your logos.

#### Expected use-case for said feature?
For Content-Creator or someone who wants to present this wonderful plugin.

#### Why should this feature be added to TNE?
Its not really a feature for within TNE but a ruleset for using your images on platforms
like YT, Twitch and so on.

#### Why I suggest this?
I'm currently working on a presentation for our server update. Within this update we switch 
from iConomy to TNE and I want to present some features of TNE in this presentation.
I think it would be nice to add your logo on this presentation.

Greetings
EONA Bloodrayne

**Comment by creatorfromhell** [comment]
From the start, usage of the TNE logo is allowed in videos that are meant for tutorials or to showcase the plugin. If you believe youll need special access beyond this let me know

**Comment by Bloodrayne1995** [comment]
I need it to present the changes in our economy system with the new economy plugin.
I do not show some commands or make a tutorial for configuration.

is this allowed?

**Comment by creatorfromhell** [comment]
That is fine.

**Comment by Bloodrayne1995** [comment]
Ok thank you. I close this issue now.
