### ISSUE TITLE
Error on Server Reboot: Unable to contact update server

### ISSUE THREAD

**Issue by oranges13** [TheNewEconomy/TNE-Bukkit#360]
#### What is the issue/bug you're experiencing?
When our server restarts, it hangs when starting TNE. We have disabled Update: check and notify in our config.yml but it still attempts to check for updates and stalls the reboot process.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Reboot server, it will hang at the TNE enabling as it is checking for an update and takes 4 minutes to time out.

#### TNE version?(exact version number), and whether or not you've made modification to it.
1.1.7

#### TNE build?(/tne build), and whether or not you've made modification to it.
You're currently running TNE build 3Beta115

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.

`22.10 04:03:54 [Server] INFO Found module: MySQL version: 0.1.1
22.10 04:03:54 [Server] INFO Found module: H2 version: 0.1.1
22.10 04:03:54 [Server] INFO Found module: Mobs version: 0.1.0
22.10 04:03:54 [Server] INFO Found module: Conversion version: 0.1.0
22.10 04:03:54 [Server] INFO MySQL Module loaded!
22.10 04:03:54 [Server] INFO Mobs Module loaded!
22.10 04:03:54 [Server] INFO H2 Module loaded!
22.10 04:03:54 [Server] INFO Conversion Module loaded!`

#### Spigot/Bukkit version?
1.13

#### Is your server run in online mode?
Yes

#### The exact command you ran w/ arguments?
No TNE command, we just were trying to reboot our server.

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/ZJJS5sFqx8/

#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/KzbQvMPfjx/ (Line 627 - 628, you can see that it took FOUR MINUTES for the update request to time out)

We want to be able to DISABLE update checking because it's seriously interfering with our server restart process.

**Comment by creatorfromhell** [comment]
Your tne is very out of date, this issue was patched already.

**Comment by oranges13** [comment]
Thank you for the update. Can you let me know which most recent version will still run on 1.13? Thank you.

**Comment by creatorfromhell** [comment]
All tne versions will run on 1.13

**Comment by oranges13** [comment]
Is there a Stable version? I'm guessing they downloaded 1.1.7 because they don't want to download Beta / Alpha builds.

**Comment by creatorfromhell** [comment]
All tne builds are beta builda 1.1.7 includes
