### ISSUE TITLE
Error/spam in the console whenever a player joins

### ISSUE THREAD

**Issue by thanasishadow** [TheNewEconomy/TNE-Bukkit#363]
#### What is the issue/bug you're experiencing?
Error/spam in the console whenever a player joins (see logs).
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Here is everything in my TNE config folder: https://www.mediafire.com/file/94h6k0no4v0xzgv/TNE_config.zip/file
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9, unmodified
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119, unmodifiied.
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
All modules, unmodified.
#### Spigot/Bukkit version?
git-Paper-226 (MC: 1.14.4)
#### Is your server run in online mode?
Yes.
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/GVjNWTF6Q7/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/VQcTwjw7fZ/

**Comment by creatorfromhell** [comment]
What is the balance of the account that is attempting to join?

**Comment by thanasishadow** [comment]
0

**Comment by creatorfromhell** [comment]
[TNE-1.1.9.2.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/3934215/TNE-1.1.9.2.zip)
try this build, I'm not currently getting this error when testing.
