### ISSUE TITLE
TNE breaks FactionsUUID

### ISSUE THREAD

**Issue by elwolf6** [TheNewEconomy/TNE-Bukkit#365]
Report Format
=====================
Please Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

#### What is the issue/bug you're experiencing?
TNE breaks FactionsUUID's dynmap-integration whenever you enable economy in FactionsUUID

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
1. Install FactionsUUID, Dynmap, and Towny
2. Enable economy in FactionsUUID config
3. Watch the console burn
#### TNE version?(exact version number), and whether or not you've made modification to it.
TNE-1.1.9.2 no moditifaction
#### TNE build?(/tne build), and whether or not you've made modification to it.
https://elwolf6.feen.us/x1benh.png
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Mobs-0.1.3.0 no modification

#### Spigot/Bukkit version?
Paper 1.15 1
#### Is your server run in online mode?
yes
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/JngJFN5xwB/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/mhQHs8WvSg/

**Comment by creatorfromhell** [comment]
This is caused by you not having vault.

**Comment by elwolf6** [comment]
bro i had vault installed
i tried it with vault and w/o reserver
and i tried w/ reserve and w/o vault

**Comment by creatorfromhell** [comment]
This issue is closed because the error is a factions uuid issue please read your error log before posting a ticket here.
