### ISSUE TITLE
Error occurred while enabling TheNewEconomy

### ISSUE THREAD

**Issue by splintermik** [TheNewEconomy/TNE-Bukkit#367]
Report Format
=====================

#### What is the issue/bug you're experiencing?
Error occurred while enabling TheNewEconomy
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
latest plugin version + Paper-31 (MC: 1.15.1)
#### TNE version?(exact version number), and whether or not you've made modification to it.
The New Economy 0.1.1.9a ( https://www.spigotmc.org/resources/the-new-economy.7805/download?version=304603 ) no modification
#### TNE build?(/tne build), and whether or not you've made modification to it.
/tne build don't work ( 
15:24:46] [Server thread/INFO]: splintermik issued server command: /tne build
[15:24:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'tne' in plugin TheNewEconomy v0.1.1.9 - plugin is disabled.
)
#### Spigot/Bukkit version?
Paper-31 (MC: 1.15.1)
#### Is your server run in online mode?
offline mode
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/LS8uHrS8
#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/xw0jhhS4

Hello

I wanted to test version 1.15.1 for the server, and I encountered a problem with the plugin when I launched the server. 
I'm on the latest version of paperspigot and TNE.
i use java 11

thank you

**Comment by creatorfromhell** [comment]
The server log entry is for the full server log.

**Comment by splintermik** [comment]
here's the log file https://pastebin.com/a6m3R63k
