### ISSUE TITLE
In-Game MC Variables (@p, @a, etc.) are creating MC Variable users, not resolving to a player name.

### ISSUE THREAD

**Issue by ctkoakenleaf** [TheNewEconomy/TNE-Bukkit#368]
#### What is the issue/bug you're experiencing?
When useing commands with @p, TNE creates a user '@p' with a UUID instead of the expected behavior of resolving @p to a Username

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
I ran these commands in minecraft on the chat line.
command `/tne id <Your Username>`
command `/tne id @p`
   UUIDs were different and not the expected match

#### TNE version?(exact version number), and whether or not you've made modification to it.
1.1.9.2, No

#### TNE build?(/tne build), and whether or not you've made modification to it.
2Beta119

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
None

#### Spigot/Bukkit version?
git-Paper-237 (MC: 1.14.4)

#### Is your server run in online mode?
Yes

#### The exact command you ran w/ arguments?
See above

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/FWwrFxhdXg/

#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/CgrRrwzycs/

**Comment by creatorfromhell** [comment]
This has been added to the commands library, and will be in the next TNE release.
