### ISSUE TITLE
Towny Daily Taxes Bug

### ISSUE THREAD

**Issue by JohnS19** [TheNewEconomy/TNE-Bukkit#372]
What is the issue/bug you're experiencing?
Towns/Nations randomly being disbanded even with proper balance in their accounts during the daily taxes.

How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Not completely sure, but it seems to be at random right now.

TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9

TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119

Modules Loaded?(exact version number), and whether or not you've made modification to it.
0

Spigot/Bukkit version?
Paper 226

Is your server run in online mode?
No

The exact command you ran w/ arguments?
N/A

config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/28Bkzq6m7C/

Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/7vdZcffpZg/

**Comment by creatorfromhell** [comment]
Have you tried the latest release? Youre on 0.1.1.9 and there id 0.1.1.9b

**Comment by JohnS19** [comment]
No, I will try it out soon, I assumed it wouldn't make much of a difference considering the changes listed weren't really that large or seemed impactful on the situation being caused.

**Comment by JohnS19** [comment]
Still occurring
