### ISSUE TITLE
Chestshop Bug

### ISSUE THREAD

**Issue by MOHMOBILE** [TheNewEconomy/TNE-Bukkit#373]
Hey!
1. I have this weird issue that my players are not getting any money from Chestshops... I already asked the Chestshop community, but they say, that I should ask the economy plugin provider.
Can you help me? I think it's some kind of a bug.

2. You can reproduce this bug, if you install Chestshop, Vault and TNE on a Paper 1.14.4 Server and sell an Item.

3. Version: 1.1.9.2

4. 1Beta119b

5.No Modules are installed.

6. Paper Version 1.14.4, build 237

7. The server is in offline mode, bungeecord is set to "true" in the spigot.yml

8. I just sold an Item (no command)

9. https://paste.ubuntu.com/p/kJmt2zPgF8/

10. https://paste.ubuntu.com/p/TZ4HhyKbZw/

Best regards,
MOHMOBILE

**Comment by creatorfromhell** [comment]
Unable to reproduce as discussed on the discord, reopen after confirming this is a TNE issue.
