### ISSUE TITLE
Conflict with Taboolib

### ISSUE THREAD

**Issue by himekifee** [TheNewEconomy/TNE-Bukkit#374]
THE failed to launch during startup.I tested and it seems like to be conflicting with Wayback plugin
Specifically, conflict with taboolib which is the library the Wayback plugins uses. The [bug report].(https://pastebin.com/pMfEaZ48)
The [plugin repo](https://github.com/IzzelAliz/Wayback).
Version is 1.1.9.2b
Offline mode

**Comment by creatorfromhell** [comment]
Fixed for next release. http://prntscr.com/qwj409
