### ISSUE TITLE
Errors when starting for the second time

### ISSUE THREAD

**Issue by C4BR3R4** [TheNewEconomy/TNE-Bukkit#377]
When the server is loaded a second time, the following errors appear https://pastebin.com/LV7aycEn
and these in debug mode https://pastebin.com/u9LxAraV

When this happens a new file is generated called "Economy.trace.db"

PD: Without changing any of the default settings

_Using: Spigot 1.15.1 | TNE 1.1.9.2 | Vault 1.7.2_

**Comment by creatorfromhell** [comment]
Incorrect reporting format.
