### ISSUE TITLE
Could not pass event EntityDeathEvent to MobHunting v6.9.9

### ISSUE THREAD

**Issue by hashashin** [TheNewEconomy/TNE-Bukkit#378]
#### What is the issue/bug you're experiencing?
This happens when a citizen sentinel of type player npc, damages a mob, "drop_money_on_ground" it's set to "false" in MobHunting, one real player does the killing blow and you're using TheNewEconomy plugin. I can't reproduce it with EssentialsX eco for example.
So not sure where to report this. Also reported in Rocologo/MobHunting#602
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
* Min plugins to reproduce:
    -Citizens-2.0.26-b1815
    -Sentinel-2.0.1-SNAPSHOT-b336
    -TNE-1.1.9.2
    -Vault 1.7.3
    -MobHunting-6.9.9
    All in default config but the "drop_money_on_ground" set to false in MobHunting.
* Steps:
    -create a sentinel npc ex: /npc create dude --trait sentinel
    -add monsters target: /sentinel addtarget monsters
    -spawn a monster mob
    -wait for the npc to damage it
    -kill the mob as player

#### TNE version?(exact version number), and whether or not you've made modification to it.
TNE-1.1.9.2
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119b
#### Spigot/Bukkit version?
git-Paper-77 MC-1.15.2
#### Is your server run in online mode?
Yes.
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
default
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/ZnywNMh6f5/

**Comment by creatorfromhell** [comment]
Does it only happen after an NPC has damaged it first? If so is there a functionality in MobHunting that splits the drop between all damagers?

**Comment by hashashin** [comment]
> 
> 
> Does it only happen after an NPC has damaged it first? 

Yes, only happens if the NPC does damage and then a player does the killing hit. 
>
>
> If so is there a functionality in MobHunting that splits the drop between all damagers?

I think so.

**Comment by creatorfromhell** [comment]
Enable tne debug mode then turn the server back on and post the server log with the debug lines.

**Comment by hashashin** [comment]
https://paste.ubuntu.com/p/H7DDkBv73c/

**Comment by creatorfromhell** [comment]
Somewhere along the line the username is being passed as null. http://prntscr.com/quvoa2 I'm not familiar with MobHunting enough to know, but I would like to see what it's passing to TNE through vault if it has a debug mode, again I'm not sure.

**Comment by hashashin** [comment]
Debug was already enabled on MobHunting and Vault has no debug afaik. I think MobHunting should check if the "player" it's a npc so it's his fault, maybe? 
Citizens uses metadata to tag the fake players with "NPC", so should be easy to check.

Perhaps this can be closed until @Rocologo steps in the other issue.

Thanks anyway :)

**Comment by creatorfromhell** [comment]
Cheers, no worries.
