### ISSUE TITLE
TNE not working

### ISSUE THREAD

**Issue by unicorngas** [TheNewEconomy/TNE-Bukkit#380]
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Typing any TNE command in.

#### TNE version?(exact version number), and whether or not you've made modification to it.
No modifications, TNE-1.1.9.2

#### TNE build?(/tne build), and whether or not you've made modification to it.
TNE build 1Beta119b no modifications

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No modules loaded

#### The exact command you ran w/ arguments?
/money balance
/money give LearningLAB 5

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/LszWEH2D

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/dkbnGYWDBr/

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment]
so after reading your currency configurations
you don't have a default global currency
so what's happening is it's looking for the default currency in the world, but it can't because it doesn't have one nor is there a global one
http://prntscr.com/qucxzf
