### ISSUE TITLE
Errors when starting TNE 1.1.9.2

### ISSUE THREAD

**Issue by C4BR3R4** [TheNewEconomy/TNE-Bukkit#385]
#### What is the issue/bug you're experiencing?
The plugin does not start

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
When you start the server a second time

#### TNE version?(exact version number), and whether or not you've made modification to it.
1.1.9.2

#### TNE build?(/tne build), and whether or not you've made modification to it.
 0.1.1.9b 6c58b48

#### Spigot/Bukkit version?
1.15.1-R0.1-SNAPSHOT #2574
#### Is your server run in online mode?
Yes
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/qvhLQ0UJ

#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/LV7aycEn

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
https://pastebin.com/u9LxAraV

**Comment by creatorfromhell** [comment]
Mysql version?
And mysql or mariadb?

**Comment by creatorfromhell** [comment]
No response. Closing.
