### ISSUE TITLE
Issue with Towny

### ISSUE THREAD

**Issue by slvlr** [TheNewEconomy/TNE-Bukkit#386]
I am using new jar you sent me, players balances have come through but towns are still $0. I have typed /tne restore. It didn't put any output in server and didn't restore the towns balances. Advise please?
Restoration actually stops at 99 in the console and didn't say anything in chat at all so not sure if its done.

Conversion also stopped at 99 in console but did give me a complete notice in chat.
Also I still get the internal error if i type.. what does /tne bal town-sixto
Does this mean it should be done? : https://gyazo.com/eba913d7651f97ab322f3d18754d28ef
Gyazo
Gyazo

Rangewonk / SlVlRYesterday at 18:15
I also changed all nation% and town% to nation@ and town@ but I have noticed that some things still have % like this:

  EXP%Theodor:
    Balances:
      towny:
        Dollar: '325.6339'
  Typical%wierdo:
    Balances:
      towny:
        Dollar: '965.83'
Do you know what this is please?

I started from scratch by deleting the database and extracted file.
It still doesn't work for towny balances with the new jar you sent me??

**Comment by creatorfromhell** [comment]
Invalid format. See discord responses.
