### ISSUE TITLE
Towns 0 Balance

### ISSUE THREAD

**Issue by slvlr** [TheNewEconomy/TNE-Bukkit#388]
Hello,
I have tried to fill out the template the best I can.
I hope this helps you help me.
Thank you.

### What is the issue/bug you're experiencing?
After converting from EssentialsECO, Players balances are restored however towns have $0 Balance.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
1) /Convert Essentials
2) /Tne Restore

#### TNE version?(exact version number), and whether or not you've made modification to it.
TNE-1.1.9.2 (pre-release sent via discord).

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Conversion-0.0.1.4.jar

#### Spigot/Bukkit version?
Paper 1.15.2 (build 90+)

#### Is your server run in online mode?
Yes online only

#### The exact command you ran w/ arguments?
/Convert Essentials
/Tne Restore
/bal <player> (showed correct balances)
/t <townname> (showed 0 balance)
/tne bal town-sixto (returns internal error)

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/2rwTBFPF6D/

#### Your latest server log file?(use http://paste.ubuntu.com)
N/A as I have not got the log when TNE was installed.

#### Towns affected by this issue? And whether or not they've been renamed recently.
All Towns, Renamed or not.

#### Nations affected by this issue? And whether or not they've been renamed recently.
All Nations, Renamed or not.

**Comment by creatorfromhell** [comment]
Where is the server log?

**Comment by slvlr** [comment]
@creatorfromhell You know the issues. You were able to reproduce it on your test server. Why do you need all this info from me when you know whats wrong. Just being a pain on purpose.
