### ISSUE TITLE
Players starting with 0 balance

### ISSUE THREAD

**Issue by introvertism** [TheNewEconomy/TNE-Bukkit#389]
#### What is the issue/bug you're experiencing?
Players are starting with a balance of 0
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Use TNE, set the starting balance to anything, have a new player join and their balance will be 0
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119b
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Conversion 0.0.1.4 but havent used it in a while
#### Spigot/Bukkit version?
Paper-89 1.15.2
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
N/A?
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/pQYW26Csfj/
#### Your latest server log file?(use http://paste.ubuntu.com)
N/A?  https://paste.ubuntu.com/p/mQ4qMX5zPq/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
N/A

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment]
Tested this on paper 1.15.2 with tne, towny and Reserve, and players are correctly starting with the set starting balance

**Comment by introvertism** [comment]
Dunno if it makes a difference but I'm using Vault. I'll try reproducing it on a fresh setup later tonight when I have time.

**Comment by creatorfromhell** [comment]
It doesn't matter, Reserve/Vault are only what's used for external plugins to talk to economy plugins.

**Comment by creatorfromhell** [comment]
No response in 6 days
