### ISSUE TITLE
Could not pass event PlayerInteractEvent to TheNewEconomy v0.1.1.9

### ISSUE THREAD

**Issue by elwolf6** [TheNewEconomy/TNE-Bukkit#390]
#### What is the issue/bug you're experiencing?
Nothing noticable but an error in the console
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Idk, it started happening after i switched from Java 11 to Java 8
#### TNE version?(exact version number), and whether or not you've made modification to it.
TNE version 0.1.1.9 no mods
#### TNE build?(/tne build), and whether or not you've made modification to it.
TNE build 1Beta119b no mods
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Mobs-0.1.3.0 no mods
Signs-0.0.1.3 no mods
#### Spigot/Bukkit version?
Paper #107 
#### Is your server run in online mode?
Bungee Online mode (with waterfall)
#### The exact command you ran w/ arguments?
i didn't run any
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/gDVrXbJDTc/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/hGAH59JK
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

I have TNE, Town, and Towny-TNE (main plugins, there are others but these are main ones)

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by elwolf6** [comment]
idk why it hyperlinked #107  to issue 107 just ignore that

**Comment by obj-obj** [comment]
I am now randomly having this issue but on Java 11 instead of Java 8, and I can confirm it was the Signs module because it stopped after I disabled it

**Comment by creatorfromhell** [comment]
> I am now randomly having this issue but on Java 11 instead of Java 8, and I can confirm it was the Signs module because it stopped after I disabled it

Gotcha
