### ISSUE TITLE
Checking Players Balance.

### ISSUE THREAD

**Issue by Grandof1** [TheNewEconomy/TNE-Bukkit#392]
**What is the issue/bug you're experiencing?**
When using the alias for ```/tne bal <username>``` command, it does not show the balance of said player and results in an error in console. When using the parent command ```/tne bal <username>``` it works fine with out any error messages to the console and displays the corresponding balance of said player.

**How can the issue be reproduced?(i.e. the steps to make the issue occur again)**
Type ```/bal <username>``` for yourself or even for other players causes the error.

**TNE version?(exact version number), and whether or not you've made modification to it.**
```TNE-0.1.1.9.2b``` but shows up in game as ```0.1.1.9``` with zero modifications.

**TNE build?(/tne build), and whether or not you've made modification to it.**
```1Beta119b```

**Modules Loaded?(exact version number), and whether or not you've made modification to it.**
- Mobs.jar (not sure where to check version number) ```1.12``` I think?
- Signs-0.0.1.3.jar

**Spigot/Bukkit version?**
No longer using spigot, moved to Papermc version ```paper-93``` and have tested on ```paper-121```.

**Is your server run in online mode?**
Yes

**The exact command you ran w/ arguments?**
```/bal <username>```
E.g ```/bal grandof```

**config.yml?**
https://hastebin.com/seceruneba.bash

**Your latest server log file?**
https://hastebin.com/cuderuqete.md

**If this is to do with messages/world/player configurations, please include the YAML file for such.**
No it does not have anything to do with those config files.

**Comment by creatorfromhell** [comment]
/bal <username> is not a command, use /tne balance.

**Comment by Grandof1** [comment]
In the paste it acted as an alias for ```/tne bal <username>``` and would show the balance of said player as well as not send a error message.
