### ISSUE TITLE
Inconsistent Version Number/Build

### ISSUE THREAD

**Issue by thewarden** [TheNewEconomy/TNE-Bukkit#394]
#### What is the issue/bug you're experiencing?
The version number and build within plugin.yml, https://www.spigotmc.org/resources/the-new-economy.7805/history, https://github.com/TheNewEconomy/TNE-Bukkit/releases, /tne version, /tne build is inconsistent. The filename is missing the build number. 

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Compare the version entered in the plugin.yml under the property "version" vs. the version number stated on the release pages or in-game type /tne version and /tne build.

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9

#### TNE build?(/tne build), and whether or not you've made modification to it.
2beta119

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
- Mobs.jar (not clearly stated anywhere the version it's assumed v0.1.1.8 or Mobs-0.0.1.0.jar)
- Signs-0.0.1.3.jar

#### Spigot/Bukkit version?
Using both...
- PaperMC #118
- Spigot CraftBukkit version git-Spigot-8faa8b4-3d61a85 (MC: 1.15.2)

#### Is your server run in online mode?
Yes

#### The exact command you ran w/ arguments?
Not applicable in part of the context otherwise /tne version and /tne build.

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
n/a

#### Your latest server log file?(use http://paste.ubuntu.com)
n/a

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

n/a

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without notice.

**Comment by creatorfromhell** [comment]
TNE uses a alpha character after the version to dictate minor releases, or bug fix releases for major versions. I have no intention of updating the plugin.yml to include a alpha character. This is why the build number is also present. While not used as a build number in its truest form, TNE build numbers are treated as revision numbers.

**Comment by thewarden** [comment]
> TNE uses a alpha character after the version to dictate bug fix releases for major versions. I have no intention of updating the plugin.yml to include a alpha character. This is why the build number is also present. While not used as a build number in its truest form, TNE build numbers are treated as revision numbers.

Well I understand that however I do not understand how this is not inconsistent and clear to the user dealing with the software. From a perspective of an system administrator that is in charge of updating the software explain then to me how one can clearly see what version and build is installed compared to say https://github.com/TheNewEconomy/TNE-Bukkit/releases and file name of the jar?  

As you can see one place it states "Beta 1.1.9b", then tagged "0.1.1.9b", the filename is  "TNE-1.1.9.2.jar", /tne build it is version 1.1.9 2beta119 and then if you look at the plugin.yml there it "version: 1.1.9". This creates confusion by miscommunication. A software version can contain also the build at the end. There seems to be a mix of uses for build and version. Maybe you are not using semver 2 but this is extremely helpful for an administrator by looking at what is available to download vs what files are present on a system. 

I'm just trying to understand your perspective and show another perspective to help aid in better communication.

**Comment by creatorfromhell** [comment]
> > TNE uses a alpha character after the version to dictate bug fix releases for major versions. I have no intention of updating the plugin.yml to include a alpha character. This is why the build number is also present. While not used as a build number in its truest form, TNE build numbers are treated as revision numbers.
> 
> Well I understand that however I do not understand how this is not inconsistent and not clear to the user dealing with the software. From a perspective of an system administrator that is in charge of updating the software explain then to me how one can clearly see what version and build is installed compared to say https://github.com/TheNewEconomy/TNE-Bukkit/releases and file name of the jar?
> 
> As you can see one place it states "Beta 1.1.9b", then tagged "0.1.1.9b", the filename is "TNE-1.1.9.2.jar", /tne build it is version 1.1.9 2beta119 and then if you look at the plugin.yml there it "version: 1.1.9". This creates confusion by miscommunication. A software version can contain also the build at the end. There seems to be a mix of uses for build and version. Maybe you are not using Semantic Versioning 2.0.0 (semver) but this is extremely helpful for an administrator by looking at what is available to download vs what files are present on a system.
> 
> I'm just trying to understand your perspective and show another perspective to help aid in better communication.
> 
> I look forward to your response.

The .2 at the end was a mistake as the jar was pushed out quickly for bug fixes. This may be validated with other jars which usually say "TNE.jar." There is no meaning behind the name 1.1.9.2 other than I forgot to rename it when uploading.

This is mainly because a) I was more concerned about pushing out a patch and b) the file name is irrelevant when it comes to bug reporting.
