### ISSUE TITLE
MySQL - odd sizes

### ISSUE THREAD

**Issue by Kbryst** [TheNewEconomy/TNE-Bukkit#395]
Just had a question about the MySQL setup for TNE.

Lately our server has been locking up, we believe its due to our MySQL. I'm seeing that two TNE tables are easily 8x the size of everything else.

TNE charges
TNE transactions

Is there anything we can do to cut these down a bit? I didn't find any config settings for old data cleanup.

**Comment by creatorfromhell** [comment]
Currently this is not possible. There are plans to make a configuration for this but until then youll have to manually wipe the tables.
