### ISSUE TITLE
Support for EssentialsX & Repair Placeholders

### ISSUE THREAD

**Issue by tomekatomek123456789** [TheNewEconomy/TNE-Bukkit#398]
Could support for Essentials be added?
Placeholders from LuckPerms when the plugin is enabled do not work.
Sorry for English. This is not my national language.

**Comment by creatorfromhell** [comment]
What do you mean by essentialsx support? TNE is a standalone economy plugin

**Comment by creatorfromhell** [comment]
Closing. This ticket is vague and doesnt follow the correct formats

**Comment by tomekatomek123456789** [comment]
TNE duplicates server economics when Essentials is enabled.
