### ISSUE TITLE
Economics with Essentials and Groups with LuckPerms

### ISSUE THREAD

**Issue by tomekatomek123456789** [TheNewEconomy/TNE-Bukkit#399]
**What is the issue/bug you're experiencing?**
1.Economics duplication
The /money command displays the account balance from TNE, while /balance displays the account balance from Essentials
Some plugins use the economi system from Essentials.
2.Placeholders Error
Placeholders do not work properly with a large number of plugins: [Vault, LuckPerms, Essentials, etc.]

**TNE version?(exact version number), and whether or not you've made modification to it.**
0.1.1.9b

**TNE build?(/tne build), and whether or not you've made modification to it.**
I have not modify TNE.

> [13:17:50] [Server thread/INFO]: You're currently running TNE build 1Beta119b

**Spigot/Bukkit version?**

Spigot git-Spigot-cbd1a1b-009d8af (1.14.4)

**Is your server run in online mode?**

Yes

**The exact command you ran w/ arguments?**
/money 
/balance
Use placeholders from plugins I wrote earlier.

**config.yml?(use http://paste.ubuntu.com, and remove your SQL details)**

https://hatebin.com/vyqgbdtqmq

**Your latest server log file?(use http://paste.ubuntu.com)**
https://hatebin.com/iknurdtlro

Sorry for English, but this is not my national language.

**Comment by creatorfromhell** [comment]
Issue was already addressed in beta tester builds
