### ISSUE TITLE
The server name is ignored

### ISSUE THREAD

**Issue by Dok-dev** [TheNewEconomy/TNE-Bukkit#400]
#### What is the issue/bug you're experiencing?
The server name specified in the configuration file is ignored. The database still says "Main Server" instead of the actual server name.
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Specify the server name in config.yml then see what is written in MySQL.
#### TNE version?(exact version number), and whether or not you've made modification to it.
TNE Version 0.1.1.9.2.
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119b
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No Modules
#### Spigot/Bukkit version?
Spigot Paper 1.15.2-126
#### Is your server run in online mode?
No
#### config.yml
https://paste.ubuntu.com/p/tR4rR92SQx/

#### And I absolutely can't understand how to make a common player balance on two different servers and worlds.
worlds.yml https://paste.ubuntu.com/p/BtC9k3C2vs/

**Comment by creatorfromhell** [comment]
This issue was already fixed in the beta tester builds.
