### ISSUE TITLE
Server crash when using MySQL

### ISSUE THREAD

**Issue by MinecraftAdmin** [TheNewEconomy/TNE-Bukkit#402]
#### What is the issue/bug you're experiencing?
Server crash
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Install TNE
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119b
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
TNE-Signs, TNE-Mobs, Towny-TNE
#### Spigot/Bukkit version?
Paper 1.15.2
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
None
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/raw/BUvKref3
#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/raw/ttxUNiuS

**Comment by creatorfromhell** [comment]
Cant reproduce this.
