### ISSUE TITLE
STOP WORKING AFTER SERVER RESTART

### ISSUE THREAD

**Issue by Rpuxshi** [TheNewEconomy/TNE-Bukkit#403]
I´ve been using the plugin since last year and it always worked well, but last night after a server restart it started sending error after error; I deleted and re-installed the plugin, that made the job until I restarted the server again, then the errors came back. It happen every time I restart the server.
I wonder if you could have an idea about what is happening.

Here is a pastebin about it:
https://pastebin.com/Uawfe4qB

**Comment by creatorfromhell** [comment]
Follow the format. Its there for a reason.
