### ISSUE TITLE
Town/Nation balances wiped after upkeep collection

### ISSUE THREAD

**Issue by JohnS19** [TheNewEconomy/TNE-Bukkit#406]
#### What is the issue/bug you're experiencing?
Many town balances have been wiped after new day upkeep was being collected.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Not completely sure but execute a new day while having a few towns with balances.

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9b

#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
none

#### Spigot/Bukkit version?
Paper 214

#### Is your server run in online mode?
No.

#### The exact command you ran w/ arguments?
N/A (automatic new day upkeep collection)

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/YJ4BrSnG8r/

#### Your latest server log file?(use http://paste.ubuntu.com)
I have messaged you about it on discord. (too large to put on paste.ubuntu.com, keeps timing out)

#### Towns affected by this issue? And whether or not they've been renamed recently.
Multiple, not completely sure of all of the ones affected (5+) , and no, they've not been renamed recently.

#### Nations affected by this issue? And whether or not they've been renamed recently.
Multiple, not completely sure of all of the ones affected (5+) , and no, they've not been renamed recently.

https://pastebin.com/86ixrTDu

**Comment by creatorfromhell** [comment]
Attempted to recreate this, wasn't able to.
