### ISSUE TITLE
Random town balance deletion

### ISSUE THREAD

**Issue by Rishabh-Raghunath** [TheNewEconomy/TNE-Bukkit#407]
#### What is the issue/bug you're experiencing?
Town Balanced getting deleted.
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
This occurs randomly.
#### TNE version?(exact version number), and whether or not you've made modification to it.
TNE version 0.1.1.9. No modifications made.
#### TNE build?(/tne build), and whether or not you've made modification to it.
Running TNE build 2Beta119
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
--
#### Spigot/Bukkit version?
Paper version git-Paper-102 (MC: 1.15.2)
#### The exact command you ran w/ arguments?
-
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/scrs6qbKYS/
#### Towns affected by this issue? And whether or not they've been renamed recently.
Town name: "Auschwitz" 
Was it recently renamed? Yes, but player says it was renamed a 5-7 before this happened.
As a safe measure, I had asked the player to deposit some money in the town till we get this issue resolved. But unfortunately, it happened for the second time in the next day in the same town.

The town has been renamed twice in the past.
`Juiceless` -> `Netherville` -> `Auschwitz`

I did `/tne export` and found that each name has a lot of money still inside.
Is this normal to have? The same town has 3 entries(its previous names with balances.)
https://paste.ubuntu.com/p/RdQT6z3GjJ/

#### Nations affected by this issue? And whether or not they've been renamed recently.
-
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment]
unable to reproduce
