### ISSUE TITLE
Enderchest is not included in the balance of offline players

### ISSUE THREAD

**Issue by Binero** [TheNewEconomy/TNE-Bukkit#408]
#### What is the issue/bug you're experiencing?
When players log out, the money stored in their enderchest is not included as money part of their balance.

The issue is easily reproducible: Put 10 money in your inventory and 5 in your enderchest. Type `tne balance <player>` into the console and see that the balance is indeed 15. Log out. Type `tne balance <player>` into the console, and see that the balance is only 10 now.

#### TNE version / build

Version 0.1.1.9 build 1Beta119b

#### Modules Loaded?

None

#### Spigot/Bukkit version?
git-Paper-146 (MC: 1.15.2)

#### Is your server run in online mode?

Yes

#### The exact command you ran w/ arguments?

`tne balance Binero`

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)

`config.yml`: https://paste.ubuntu.com/p/WMG7kF4sCM/
`currencies/PBN.yml`: https://paste.ubuntu.com/p/DWWwNYv28Y/

#### Your latest server log file?

https://paste.ubuntu.com/p/M8WWhmJHpD/

**Comment by creatorfromhell** [comment]
This requires a cache or NMS usage which I won't add to TNE for sanity purposes.
