### ISSUE TITLE
A problem with the plugin QuickShop

### ISSUE THREAD

**Issue by erDUKE21** [TheNewEconomy/TNE-Bukkit#411]
**## Bug Report Format**
**#### What is the issue/bug you're experiencing?**

>.... [21:44:42 WARN]: java.lang.NullPointerException
>.... [21:44:42 WARN]: at net.tnemc.core.common.api.IDFinder.getID(IDFinder.java:134)
>.... [21:44:42 WARN]: at net.tnemc.core.common.api.TNEAPI.hasAccount(TNEAPI.java:182)
>.... [21:44:42 WARN]: at net.tnemc.core.common.api.Economy_TheNewEconomy.hasAccount(Economy_TheNewEconomy.java:67)
>.... [21:44:42 WARN]: at net.tnemc.core.common.api.Economy_TheNewEconomy.depositPlayer(Economy_TheNewEconomy.java:188)
>.... [21:44:42 WARN]: at net.tnemc.core.common.api.Economy_TheNewEconomy.depositPlayer(Economy_TheNewEconomy.java:182)
>.... [21:44:42 WARN]: at org.maxgamer.quickshop.economy.Economy_Vault.deposit(Economy_Vault.java:112)
>.... [21:44:42 WARN]: at org.maxgamer.quickshop.economy.Economy.deposit(Economy.java:55)
>.... [21:44:42 WARN]: at org.maxgamer.quickshop.shop.ShopManager.actionCreate(ShopManager.java:814)
>.... [21:44:42 WARN]: at org.maxgamer.quickshop.shop.ShopManager.lambda$handleChat$2(ShopManager.java:421)
>.... [21:44:42 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [21:44:42 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
>.... [21:44:42 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1233)
>.... [21:44:42 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [21:44:42 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1151)
>.... [21:44:42 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
>.... [21:44:42 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [21:44:42 WARN]: [QuickShop] This seems not QuickShop fault, you should cotact with your economy plugin author. (TheNewEconomy)

**#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)**

I don't know exactly how it happens.

**#### TNE version?(exact version number), and whether or not you've made modification to it.**

0.1.1.9

**#### TNE build?(/tne build), and whether or not you've made modification to it.**

I don't understand this question

**#### Modules Loaded?(exact version number), and whether or not you've made modification to it.**

Don't know what do you mean with this

**#### Spigot/Bukkit version?**

I'm using paper-221.jar

**#### Is your server run in online mode?**

it's running on online mode: false

**#### The exact command you ran w/ arguments?**

It's just an issue with the QuickShop plugin, i don't use any command

**#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)**

https://paste.ubuntu.com/p/d4sZtGmyjX/

**#### Your latest server log file?(use http://paste.ubuntu.com)**

https://paste.ubuntu.com/p/yh5VjpDNH4/

**#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)**

https://paste.ubuntu.com/p/TQHc936wTD/

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment]
[TNE-1.1.9.3-shaded.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/5011413/TNE-1.1.9.3-shaded.zip)
try this
