### ISSUE TITLE
Issue occurs when creating note 

### ISSUE THREAD

**Issue by RomainCadieu** [TheNewEconomy/TNE-Bukkit#413]
My server is in current development and I want to use TNE with towny.

TNE version?
TNE-1.1.9.2.jar

TNE build?(/tne build)
1Beta119b

Modules Loaded?
no

Spigot/Bukkit version?
paper-162.jar

Is your server run in online mode?
no

config.yml
https://paste.ubuntu.com/p/N68yQCPxsM/

Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/qD6tzT3nkw/

![unknown](https://user-images.githubusercontent.com/26386466/80891842-f6305f80-8cc6-11ea-80d2-6d6ca67ed79e.png)
![1](https://user-images.githubusercontent.com/26386466/80891848-021c2180-8cc7-11ea-9e77-3c2be8a9c72d.png)

**Comment by creatorfromhell** [comment]
Does this occur with all amounts?

**Comment by RomainCadieu** [comment]
Sure, I tried with many amount but none worked. I have thought about a way to reproduce the bug to share with you.

**Comment by ssterling** [comment]
Experiencing the same issue with only `Notable: true` in `USD.yml`.

**Comment by creatorfromhell** [comment]
Fixed in the latest pre release
