### ISSUE TITLE
removeHoldings bug

### ISSUE THREAD

**Issue by DucPr0** [TheNewEconomy/TNE-Bukkit#414]
Bug Report Format
The server I worked on had 2 currencies in TNE. The shop plugin we used takes money from the second currency.

TNE version?
TNE-1.1.9.2.jar

TNE build?(/tne build)
Don't really know

Modules Loaded?
No

Spigot/Bukkit version?
Spigot 1.15.2

Is your server run in online mode?
Yes

Issue:
Since I have located the bug, Imma just get straight into it:

File: net.tnemc.core.common.account.TNEAccount

Function: removeHoldings() with currency as an argument. For example: 
public EconomyResponse removeHoldings(BigDecimal amount, Currency currency).

Bug: The function have a hasHoldings check to see if removal of currency is possible. However, this check only contained the amount itself, and therefore is checking on the default currency instead.

Recreated:
- Consider the 2 currency names as USD and EUR, with USD being the default, and EUR being the currency the shop uses.
- If the player tries to buy a 10 EUR item, my shop plugin calls removeHoldings in the TNE API, which then refers to the removeHoldings call mentioned above.
- If USD < 10 and EUR >= 10, the shop plugin's check with hasHoldings will go through and give the player the item, however removeHoldings().success() will return a EconomyResponse.FAILURE.
- If USD >= 10 and EUR < 10, the shop plugin's check will fail. However, if the shop's check is disabled and removeHoldings() is called, it will attempt to remove the 10 EUR from an insufficent amount of money as hasHoldings() passed and therefore cause a NPE.
- If USD >= 10 and EUR >= 10, the plugin works correctly.

**Comment by creatorfromhell** [comment]
Please provide code snippets of calls you make to the TNEAPI

**Comment by DucPr0** [comment]
```
       public void canSell(EconomyHasMoneyEvent e) {
		if (noCurrency()) return;
		
		BigDecimal amount = new BigDecimal(e.getMoney());
		boolean hasMoney = plugin.getEco().hasHoldings(e.getPlayer().getUniqueId().toString(), amount, plugin.getUsedCurrency());
		
		e.setHasMoney(hasMoney);
	}

```

```
       public void withdrawEvent(EconomyWithdrawMoney e) {
		if (noCurrency()) return;
		
		e.setCancelled(true);
		BigDecimal amount = new BigDecimal(e.getMoney());
		boolean removed = plugin.getEco().removeHoldings(e.getPlayer().getUniqueId().toString(), amount, plugin.getUsedCurrency());
		if (!removed) Bukkit.getLogger().warning("Failed to take money from player " + e.getPlayer().getName());
	}
```
```
       public TNECurrency getCurrency(String identifier) {
		Set<TNECurrency> currencies = eco.getCurrencies();
		for (TNECurrency currency: currencies) {
			Bukkit.getLogger().warning(currency.getIdentifier());
			if (currency.getIdentifier().equals(currencyName)) return currency;
		}
		return null;
	}
```

Here is an event registered from the shop plugin whenever a player buys an item and the hasHoldings check pass.

- plugin.getUsedCurrency() is a call to the main class for the currency that will be taken instead of the default one. The code used to obtain the currency is present above. currencyName is the string "EUR"
- Cancelling the event prevents it from taking the default currency
- The boolean removed is the call I made to TNEAPI
As stated:
+) Player have < 10USD and >= 10EUR, canSell have the hasHoldings call returning true and therefore, the shop proceeds to withdrawEvent. However, the Bukkit warning will then appear and the second currency is unremoved.
+) Player have >= 10USD and >= 10EUR, everything works fine. EUR is taken.
+) Player have < 10USD, shopPlugin's canSell event is set to false and therefore does not proceed to withdrawEvent.
