### ISSUE TITLE
Error on startup v 0.1.1.9

### ISSUE THREAD

**Issue by Jay9519** [TheNewEconomy/TNE-Bukkit#417]
#### What is the issue/bug you're experiencing?
Getting an error on startup
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
load up the server with the plugin 
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.9
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119b
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
none
#### Spigot/Bukkit version?
Spigot 1.15.2 latest
#### Is your server run in online mode?
no, running spigot in offline mode in a travertine bungee
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/VJQfmddBjR/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/EBwxyMcd
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by Jay9519** [comment]
been working fine for around a year then all of a sudden I get the error on startup, I haven't altered anything in any way

**Comment by creatorfromhell** [comment]
Please send me your db. At first glance it appears that your db is corrupted

**Comment by Jay9519** [comment]
https://www.dropbox.com/s/ofnudkbe65yze6s/Economy.mv.db?dl=1

**Comment by creatorfromhell** [comment]
Attempted to open DB with an external software(RazorSQL), and it's not loading. You will probably have to reload from a backup.
