### ISSUE TITLE
Remove async-intialializing of plugin

### ISSUE THREAD

**Issue by suneettipirneni** [TheNewEconomy/TNE-Bukkit#418]
#### What feature are you suggesting be added?
Removal of async initializing, and add back synchronous initializing. 

#### Expected use-case for said feature?
More expected behavior for both players and developers.

#### Why should this feature be added to TNE?
Well, there's a couple of reasons, when the plugin loads, you still have to *wait* for the TNE to finish initializing even when the server has finished loading plugins. To a player, this gives mixed signals because the server shows as online, but then they will get kicked by TNE if it hasn't finished loading. On top of this, it offers virtually no benefits over a synchronous implementation because at the end of the day you still have to wait for TNE to finish initializing, *after* the server finishes loading plugins anyways.

Players aren't the only ones that are affected by this, but also plugin devs, this is a chat transcript from a dev trying to implement a currency config option in towny.
> Because TNE, which is by far the biggest Reserve economy provider, crashes if you ask for a Currency before it has finished initializing.
This also means I cannot check ahead-of-time if the configured currency is valid.

Because the loading of TNE isn't *done* after a plugin explicitly depends on it, then the thread-safety is violated by race conditions. Essentially, there's no safe way to depend and/or interact with TNE because it's dependence relies on the amount of time it takes to load. You have to cross your fingers that a third party's plugin's `onEnable()` doesn't call anything that TNE only has access to after it's loaded, or pray for the fact the TNE finished initializing before your plugin is enabled.

How to solve this issue? Make loading synchronously, have plugins actually have the ability to properly depend on this plugin. This will also remove the false positive of "being able to join" when in reality TNE will just kick you because it hasn't finished initializing.

**Comment by creatorfromhell** [comment]
This has already been changed in the local source base to use a configuration for the server owner to decide. This is due to the fact that some owners prefer the faster loading and kick message while some prefer the slower loading.

**Comment by suneettipirneni** [comment]
> This has already been changed in the local source base to use a configuration for the server owner to decide. This is due to the fact that some owners prefer the faster loading and kick message while some prefer the slower loading.

This addresses the first issue I brought up but it doesn’t address the second one. There’s no guarantee that a server is using the synchronized thread safe option therefore, plugin devs still will have situations where they’ll access data before TNE has been loaded causing crashes or undefined behavior.

**Comment by hugo4715** [comment]
I also suggest removing this feature. 
Async initialization is useless if players can't even connect to the server.

**Comment by creatorfromhell** [comment]
"Async initialization is useless "

Async initialization is not useless as it fulfills its purpose. It allows TNE to continue initializing in the background while other plugins continue to initialize themselves. Also this is a long-dead ticket, which shouldn't be necroed.
