### ISSUE TITLE
Compatibility with GUIShop

### ISSUE THREAD

**Issue by A248** [TheNewEconomy/TNE-Bukkit#419]
Hi, I'm one of the contributors to [GUIShop](https://github.com/pablo67340/GUIShop) and I noticed that TNE explicitly doesn't load when GUIShop is present. One of our users was having a problem where GUIShop couldn't find an economy plugin, and it turned out to be because TNE disables itself when GUIShop is present.

I noticed you did this in 4fee78831f4188ab522dd6777e4b64b92ec5fd13. Is there any reason why TNE is not compatible with GUIShop? Is it something we've done? If so, I would appreciate if you could point us in the right direction as to the source of the incompatibility, or possibly collaborate on a solution, instead of just disabling TNE when GUIShop is present, which causes a lot of headaches with support.

Since I couldn't find any reasons why you added this functionality into TNE, I'm very confused why this was done. GUIShop uses standard Vault API methods. At the very least, could you not add some explanation to the log statement?

#### What is the issue/bug you're experiencing?
TNE shuts down when GUIShop is present with the following message:
```
[TheNewEconomy] Unable to load The New Economy as it is incompatible with GUIShop.
```

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Install GUIShop and TNE

#### TNE version?(exact version number), and whether or not you've made modification to it.
Master branch as of 4fee78831f4188ab522dd6777e4b64b92ec5fd13

#### TNE build?(/tne build), and whether or not you've made modification to it.
n/a
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
n/a
#### Spigot/Bukkit version?
Either, it won't matter
#### Is your server run in online mode?
Either, it won't matter
#### The exact command you ran w/ arguments?
n/a
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
n/a
#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/JRQQufxq

**Comment by creatorfromhell** [comment]
If I remember correctly, this was put in place as TNE was going to switch to Reserve only rather than utilizing the vault API since it allows TNE users to have a better feature suite and takes advantage of the multi currency support that TNE has. I have no problem removing it, but if GUIShop doesn't support Reserve and TNE goes that direction I'll have to have server owners convert to a shop plug-in with Reserve support such as QuickShop or chestshop

**Comment by A248** [comment]
I can understand if you won't be supporting Vault, but I'm still not sure how that would merit a "TNE is not compatible with GUIShop" message. There are lots of plugins using the Vault API and GUIShop is just one of them. We receive a lot of support requests, including from many users who are new to the MC hosting scene, and I wouldn't want them to be confused why TNE is disabling itself or think that it's a problem with GUIShop.

**Comment by creatorfromhell** [comment]
I could change the message to "TNE doesn't support this plug-in since it doesn't support Reserve." I suppose if I go that route

**Comment by A248** [comment]
I'm done. We're not supporting Reserve as far as I can foresee, sorry.
