### ISSUE TITLE
Broken economy episode 2

### ISSUE THREAD

**Issue by 3meraldK** [TheNewEconomy/TNE-Bukkit#422]
#### What is the issue/bug you're experiencing? 
The economy works in online-mode only
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
1. set mode to offline-mode
2. run a server
#### TNE version?(exact version number), and whether or not you've made modification to it.
1.1.9b
#### TNE build?(/tne build), and whether or not you've made modification to it.
1Beta119b
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No
#### Spigot/Bukkit version?
Paper-353
#### Is your server run in online mode?
**No**
#### The exact command you ran w/ arguments?
No
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/yz9c57WFJJ/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/WRnRC7Hr64/

#### Edit nr 1
I know it's a "known" issue with BungeeCord now. How to fix that and are you fixing it?
#### Edit nr 2
It works in "50%", because I now hold stacks of gold blocks. My wealth updates each some long time, Idk why. Also it can be overused, for example paying gold to city and depositing real gold in chest, can be duped this way

**Comment by creatorfromhell** [comment]
This is a duplicate issue.
