### ISSUE TITLE
Allow Self Signed CA to connect with SSL

### ISSUE THREAD

**Issue by lucasboss45** [TheNewEconomy/TNE-Bukkit#426]
#### What feature are you suggesting be added?
Config option to disable SSL Certificate verification

#### Expected use-case for said feature?
Allow SSL connection to MySQL databases with a Self Signed Certificate

#### Why should this feature be added to TNE?
To allow SSL connections with Self Signed Certificates as Signed Certificate can cost hundreds of Euros

**Comment by creatorfromhell** [comment]
Try the answer seen here, https://stackoverflow.com/questions/47023263/mysql-ssl-verify-server-cert-true-is-returning-ssl-certificate-validation-fai

**Comment by creatorfromhell** [comment]
This is an issue resolved at host-level not plugin-level.
