### ISSUE TITLE
Server crashing when using latest version.

### ISSUE THREAD

**Issue by Agaloth** [TheNewEconomy/TNE-Bukkit#427]
#### What is the issue/bug you're experiencing? 
`My server instantly freezes once booted up with the latest version of TNE.`

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
 `Install the latest version of TNE?`

#### TNE version?(exact version number), and whether or not you've made modification to it. 
`Beta 1.1.9d on spigot`

#### TNE build?(/tne build), and whether or not you've made modification to it.
`Can't get that since I can't even run commands when running the latest version.`

#### Spigot/Bukkit version?
`I tried spigot, paper #378 and tuinity-"5268ef9" all in 1.15.2.`

#### Is your server run in online mode?
`Yes.`
#### The exact command you ran w/ arguments?
`No commands ran, just a global server freeze, but I've tried using every spigot forks and spigot itself, uninstalling protocolsupport and installing viaversion + viabackwards, tried without viaversion + viabackwards + protocolsupport, deleted usercache.json, switched from java 11 to java 8 but nothing fixed it.`

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
`https://paste.ubuntu.com/p/XHcXd2PzYj/`

#### Your latest server log file?(use http://paste.ubuntu.com)
`Latest paper #378 restart with latest TNE: https://paste.ubuntu.com/p/GyvVdsyT2W/`
`Tuinity gets the same stacktrace.`

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
`Nothing to do with that normally`

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment]
As stated on discord: This is the same error as last time that was advised to contact paper.. Did you contact the paper team?

**Comment by creatorfromhell** [comment]
http://prntscr.com/tf0zrr unable to reproduce see above comment.
