### ISSUE TITLE
Minor Tier Currency Weight can't be lower than 1

### ISSUE THREAD

**Issue by nacjm** [TheNewEconomy/TNE-Bukkit#428]
#### What is the issue/bug you're experiencing?
If you set the minor weight of a a currency tier to a decimal number less than 1 all tiers fail to load into TNE
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Create a minor currency tier with a decimal number weight less than one.
#### TNE version?(exact version number), and whether or not you've made modification to it
1.1.9.3
#### TNE build?(/tne build), and whether or not you've made modification to it.
0.1.1.9d
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Signs 0.1.3 Mobs 0.1.3
#### Spigot/Bukkit version?
Mohistversion  git-Mohist-1.12.2-baf4531 (MC: 1.12.2)(Implementing API version 1.12.2-R0.1-SNAPSHOT)
#### Is your server run in online mode?
yes
### The exact command you ran w/ arguments?
No commands error happened on server restart
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/BHMVbkRMNz/
#### Your latest server log file?(use http://paste.ubuntu.com)
Ok the log is large enough I am quite literally crashing pate.ubuntu.com and gist.github.com trying to paste it in so i will just upload it here at the bottom
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/TvCVBGMG72/
Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

[latest (6).txt.gz](https://github.com/TheNewEconomy/TNE-Bukkit/files/4905394/latest.6.txt.gz)
(A gzip because otherwise github screams yowza at the filesize)

**Comment by creatorfromhell** [comment]
The minor weight is meant to not be less than 1....
