### ISSUE TITLE
TNE & quickshop, it doesnt recognise it as a currency

### ISSUE THREAD

**Issue by ShadiestGoat** [TheNewEconomy/TNE-Bukkit#432]
When I try to buy stuff from quickshop (qs), it doesnt recognise that i have any money, althou i added around 40000$. I did manage to sell something, and then i was able to buy stuff with the money :?
TNE BUILD: 0.1.1.9d
No modules or modifications
Spigot 1.15.2
Online mode on
Config: https://paste.ubuntu.com/p/5sJsTmRfyk/
Nothing noteworthy on logs

**Comment by creatorfromhell** [comment]
Seems to be fixed in latest builds from what I've tested.
