### ISSUE TITLE
The New Economy is still initializing.

### ISSUE THREAD

**Issue by hugo4715** [TheNewEconomy/TNE-Bukkit#435]
#### What is the issue/bug you're experiencing?
Sometimes, when the servers load players can't connect and get kicked  with reason 'The New Economy is still initializing.' forever.
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
I don't know yet, it seems random but i'm still trying to find out why.
#### TNE version?(exact version number), and whether or not you've made modification to it.
I recently upgraded to 0.1.1.9 but it also hapenned on older versions.
#### TNE build?(/tne build), and whether or not you've made modification to it.
Build 0.1.1.11
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Default modules
#### Spigot/Bukkit version?
SportPaper 1.8.8 
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
Does not apply
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
Default with just advanced=true changed
#### Your latest server log file?(use http://paste.ubuntu.com)
The only message is 
`[21:02:33] [User Authenticator #2/INFO]: Disconnecting com.mojang.authlib.GameProfile@6b417760[id=a864464f-355f-464d-aa99-4bc0fdaa792f,name=hugo4715,properties={textures=[com.mojang.authlib.properties.Property@36d07b06]},legacy=false] (/removed ip): The New Economy is still initializing.`
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
Does not apply

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment]
This is an intended functionality that happens while items.yml is loading.

**Comment by hugo4715** [comment]
Yes but it's happenning forever it's not supposed to players cannot connect at all.

**Comment by faguoren** [comment]
Grave digging for the record:

> This is an intended functionality that happens while items.yml is loading. 

This is neither a user-friendly functioanlity, nor a properly implemented functionality.

Have a good day.

**Comment by creatorfromhell** [comment]
> Grave digging for the record:
> 
> > This is an intended functionality that happens while items.yml is loading.
> 
> This is neither a user-friendly functioanlity, nor a properly implemented functionality.
> 
> Have a good day.
This has been changed in recent pre releases, but thanks for the added input!
