### ISSUE TITLE
Question: HIGH!

### ISSUE THREAD

**Issue by SundraLOL** [TheNewEconomy/TNE-Bukkit#437]
When new players join they earn 200 gold even if the economy server account is set to 0

**Comment by creatorfromhell** [comment]
> When new players join they earn 200 gold even if the economy server account is set to 0

The server account balance has nothing to do with default balance. Check your config file, and configure properly. https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/TNE/src/net/tnemc/resources/config.yml#L224 Nowhere in the documentation for the default balance configuration does it state "if the server account has the funds."
