### ISSUE TITLE
Near every day at ~5 AM the server got stuck and crashes.

### ISSUE THREAD

**Issue by xManInWhitex** [TheNewEconomy/TNE-Bukkit#440]
#### What is the issue/bug you're experiencing?
Near every day at ~5 AM the server got stuck and crashes.
In the paper dump there are some SQL workers of TNE (As seen at line 1085 of the log file)

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
I don't know, it occurs without any warning. I don't have to do something for it to occur.

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.12 without modifications

#### TNE build?(/tne build), and whether or not you've made modification to it.
0.1.1.12 without modifications

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
None

#### Spigot/Bukkit version?
Paper-MC#202-1.16.3

#### Is your server run in online mode?
Paper not but Bungee is in online mode

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/7kTmhmt2

#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/b6q1UXDd

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
What does this point mean?

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment]
Does this not occur anymore or?

**Comment by xManInWhitex** [comment]
It was a Problem of the MySql server.
It was stuck due a big amount of Data from dynmap.

Your plugin seems to be the first plugin which wanted to access the server after it got stuck. I think thats why your plugin is listed in the Paper error report.
