### ISSUE TITLE
MaxBalace wont limit account balance

### ISSUE THREAD

**Issue by xManInWhitex** [TheNewEconomy/TNE-Bukkit#441]
#### What is the issue/bug you're experiencing?
If I set the value MaxBalance of my currency (Default) to 50000.0 (or 50000), the player can have
100000 on their account without any problem.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Set MaxBalance to a specific value and give the player more money

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.12

#### TNE build?(/tne build), and whether or not you've made modification to it.
0.1.1.12

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
none

#### Spigot/Bukkit version?
Paper 1.16.3 (204)

#### Is your server run in online mode?
no but with bungee cord in front of it

#### The exact command you ran w/ arguments?
/money balance

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://pastebin.com/hq6G5qhj

#### Your latest server log file?(use http://paste.ubuntu.com)
https://pastebin.com/HQNycnCY

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by xManInWhitex** [comment]
@creatorfromhell ?

**Comment by creatorfromhell** [comment]
> @creatorfromhell ?

Tickets are responded to in the order they are received, so don't @ please I will get to this in the order it's received
