### ISSUE TITLE
TNE issues after updating towny to 0.96.2.12 and higher

### ISSUE THREAD

**Issue by DanDose** [TheNewEconomy/TNE-Bukkit#442]
Hello!
My server is on 1.16.1 version (haven't updated it, as i can't update towny because of TNE issues). The server name is OriginEarth.

#### What is the issue/bug you're experiencing?
I experience an issue after I update Towny to version 0.96.2.12 and higher. Towny commands, that require data from TNE such as /t, /t (townname) take a long time to load. /player (nickname) commands take too long to load too. After talking with towny dev we came to conclusion that it is TNE that causes the errors. Also, when using /bal the console gets errors and the server crashes. Same happens if a few players join.

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
0) My server was on 0.96.2.0 towny version. 
1) After i updated it to 0.96.2.12 (note .0.96.2.4 changes database of towny, but it was ok when i updated to it; 0.96.2.12 also changes database of towny) or higher version, the issues appears, when i 
2) try to do commands /t, /t (townname), /player (nickname) and most importanty 
2.1) the error appears in logs when using command /bal or when other players join the server and the server eventually crashes.

#### TNE version?(exact version number), and whether or not you've made modification to it.
TNE version is 0.1.1.12. No modifications, except for config changes.

#### TNE build?(/tne build), and whether or not you've made modification to it.
TNE build 0.1.1.12, no modifications, except for configt changes.

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No modules loaded.

#### Spigot/Bukkit version?
Spigot version 1.16.1-b138

#### Is your server run in online mode?
Yes, the server is in online mode.

#### The exact command you ran w/ arguments?
I used command /bal DanDose or other player's nickname and after that the server started lagging and eventually crashed (the errors started appearing in console, which u can check in the logs below). If I used command /t Cyrene or other town name it would load very long, same with /player DanDose or other player nickname.

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
Here is the config.yml, the changed configs are highlighted with 1!.
https://paste.ubuntu.com/p/q8ZbTDwvmQ/

#### Your latest server log file?(use http://paste.ubuntu.com)
Here is the log file for when i tried to update the server last time.
https://paste.ubuntu.com/p/ZWJZ37Trbp/

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
worlds/players/messages/items configurations were not changed.

P.S.
The served had TNE database issues once, due to which I had to /extract the database and /restore it. This was long ago, like 2 months ago.
I never tried to /tne purge.

I hope i described everything correctly.

Waiting for your answer,
Thanks for your time

**Comment by introvertism** [comment]
Running into the same issue, happens anytime someone uses /t claim as well.

**Comment by creatorfromhell** [comment]
Try this build https://cdn.discordapp.com/attachments/267902896970924036/770657690392330280/TNE-0.1.1.12.jar

**Comment by DanDose** [comment]
Here is result of testing: https://paste.ubuntu.com/p/3znRRjdMS7/
All seems to be working fine, even if more players join, but TNE has sent TNE error log at line 729. Idk what that means. It didn't affect anything in-game though, i think.

**Comment by creatorfromhell** [comment]
Responded on discord; appears to be fixed.
