### ISSUE TITLE
Error when using with QuickShop & Enderchests

### ISSUE THREAD

**Issue by rshuttle1337** [TheNewEconomy/TNE-Bukkit#445]
#### What is the issue/bug you're experiencing?
I am using diamonds as an item currency. My diamonds are in my enderchest (I had 52). I purchase something for 2 diamonds from a shop (using the QuickShop plugin) and the shop owner is paid 2 diamonds, however I am charged 50 diamonds (essentially, my balance is set to the amount I paid). I also asked about this on the QuickShop Discord and they told me to make a bug report for TNE. 
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
See above
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.12 with no modifications
#### TNE build?(/tne build), and whether or not you've made modification to it.
0.1.1.12
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
None
#### Spigot/Bukkit version?
1.16.4 PaperMC build 274
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
n/a
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/kwNfB6wqp7/
#### Your latest server log file?(use http://paste.ubuntu.com)
n/a
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
n/a
Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

> Use the correct format. The template you erased is required for a reason.
> 
> _Originally posted by @creatorfromhell in https://github.com/TheNewEconomy/TNE-Bukkit/issues/444#issuecomment-726939477_

With regards to this, there was no template when I made my bug report, I didn't delete anything. 

Thank you for your help!

**Comment by creatorfromhell** [comment]
Server log?

**Comment by rshuttle1337** [comment]
> Server log?

Hey, I couldn't find anything on the log referring to it so I decided not to post it

**Comment by creatorfromhell** [comment]
> > Server log?
> 
> Hey, I couldn't find anything on the log referring to it so I decided not to post it

Ok so then we'll go off limited info. Does the same issue work with money out of the ender chest? Also turn off server, enable debug and start up and perform the same transaction and post that server log.

**Comment by rshuttle1337** [comment]
Here's the log from when I make a purchase:

https://paste.ubuntu.com/p/Bk6jFSVHBX/

> Does the same issue work with money out of the ender chest?
Sorry I am not sure what you mean?

**Comment by creatorfromhell** [comment]
> Here's the log from when I make a purchase:
> 
> https://paste.ubuntu.com/p/Bk6jFSVHBX/
> 
> > Does the same issue work with money out of the ender chest?
> 
> Sorry I am not sure what you mean?

The full log that one is missing details I'm looking for.

And I mean if you have 52 diamonds in your inventory, instead of ender chest and inventory does it work correctly?

**Comment by tdfischer** [comment]
What's the steps to create a full log? I have this issue on my sever as well. We're using Cobblestone instead of diamonds, but its all the same. Payments that involve ender chests are unpredictable. Possibly related, Towny is unable to charge people the daily tax on their accounts when they're offline and I'm unable to query the balance of offline players.

**Comment by tdfischer** [comment]
Still not sure what a full log is, but I've built the master branch and turned on all the debug output I could find. Here's the output:

https://gist.github.com/tdfischer/5f4db147dc7f52acb846c3745a435199

Bug doesn't even need QuickShop to reproduce. Here's the steps:

1. `/money give @p 7000` - You should now have 7000 according to `/balance`
2. Deposit your currency into an ender chest
3. Confirm that `/balance` still says 7000
4. `/money take @p 15`
5. Witness that your balance is now 15, and the enderchest only holds 15 units of currency.
