### ISSUE TITLE
/money doesnt work when added to plugins

### ISSUE THREAD

**Issue by GreenArroww** [TheNewEconomy/TNE-Bukkit#451]
Hello there! the issue is:
Prizes:
  '1':
    Chance: 75
    Messages:
      - '&7You have just found &a$500&7.'
    Commands:
      - 'money give %Player% 500'
      **as you can see its a crate reward command, when I had essentials it worked but when I moved to this economy I had to change eco to money so may ik if I shld change it back to eco or what shld I type there so that when a player gets the price it types the command in console.**

**Comment by creatorfromhell** [comment]
http://prntscr.com/1folyr6 This works in my test with the plugin GoldenCrates.
