### ISSUE TITLE
Low TPS and ThreadDump

### ISSUE THREAD

**Issue by Wolf2323** [TheNewEconomy/TNE-Bukkit#452]
#### What is the issue/bug you're experiencing?
After we noticed bad TPS(10) i did ``/timigs report` and this is the result: https://timings.aikar.co/?id=d3aa2081981645178518d094294e554c
A while later we got a ThreadDump and it looks like TNE: https://paste.ubuntu.com/p/nPbYyRky2g/

#### TNE version?(exact version number), and whether or not you've made modification to it.
version `0.1.1.12` no Modifications

#### TNE build?(/tne build), and whether or not you've made modification to it.
build `0.1.1.12` no Modifications

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
`none`

#### Spigot/Bukkit version?
`git-Tuinity-"8056d13"`

#### Is your server run in online mode?
`yes`

#### The exact command you ran w/ arguments?
`none`

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/BMQmjnZTt6/

#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by Wolf2323** [comment]
Today it repeated this situation again:
The Timings: https://timings.aikar.co/?id=ac7b162b368745ccb9a2f1c7549e3cc2
This time it is the `SaveWorker`
And a threaddump again: https://paste.ubuntu.com/p/s7TxdKR4VY/

**Comment by creatorfromhell** [comment]
The saveworker will always be higher but it isn't run on the main thread. There is a prerelease build on the discord that corrects tps issues

**Comment by Wolf2323** [comment]
But what is with the first issue, that is caused by `PlayerInteractEvent`?

**Comment by creatorfromhell** [comment]
> But what is with the first issue, that is caused by `PlayerInteractEvent`?
> But i test the Pre-Release

it was resolved with the pre release as I stated above.....,....

**Comment by Wolf2323** [comment]
And again, we have a ThreadDump after updating https://paste.ubuntu.com/p/shjpKg4WRc/

**Comment by creatorfromhell** [comment]
> And again, we have a ThreadDump after updating https://paste.ubuntu.com/p/shjpKg4WRc/

Create a new ticket with the updated thread dump
