### ISSUE TITLE
Player with 2 amounts off money (when online and when offline)

### ISSUE THREAD

**Issue by jusobreira** [TheNewEconomy/TNE-Bukkit#456]
#### What is the issue/bug you're experiencing?

When a player is online he have a specific amount, if he is offline the player have other amount. I delete the player's acount using tne delete NICK when he was online and offline. I also deleted the database with his money. This happens with 2 players as far as I know. The others works fine

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Give a money to a player online and check his balance when he is offline. (don't happen with all the players)

#### TNE version?(exact version number), and whether or not you've made modification to it.
![image](https://user-images.githubusercontent.com/10175304/106165568-013af200-616a-11eb-8c3f-ab5a0a2f77bb.png)

#### TNE build?(/tne build), and whether or not you've made modification to it.
![image](https://user-images.githubusercontent.com/10175304/106165623-0b5cf080-616a-11eb-8183-69210c1be3af.png)

#### Spigot/Bukkit version?
![image](https://user-images.githubusercontent.com/10175304/106165662-16178580-616a-11eb-9b99-184aafc9499e.png)

#### Is your server run in online mode?
offline
#### The exact command you ran w/ arguments?
/money other NICK

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/RVWKjnT6n3/

#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/xXR2yMsvj7/

**Comment by creatorfromhell** [comment]
"Is your server run in online mode?
offline"
UUIDs are not guaranteed to work for offline servers using TNE. Support isn't provided to cracked servers.
