### ISSUE TITLE
Startup SQL table update Bug

### ISSUE THREAD

**Issue by lrmtheboss** [TheNewEconomy/TNE-Bukkit#457]
#### What is the issue/bug you're experiencing?
Error when it attempts to update the database tables on startup
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
restart the server
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.12 (no modifications)
#### TNE build?(/tne build), and whether or not you've made modification to it.
0.1.1.12 (no modifications)
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
none besides built-in ones
#### Spigot/Bukkit version?
 Purpur-967 (MC: 1.16.5)
#### Is your server run in online mode?
yes
#### The exact command you ran w/ arguments?
N/A
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/GV5xpfxpFD/
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/XzvH4NXF2J/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
N/A

SQL Server Version
MariaDB 10.5.6

**Comment by lrmtheboss** [comment]
Why was this closed? This is still a current issue

**Comment by creatorfromhell** [comment]
> Why was this closed? This is still a current issue

This was closed because I closed it. Under the new library that tne is being shifted to this report was invalidated

**Comment by lrmtheboss** [comment]
> > Why was this closed? This is still a current issue
> 
> 
> 
> This was closed because I closed it. Under the new library that tne is being shifted to this report was invalidated.

oh alright thank you
