### ISSUE TITLE
GUIShop Marked Incompatible, without Collaboration Request?

### ISSUE THREAD

**Issue by pablo67340** [TheNewEconomy/TNE-Bukkit#459]
#### What is the issue/bug you're experiencing?

I am having users contact me saying TNE is not working with GUIShop. After investigation, I've come to find:
https://github.com/TheNewEconomy/TNE-Bukkit/blob/77cd3415557bada8e92d57a824e5aa5e313169c5/TNE/src/net/tnemc/core/TNE.java#L172

Which interesting as I've never once received a message from anybody looking to work out compatibility issues. I find it odd that your simple solution would be to blacklist one of the single most used shop plugins out there, especially when your plugin is Open Sourced (Meaning external collaboration/inquires are expected). I am more than willing to work out a compatibility bridge, however I get the feeling this is probably not in your interest I feel one of TNE's creators would've already contacted me.

If you'd like to proceed with working out compatibility issues, please add my Discord directly. 

Discord (Case Sensitive, Without Space): Bryce# 0001

*Now proceeding to fill in your format as you do not offer a general inquiry format. 

#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Simply starting your server with GUIShop installed *shrug*

#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.12

#### TNE build?(/tne build), and whether or not you've made modification to it.
No clue. This is coming from many GUIShop users.

#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No clue. This is coming from many GUIShop users.

#### Spigot/Bukkit version?
Anywhere from 1.8-1.16.5 (If your plugin supports those versions)

#### Is your server run in online mode?
No clue. This is coming from many GUIShop users.

#### The exact command you ran w/ arguments?
N/A

#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
N/A

#### Your latest server log file?(use http://paste.ubuntu.com)
N/A

Hope to hear back from somebody.

**Comment by creatorfromhell** [comment]
https://github.com/TheNewEconomy/TNE-Bukkit/issues/419

**Comment by Skyslycer** [comment]
To understand that right:
You opened an issue like 3 years ago.
Bryce didn't want to add Reverse support because it isn't used by almost anyone. Vault is the winner here. And then, when you create a nice economy system that supports vault, you disable GUIShop because Bryce didn't want to add support for something that almost no one uses. I've never seen someone with Reverse as a  Vault replace.

Thats my understanding.
Am I right or am I just completely dumb.
