### ISSUE TITLE
[0.0.2.4] Messages.yml does absolutely zilch

### ISSUE THREAD

**Issue by JackBarnett2016** [TheNewEconomy/TNE-Bukkit#46]
Hey!

I'm assuming this is going to be something that is WIP, but! Your plugin generates a messages.yml which gives the impression that we're able to edit the messages within the plugin, but having read through your source code it seems like the meessages are all hard coded, alongside this eediting the config does nothing ingame with either /tne reload or a restart.

Are you planning to release this with Alpha 3? It's a dealbreaker for the server I'm currently working on.

Thanks!

**Comment by creatorfromhell** [comment]
Messages work, the only thing hard coded is the default value so it doesn't error out if someone elects to remove any from the yaml file
