### ISSUE TITLE
Global currency with different world names

### ISSUE THREAD

**Issue by JeffHD** [TheNewEconomy/TNE-Bukkit#460]
Hey,
I am not able to create a global currency.
In my config.yml, Core.Multiworld is false and Core.Currency.Info.Advanced is true.
In the USD.yml all information is the same and global is true. I have different balances on each server. In the MySQL databases I have a separate entry for each world. For example Server 1 with the world name world_farm and Server 2 with the world name world_build have separate balances and so on. How do I get a global currency no matter what the world is called or do I miss something in the configs.
thanks

**Comment by creatorfromhell** [comment]
Did you restart your server after configuration multiworld to false?

**Comment by JeffHD** [comment]
Do you mean the worlds.yml or what world config? and what do i need to set to globalworld

**Comment by JeffHD** [comment]
What I found out is that the /money command always changes the balance which was created first. but the display of the balance with vault shows 0 until some other plugin gives me money. Money that is paid, for example, as a vote reward, chest shop or in general via vault, then goes into a new account.

Account created on Server 1 with world world_1 now i'm on Server 2 with the world world_2

UUID | Main Server | world_1 | USD | 2000.0000         <-- /money give

UUID  | Main Server | world_2 | USD | 1000.000          <-- money from other plugins over vault

vault placeholder for tablists only showing the balance from the world i'm on

**Comment by creatorfromhell** [comment]
> Do you mean the worlds.yml or what world config? and what do i need to set to globalworld

I mean did you follow the FAQ for this on the discord page before posting a ticket?
