### ISSUE TITLE
Possible NPE if username of OfflinePlayer is null

### ISSUE THREAD

**Issue by Phoenix616** [TheNewEconomy/TNE-Bukkit#461]
It is possible to cause an NPE in the Economy_TheNewEconomy method on the range-patch branch if the username of an OfflinePlayer is null (a case which is possible in the API when getting an OfflinePlayer object by its UUID without the name being known/cached).

The code in question (that I found, there might be more cases):

https://github.com/TheNewEconomy/TNE-Bukkit/blob/b24e7063b1e74950c185073ff6f841c7a277d901/TNE/src/net/tnemc/core/common/api/Economy_TheNewEconomy.java#L298

https://github.com/TheNewEconomy/TNE-Bukkit/blob/b24e7063b1e74950c185073ff6f841c7a277d901/TNE/src/net/tnemc/core/common/api/Economy_TheNewEconomy.java#L263

See ChestShop-authors/ChestShop-3#438 for the full error log and a use case which causes that.

**Comment by creatorfromhell** [comment]
Gotcha, fixing this in my working branch now.
