### ISSUE TITLE
Dumb messages

### ISSUE THREAD

**Issue by roast247** [TheNewEconomy/TNE-Bukkit#463]
I'm using the newest pre-release, and every time I join the server, it says somewhere on the lines of "Thank you for testing this prerelease", how the hell do I disable that absolute useless feature?

**Comment by creatorfromhell** [comment]
Set Update to false in config.yml, also you should try being less rude next time.

**Comment by roast247** [comment]
apologies for my rudeness, just very frustrated

**Comment by creatorfromhell** [comment]
> apologies for my rudeness, just very frustrated

Yes an in-game message on Minecraft is frustrating enough to be rude to someone.

**Comment by roast247** [comment]
yes
