### ISSUE TITLE
Checking balance of a towny account fails

### ISSUE THREAD

**Issue by Semisol** [TheNewEconomy/TNE-Bukkit#466]
#### What is the issue/bug you're experiencing?
Cannot view Towny account `towny-war-chest` using /bal
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Run `/bal towny-war-chest`
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.12, no modifications
#### TNE build?(/tne build), and whether or not you've made modification to it.
0.1.1.12, no modifications
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
None
#### Spigot/Bukkit version?
This server is running Tuinity version git-Tuinity-"94f025a" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 30 version(s) behind
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
`/bal towny-war-chest`
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://hastebin.semisol.dev/eJ6ejH9uLhtRSOl4jWGT3l.yaml
#### Your latest server log file?(use http://paste.ubuntu.com)
(relevant stacktrace)
```
Caused by: java.lang.NullPointerException
        at net.tnemc.core.common.transaction.TNETransaction.perform(TNETransaction.java:67) ~[?:?]
        at net.tnemc.core.commands.money.MoneyOtherCommand.execute(MoneyOtherCommand.java:103) ~[?:?]
        at net.tnemc.core.commands.money.MoneyCommand.execute(MoneyCommand.java:116) ~[?:?]
        at net.tnemc.core.TNE.customCommand(TNE.java:697) ~[?:?]
        at net.tnemc.core.TNE.onCommand(TNE.java:686) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
        ... 19 more
```
https://hastebin.semisol.dev/XlY4QOPnDTxh4-DFHm8_m0.txt for full
#### Towns affected by this issue? And whether or not they've been renamed recently.
None
#### Nations affected by this issue? And whether or not they've been renamed recently.
None
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
Not relevant

**Comment by creatorfromhell** [comment]
Is this using the latest pre-release in the discord server?

**Comment by Semisol** [comment]
Nope.

**Comment by creatorfromhell** [comment]
> Nope.

I would try that first

**Comment by Semisol** [comment]
Okay thanks for letting me know, will join and download

**Comment by Semisol** [comment]
Works.
