### ISSUE TITLE
Unable to contact update servers

### ISSUE THREAD

**Issue by No767** [TheNewEconomy/TNE-Bukkit#467]
#### What is the issue/bug you're experiencing?

When at startup, tne attempts to contact the update servers but fails
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)

1. Put in tne in the plugin folder
2. Start the server up

#### TNE version?(exact version number), and whether or not you've made modification to it.
Version 0.1.1.12
#### TNE build?(/tne build), and whether or not you've made modification to it.
TNE build 0.1.1.12
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No modules
#### Spigot/Bukkit version?
Paper-1.16.5-778
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
N/A
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/XHwshfNPr2/ 
#### Your latest server log file?(use http://paste.ubuntu.com)
https://paste.ubuntu.com/p/x5jtdVFXcM/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by OskyEdz** [comment]
Can confirm on Java 16, Debian 11 server.
Running Paper-MC 778 for MC 1.16.5
Offline Mode in BungeeCord-setup.

I run with following arguments: 
java -Xms1024M -Xmx4G -Dfile.encoding=UTF-8 -jar server.jar

**Comment by creatorfromhell** [comment]
Try this again, it seems to be working properly now. Was in the middle of transferring over SSL certs to the new server.

**Comment by OskyEdz** [comment]
Yep, looks all good now!

**Comment by creatorfromhell** [comment]
Cheers.
