### ISSUE TITLE
[BUG] with hybrid jar

### ISSUE THREAD

**Issue by DaDiGui** [TheNewEconomy/TNE-Bukkit#468]
####What is the issue/bug you're experiencing?
Being OP does not allow me to perform test commands like for example: _/money give <player> <amount> [world] [currency]_
####How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Execute _/money give <player> <amount>_
#### TNE version?
0.1.1.12
#### TNE build?
0.1.1.12
#### Spigot/Bukkit version?
Im using a hybrid jar for plugins/mods
forge-1.16.5-36.1.24
arclight-forge-1.16-1.0.19
#### Is your server run in online mode?
yes
#### The exact command you ran w/ arguments?
_/money give DaDigui 200 world EUR_
#### config.yml
https://paste.ubuntu.com/p/yc8b7vqXCc/
#### Your latest server log file?
https://paste.ubuntu.com/p/VWy8B8QN7s/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.
currencies: 
 -EUR: https://paste.ubuntu.com/p/QXXGX5b9G5/
    -centimo1.yml > https://paste.ubuntu.com/p/Cnx9FyZCwv/
    -centimo2.yml > https://paste.ubuntu.com/p/99cN8PgyWM/
    -centimo5.yml > https://paste.ubuntu.com/p/7wV5zbXGcF/
    -centimo10.yml > https://paste.ubuntu.com/p/n4NcptP2PP/
    -centimo20.yml > https://paste.ubuntu.com/p/Ky2z8Vv7bN/
    -centimo50.yml > https://paste.ubuntu.com/p/BkcRPn32J7/
    -euro1.yml > https://paste.ubuntu.com/p/KVnKC7bqDD/
    -euro2.yml > https://paste.ubuntu.com/p/6gwVfMshzD/
    -euro5.yml > https://paste.ubuntu.com/p/WVWWKtqpZw/
    -euro10.yml > https://paste.ubuntu.com/p/zY3ZcMWZq7/
    -euro20.yml > https://paste.ubuntu.com/p/kT3NcxNykW/
    -euro50.yml > https://paste.ubuntu.com/p/n2qtZ9dSgc/
    -euro100.yml > https://paste.ubuntu.com/p/fQkp2QyfPt/
    -euro200.yml > https://paste.ubuntu.com/p/DYJfZWx2Mk/
    -euro500.yml > https://paste.ubuntu.com/p/vHyC4wpKFB/

**Comment by creatorfromhell** [comment]
Closing this as we are focusing on core jars only currently.
