### ISSUE TITLE
Lands Support?

### ISSUE THREAD

**Issue by MasterMetaphor** [TheNewEconomy/TNE-Bukkit#469]
Is it a possibility that Lands support will be added for The New Economy?

https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-nations-wars-1-17-support.53313/updates

**Comment by creatorfromhell** [comment]
TNE supports any plugin that supports vault, not sure what they would be doing differently that wouldn't cause it to be supported, but generally most plugins are supported.

**Comment by creatorfromhell** [comment]
Tried looking into this, but they don't outline how they send their information through vault, so I'm assuming if it doesn't work properly they're adding a prefix. However, they aren't open-source so I can't say for sure.
