### ISSUE TITLE
TNE 0.1.1.13-PRE-6 Error

### ISSUE THREAD

**Issue by Caleston** [TheNewEconomy/TNE-Bukkit#473]
**## Bug Report Format**
**#### What is the issue/bug you're experiencing?**
TNE Pre-release 0.1.1.13-PRE-6 errors upon start and problems affecting Towny and Dynmap-Towny
**#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)**
Starting server or executing Towny commands
**#### TNE version?(exact version number), and whether or not you've made modification to it.**
TNE Pre-release 0.1.1.13-PRE-6, no modifications
**#### TNE build?(/tne build), and whether or not you've made modification to it.**
TNE Pre-release 0.1.1.13-PRE-6, no modifications
**#### Modules Loaded?(exact version number), and whether or not you've made modification to it.**
Paper 1.17.1-130, no modifications. Tested on older Paper 1.17.1-90 as well, same result.
**#### Is your server run in online mode?**
Yes
**#### The exact command you ran w/ arguments?**
Startup of server. For Towny: /t list for example.
**#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)**
https://paste.ubuntu.com/p/gZhMMQVxW7/ (at the bottom)
**#### Your latest server log file?(use http://paste.ubuntu.com)**
https://paste.ubuntu.com/p/gZhMMQVxW7/

Great job on adding the requested features so quickly by the way.

**Comment by creatorfromhell** [comment]
which towny version?

**Comment by creatorfromhell** [comment]
I modified a couple things before testing, but the attached build works for me. http://prntscr.com/1fodp80 Made several /t deposits within minutes to try to break it. Using the latest towny pre release 0.97.0.16. Java 16
[TNE-0.1.1.13-PRE-7.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/6873814/TNE-0.1.1.13-PRE-7.zip)

**Comment by Caleston** [comment]
It seems to have fixed the Towny issues, but the error on startup still exist.
https://paste.ubuntu.com/p/sJTRVVbsNX/

**Comment by creatorfromhell** [comment]
> It seems to have fixed the Towny issues, but the error on startup still exist.
> https://paste.ubuntu.com/p/sJTRVVbsNX/

try deleting messages.yml and letting it regenerate.

**Comment by Caleston** [comment]
That fixes the error on startup. I reset all the configs to default, but now when attempting to use commands, it throws errors.
Its also telling me to use some /$registration command instead of /money commands, but such command does not exist.
https://paste.ubuntu.com/p/kNkhmhchZQ/

**Comment by creatorfromhell** [comment]
Interesting. Send over your commands.yml and messages.yml

**Comment by Caleston** [comment]
They're default. I generated them again to be sure, but same problem exists.
Here they are along with server log: https://paste.ubuntu.com/p/BMQBdSsVtj/
Apparently /t deposit does work and allowed me to deposit a bit of money. Economy database is also fresh.

**Comment by creatorfromhell** [comment]
Interesting, could you post your full server.lo? I'm not getting the same results on fresh install with towny 0.97.0.16.

**Comment by creatorfromhell** [comment]
Alright I've narrowed this down to what causes it. When the commands.yml is first created it results in this error, after stopping and starting the server again it goes back to normal.

**Comment by Caleston** [comment]
Damn, you're right. Plugin is working now with no errors.
Although the percentage commands are not functioning and it replies with "Parameter "$parameter" is of type parameter_type".

**Comment by creatorfromhell** [comment]
> Damn, you're right. Plugin is working now with no errors.
> Although the percentage commands are not functioning and it replies with "Parameter "$parameter" is of type parameter_type".

Yeah I realized that after I started testing it.
