### ISSUE TITLE
No change of bal on using MYSQL in combination of other server_name

### ISSUE THREAD

**Issue by ihateaccountssomuch** [TheNewEconomy/TNE-Bukkit#475]
**Problem**
when i purchase items via Chestshop or Quickshop, than the Money doesn't changes.

**Scenario**
Active Plugins:
```
Vault
ChestShop (or Quickshop)
TNE
```

Configs Changes:
```
Server:
	Name: "EOS"
Currency:
	Basic:
		Identifier: "BiM"
		Major_Single: "BiM"
		Major_Plural: "BiM"
		Minor_Single: ""
		Minor_Plural: ""
		Symbol: ""
		Virtual: ""
			BiM: 1
		Options:
			Format: "<major.amount> <symbol>"
			Balance: 250.0
			Decimal: ","
			Major_Separator: "."
	Database:
		Type: "MySQL"
		MySQL:
			SSL: true
			DB: "######"
			User: "######"
			Password: "######"
```

Hint: Server's Database is MariaDB

**Unexpected behaviors**
Money values where read from the user on server_name "EOS", then calculated, then written to the user in server_name "Main Server".
When I delete the server_name "Main Server" Entrys in the Database, it's appears after a purchase again in the Database.

**Test Scenario**
- User's Money is 20k (server_name "EOS", called "E")
- User's Money is 20k (server_name "Main Server", called "M")
- Testitem is worth 100, Stack 6.4k

```
Start with         E 20000 / M 20000
buy 1 item         E 20000 / M 19900
buy 1 item         E 20000 / M 19900
buy 1 item         E 20000 / M 19900
sell 1 item        E 20000 / M 21000
sell 1 item        E 20000 / M 21000
sell 1 item        E 20000 / M 21000

Restart with       E 20000 / M 20000
sell 1 item        E 20000 / M 21000
buy 1 item         E 20000 / M 19900

Restart with       E 20000 / M 20000
buy 1 stack items  E 20000 / M 13600
buy 1 stack items  E 20000 / M 13600
buy 1 stack items  E 20000 / M 13600
sell 1 stack items E 20000 / M 26400
sell 1 stack items E 20000 / M 26400
sell 1 stack items E 20000 / M 26400

Restart with       E 20000 / M 20000
sell 1 stack items E 20000 / M 26400
buy 1 stack items  E 20000 / M 13600
```

**Supposition** 
From where comes this "Main Server" DB Entry? Maybe there is something hardcoded with "Main Server" in the Database write function?
It dosn't fix the Problem, to change the config Server: Name: back to "Main Server", when you still have Entrys from other named servers in the Table for this user.

I finally tested the "circumnavigate":
```
Changed Config's Server: Name: to default "Main Server"
Restarted Server
Start with         E 20000 / M 20000
buy 1 stack items  E 20000 / M 13600
sell 1 stack items E 20000 / M 26400
Deleted "E" from database
buy 1 stack items            M 13600 ✓
buy 1 stack items            M  7200 ✓
buy 1 stack items            M   800 ✓
sell 1 stack items           M  7200 ✓
sell 1 stack items           M 13600 ✓
sell 1 stack items           M 20000 ✓
```

**Comment by creatorfromhell** [comment]
Is this still an issue with latest release?

**Comment by mojiansheng** [comment]
This problem is very serious. If it cannot be repaired, I will have to consider giving it up.

**Comment by mojiansheng** [comment]
> 这仍然是最新版本的问题吗？

yes.

**Comment by mojiansheng** [comment]
Caching
We now cache virtual currency balances to help with performance.

**Comment by mojiansheng** [comment]
0.1.1.14 is true
0.1.1.14+ is bad

**Comment by creatorfromhell** [comment]
> This problem is very serious. If it cannot be repaired, I will have to consider giving it up.

So the issue still persists with 0.1.1.17 pre 2?

**Comment by mojiansheng** [comment]
> > This problem is very serious. If it cannot be repaired, I will have to consider giving it up.
> 
> So the issue still persists with 0.1.1.17 pre 2?

I'm very sure

**Comment by mojiansheng** [comment]
0.1.1.17 pre 2 cannot create MySQL tables

**Comment by creatorfromhell** [comment]
> 0.1.1.17 pre 2 cannot create MySQL tables

Tested this locally, seems to work on my end, I would validate you have no startup errors.

Am looking into the server name issue.

**Comment by mojiansheng** [comment]
[TNE Beta 1.1.15](https://www.spigotmc.org/resources/the-new-economy.7805/update?update=435451)
As always, please backup your DB before updating.

Now updated for 1.18!!

Currency
Revamped currency conversion to the new system
Add config to allow starting with currency items in inventory.
Caching
We now cache virtual currency balances to help with performance.
Fixes
Fix issue where command selectors weren't being parsed
Fixed issue where materials class wasn't working for 1.18
If messages in messages.yml are empty we no longer send them
Updated to latest Reserve API
Outdated modules no longer crash TNE
Fixed an issue with TNE and Towny using item-based currencies

**Comment by mojiansheng** [comment]
Problem
when i purchase items via Chestshop or Quickshop, than the Money doesn't changes.

**Comment by mojiansheng** [comment]
[TNE Beta 1.1.15](https://www.spigotmc.org/resources/the-new-economy.7805/update?update=435451)
As always, please backup your DB before updating.

Now updated for 1.18!!

Currency
Revamped currency conversion to the new system
Add config to allow starting with currency items in inventory.
**Caching
We now cache virtual currency balances to help with performance.**
Fixes
Fix issue where command selectors weren't being parsed
Fixed issue where materials class wasn't working for 1.18
If messages in messages.yml are empty we no longer send them
Updated to latest Reserve API
Outdated modules no longer crash TNE
Fixed an issue with TNE and Towny using item-based currencies

**Comment by creatorfromhell** [comment]
> Problem when i purchase items via Chestshop or Quickshop, than the Money doesn't changes.

That's not what this ticket is in regards to. This ticket is for multiworld not simple money transactions... Also caching wouldn't affect balance changes as it's wrote to the DB when changed in the background. I would file a new ticket instead of piggy backing off one for something different.

**Comment by creatorfromhell** [comment]
Tested in the recode and seems to work as intended.
