### ISSUE TITLE
Error occurred while enabling TheNewEconomy v0.1.1.13

### ISSUE THREAD

**Issue by PappoYT** [TheNewEconomy/TNE-Bukkit#477]
#### What is the issue/bug you're experiencing?
Upgrading from 0.1.1.12 to 0.1.1.13 I get these errors during start-up:
`
[05:35:46] [Server thread/ERROR]: Error occurred while enabling TheNewEconomy v0.1.1.13 (Is it up to date?)
2176 | java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "com.hellyard.cuttlefish.grammar.yaml.YamlNode.getValues()" is null
`
`
[05:35:46] [Server thread/ERROR]: Error occurred while disabling TheNewEconomy v0.1.1.13 (Is it up to date?)
2196 | java.lang.NullPointerException: Cannot invoke "net.tnemc.libs.org.javalite.activejdbc.DB.hasConnection()" because "com.github.tnerevival.core.db.SQLDatabase.db" is null
`
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Download JAR from SpigotMC and put it in /plugins folder.
#### TNE version?(exact version number), and whether or not you've made modification to it.
TheNewEconomy v0.1.1.13
#### TNE build?(/tne build), and whether or not you've made modification to it.
Cannot use the command `/tne build`
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No modules.
#### Spigot/Bukkit version?
Paper 1.16.5 build 788
#### Is your server run in online mode?
online-mode=true
#### The exact command you ran w/ arguments?
nothing, the errors appear during start-up
#### Your latest server log file?(use http://paste.ubuntu.com)
https://mclo.gs/WPNos8Z
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
https://pastebin.com/AQMbrK06

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment]
Delete messages.yml and restart.
