### ISSUE TITLE
Latest TNE breaks all Skript/scripts

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [TheNewEconomy/TNE-Bukkit#478]
#### What is the issue/bug you're experiencing?
Breaks all Scripts from the Skript Addons, all errors started to happen once I updated to the newest release of TNE and all errors relate to TNE, even tho certain scripts r not even related to TNE.
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Install Skript and some addons, create Scripts, they will error on startup and not be usable
#### TNE version?(exact version number), and whether or not you've made modification to it.
0.1.1.13, latest release on SpigotMC
#### TNE build?(/tne build), and whether or not you've made modification to it.
[12:37:24 INFO]: You're currently running TNE build 0.1.1.13
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
Idk how to check? I made no changes anywhere, but entering my mysql data in data.yml and changing starting balance from 200 to 100.
#### Spigot/Bukkit version?
Paper 1.16.5, latest build
#### Is your server run in online mode?
Offlinemode for Bungee
#### The exact command you ran w/ arguments?
None
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://hastebin.com/tupunoxowi.yaml
#### Your latest server log file?(use http://paste.ubuntu.com)
https://hastebin.com/isuzetomoz.yaml
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)
-
Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.

**Comment by creatorfromhell** [comment]
Try this build
[TNE.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/7198948/TNE.zip)
:
