### ISSUE TITLE
jdbc Driver update and Feature request

### ISSUE THREAD

**Issue by JeffHD** [TheNewEconomy/TNE-Bukkit#479]
Hey since update to 1.17 there is a error message that says that the class com.mysql.jdbc.Driver is deprecated and the new class is com.mysql.cj.jdbc.Driver. It's not necessary to change since it manually registers the new class but u get an error every time u startup the server.
A feature that i would appreciate is that u could change the number of  the mysql pool size to scale it to personal needs.

**Comment by creatorfromhell** [comment]
> Hey since update to 1.17 there is a error message that says that the class com.mysql.jdbc.Driver is deprecated and the new class is com.mysql.cj.jdbc.Driver. It's not necessary to change since it manually registers the new class but u get an error every time u startup the server.
> A feature that i would appreciate is that u could change the number of the mysql pool size to scale it to personal needs.

The driver error is from a library used inside TNE and no updated version is available yet for Java 16. As for the feature I'll look at adding it in.

**Comment by creatorfromhell** [comment]
No longer an issue in the recode.
