### ISSUE TITLE
[BUG]: Cannot use /tne menu

### ISSUE THREAD

**Issue by KnightlyAssassin** [TheNewEconomy/TNE-Bukkit#485]
### TNE Version

BETA 1.1.14

### Spigot Version

1.17.1

### Your config.yml

https://pastebin.com/TjY0hzK4

### Your latest server log

https://pastebin.com/ycB51typ

### What part of TNE is the bug affecting?

Transactions

### Is your server using online mode?

Yes

### Bug description

When using "/tne menu" the message "Messages.command.tne tne" appears and nothing else happens.

When using "/acc" an internal server error occurs

Plugins:
Brewery
Builders-Utilities
ChestShop
Crackshot
dynmap
Essentials
FastChunkPregenerator
FastLeafDecay
Graves
LuckPerms
MCRealistic-2
NametagEdit
RPEngine
SiegeWar
TheNewEconomy
Towny
Vault
Wild
Worldborder
Worldedit

### How to reproduce

Fresh installation of TNE, along with the plugins above
attempt to do /tne menu
error should appear

**Comment by creatorfromhell** [comment]
This is from not using correct command Paramus. The message it's sending is a known issue with a separate issue being tracked via discord. The /acc command set is not released and hence why you're seeing the error, it's not meant for end user.
