### ISSUE TITLE
[BUG]: Tab Complete Displayname

### ISSUE THREAD

**Issue by AdrianJakubcik** [TheNewEconomy/TNE-Bukkit#490]
### TNE Version

0.1.1.14

### Spigot Version

Purpur 1.17.1

### Your config.yml

None

### Your latest server log

None

### What part of TNE is the bug affecting?

Other Plugin Support

### Is your server using online mode?

No

### Bug description

Whatever command from TNE I try to run the tab complete always offers me displayname for the <player> argument, which is not quite correct since entering that will produce a StackTrace because the displayname contains spaces. I tried to look into the settings of the plugin however, I didn't find any option regarding tab completion. I indeed do use ProtocolLib, ProtocolSupport, and LuckPerms. It's not an exception on the server just something I observed while using this plugin.

### How to reproduce

1. Fresh install TNE
2. Hop onto the server
3. Try to use any TNE command and watch the tab complete for the <player> part

**Comment by AdrianJakubcik** [comment]
![2021-12-16_12 49 11](https://user-images.githubusercontent.com/45712887/146368782-4f128d17-2832-4f4f-b0a0-13e3b7dc380b.png)

**Comment by AdrianJakubcik** [comment]
It does say TNE build 0.1.1.13 however, I've downloaded from the spigot page a version labeled as 0.1.1.14.

**Comment by creatorfromhell** [comment]
> It does say TNE build 0.1.1.13 however, I've downloaded from the spigot page a version labeled as 0.1.1.14.

a) you're using a build that's 2 releases out of date.
b) I'll update this with a pre release build in the discord

**Comment by creatorfromhell** [comment]
https://cdn.discordapp.com/attachments/788817936793468969/921039949657149470/TNE-0.1.1.17-PRE-1.jar
