### ISSUE TITLE
[BUG]: Server Thread freeze when doing anything economy-related while using MySQL

### ISSUE THREAD

**Issue by AlexanderOFGR** [TheNewEconomy/TNE-Bukkit#491]
### TNE Version

0.1.1.16

### Spigot Version

1.18.1

### Your config.yml

https://pastebin.com/0RPdMgGK

### Your latest server log

https://pastebin.com/sZyyYY8E

### What part of TNE is the bug affecting?

Other Plugin Support

### Is your server using online mode?

No

### Bug description

When using a economy command, executing a economy operation, the server freezes for some seconds. I am using MySQL to store all the economy data, that way I can sync the data across multiple servers. This problem does not exist when mysql is not in use and i use h2, but this way, i can't get the plugin to work how I intend to (multi-server eco)...

### How to reproduce

1. Go to /plugins/TheNewEconomy/data.yml
2. Change "Type" from H2 to MySQL and connect the plugin to a MySQL database
3. Restart the server
4. Try and give money, take money, execute a transaction

Note: I am using a mysql server on the same network as my game servers, so there is under 2ms latency (pinging the server shows ~1ms)

**Comment by creatorfromhell** [comment]
Have you tried this utilizing the latest release? Also, have you tried using TNE-provided commands not essentials provided ones? In your log you're using a command from essentials instead of /money give in TNE.

**Comment by AlexanderOFGR** [comment]
I am on 0.1.1.17-Pre-2 (the plugin shows 0.1.1.16)

Transactions are also slow through the plugin's commands (/money). Also, when i am using the /shop command from another plugin, since it has to get the balance from TNE before showing the menu, it freezes the server for some seconds.

**Comment by creatorfromhell** [comment]
> 

Are you using virtual or item-based currencies?

**Comment by AlexanderOFGR** [comment]
I am using virtual currencies

**Comment by creatorfromhell** [comment]
> I am using virtual currencies

Alright, thanks for the information I will have a look at this now and provide a test build when possible!

**Comment by AlexanderOFGR** [comment]
Okay! Thanks a lot for helping out! Have a great day/night!

**Comment by AlexanderOFGR** [comment]
Just noticed: I switched to h2 and the problem still exists. Is essentials causing issues with TNE or it works just fine? I am asking this because essentials has it's own economy system built in or is it because i updated to the build with Bungee Support (TNE)?

**Comment by creatorfromhell** [comment]
> Just noticed: I switched to h2 and the problem still exists. Is essentials causing issues with TNE or it works just fine? I am asking this because essentials has it's own economy system built in or is it because i updated to the build with Bungee Support (TNE)?

It's when a new player joins correct? I.e. a player that doesn't have an account already? Also could you provide timings?

**Comment by AlexanderOFGR** [comment]
Any economy-based action (like Economy Placeholders, Sending Money, Adding money to a player account) cause the server to be unresponsive for some seconds. Should I send a timings report when executing a command like /shop from EconomyShopGUI? Just managed to crash my server by spamming the /shop command lol

**Comment by AlexanderOFGR** [comment]
Here is the timings report when the server crashed: https://timings.aikar.co/?id=819603fda72f48a6be45b82c8074703d

**Comment by creatorfromhell** [comment]
> Here is the timings report when the server crashed: https://timings.aikar.co/?id=819603fda72f48a6be45b82c8074703d

log from the crash? also "It's when a new player joins correct? I.e. a player that doesn't have an account already?" is it happening with a player that has no previous economy account?

**Comment by AlexanderOFGR** [comment]
Here is the crash logs: https://pastebin.com/Edbm2tD0

Tested with a player that has never been in the server before and the same thing happens. They are trying to do anything economy related and the server hangs for all the players online...

**Comment by creatorfromhell** [comment]
Here's a build I've tested with essentials on my test server spamming their economy commands repeatedly couldn't get a crash with it. https://cdn.discordapp.com/attachments/420493055657902091/922147026563649546/TNE-0.1.1.17-PRE-3.jar

**Comment by AlexanderOFGR** [comment]
I am using this one, removed the plugin and it's configuration files and i will install it again

**Comment by creatorfromhell** [comment]
> I am using this one, removed the plugin and it's configuration files and i will install it again

I just compiled this before testing so it can't be in use already....

**Comment by AlexanderOFGR** [comment]
Sooo... It seems like this version actually fixed it.. After removing all the plugin's config files and reinstalling it, i connected it to my MySQL server and everything seems to be working fine. I will let you know if something breaks 😄

**Comment by creatorfromhell** [comment]
Cheers.
