### ISSUE TITLE
[BUG]: Currencies not working

### ISSUE THREAD

**Issue by Grievous07** [TheNewEconomy/TNE-Bukkit#493]
### TNE Version

TNE build 0.1.1.17-PRE-2

### Spigot Version

1.18.1

### Your config.yml

https://pastebin.com/Tj8PCQCa

### Your latest server log

https://pastebin.com/snZAkzbe

### What part of TNE is the bug affecting?

Other Plugin Support

### Is your server using online mode?

Yes

### Bug description

https://pastebin.com/szRUYuKL
All my advanced currencies look like this but with the identifier and worlds changed.

https://pastebin.com/emt1Bin3
^ Minor Currency ^
https://pastebin.com/8V5GJJ0W
^ Minor Currency ^

### How to reproduce

try to do /balance

**Comment by creatorfromhell** [comment]
Post configs of every currency.

**Comment by creatorfromhell** [comment]
Also, post a picture of your worlds folders.

**Comment by Grievous07** [comment]
https://pastebin.com/szRUYuKL
^ Adventure World Currency ^
https://pastebin.com/C2bREXUv
^ Creative World Currency ^
https://pastebin.com/1L0qEHex
^ Earth World Currency ^
https://pastebin.com/K1YTCsyd
^ Faction World Currency ^
https://pastebin.com/mtXxSFG3
^ Hardcore World Currency ^
https://pastebin.com/eDLu0RcR
^ Skyblock World Currency ^

![image](https://user-images.githubusercontent.com/18214761/149676781-70e8236b-2cd2-477d-b925-da8843c6ec15.png)
![image](https://user-images.githubusercontent.com/18214761/149676792-3b150071-5dd0-46c0-ac91-8f2a78e504f3.png)

**Comment by creatorfromhell** [comment]
From the discord "also turn on TNE debug and post that log
i.e. stop, change debug to true then start"

**Comment by Grievous07** [comment]
https://mcpaste.io/225245f0ac0cc668
^ That's the console ^

https://mcpaste.io/072588573cda2957
And console again

**Comment by creatorfromhell** [comment]
Full debug log from startup to finish

**Comment by Grievous07** [comment]
https://mcpaste.io/fcf70d75b024114d
So did the /tne debug, restarted, then tried to do abunch of commands.

**Comment by creatorfromhell** [comment]
I'm not looking for the /the debug, I'm looking for the server stopped, config setting debug to be set to true, then restarted to give me the full debug log of TNE loading. The commands don't tell me anything more than what we know already.

**Comment by Grievous07** [comment]
https://mcpaste.io/def4c7c01736a30a
Apologies, here ya go.

**Comment by creatorfromhell** [comment]
> https://mcpaste.io/def4c7c01736a30a Apologies, here ya go.

So a lot of it was cut off but this is the reason for your issues. You havent configured them correctly basedon this part of your log:

33:18 [Server] WARN Directory currencies/Skyblock does not exist.
17.01 16:33:19 [Server] WARN Directory currencies/Earth does not exist.
17.01 16:33:19 [Server] WARN Directory currencies/Creative does not exist.
17.01 16:33:19 [Server] WARN Directory currencies/Adventure does not exist.
17.01 16:33:19 [Server] WARN Directory currencies/Factions does not exist

Each currency should have a directory as outlined in the wiki.

**Comment by Grievous07** [comment]
I'll see if I can get the full report. Cause I've reviewed my currency and it seems accurate to as it should be.

**Comment by creatorfromhell** [comment]
> I'll see if I can get the full report. Cause I've reviewed my currency and it seems accurate to as it should be.

Zip your currencies directory and send it over.

**Comment by Grievous07** [comment]
[pebblehost-149320-prhccw.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/7884956/pebblehost-149320-prhccw.zip)
[pebblehost-149320-prhccw.zip](https://github.com/TheNewEconomy/TNE-Bukkit/files/7884957/pebblehost-149320-prhccw.zip)

**Comment by creatorfromhell** [comment]
The currency configurations are incorrect. Each currency requires a directory with the tiers.

**Comment by Grievous07** [comment]
? I searched for word "directory" and "tiers" in all my files, but couldn't find such
