### ISSUE TITLE
[BUG]: When using bungeerecord, multiple servers cannot synchronize in time

### ISSUE THREAD

**Issue by mojiansheng** [TheNewEconomy/TNE-Bukkit#496]
### TNE Version

0.1.1.17-Pre-2

### Spigot Version

1.18.1

### Your config.yml

http://52mc.top:808/nextcloud/index.php/s/jqjPEECkZ9JBWdM/download/config.yml

### Your latest server log

http://52mc.top:808/nextcloud/index.php/s/t6iqP2Czfe2xPjC/download/latest.log

### What part of TNE is the bug affecting?

Other Plugin Support

### Is your server using online mode?

No

### Bug description

I use bungeecord
1. When I get 500 from server a, I query the balance, and the balance is 500;
2. At this time, I send it to server B, and after querying the account, I find that my balance is 0;
3. I shut down the B server, started it again and entered the B server to query the balance. The balance is 0;
4. After I shut down server a, I entered server B to query the balance, which was 500
How can I do this? After server a obtains 500, I enter server B to query that the balance is also 500 (I don't quit bungeerecord during this period)
I didn't install tne in bungeecord.

### How to reproduce

1. You need to prepare a bungeerecord and two spot servers
2. Install tne and luckperms on the spot server
3. Set the player balance using the command on server a
4. Enter server B without shutting down server a
5. Query balance

**Comment by mojiansheng** [comment]
0.1.1.14 is true
0.1.1.14+ is bad

**Comment by mojiansheng** [comment]
MYSQL version 8.0.12

**Comment by creatorfromhell** [comment]
This won't let me see your config.yml or latest.log, please use pastebin or a paste website. Also include both configurations and both startup logs for each server.

**Comment by mojiansheng** [comment]
> This won't let me see your config.yml or latest.log, please use pastebin or a paste website. Also include both configurations and both startup logs for each server.

I won't use this thing. You can download the link I give directly without looking at the config and log

**Comment by mojiansheng** [comment]
<script src="https://pastebin.com/embed_js/U9H5MMZX"></script>

**Comment by mojiansheng** [comment]
https://pastebin.com/raw/U9H5MMZX

**Comment by creatorfromhell** [comment]
> https://pastebin.com/raw/U9H5MMZX

Ok and what version of TNE Bungee cord is installed on your bungee cord server?

**Comment by mojiansheng** [comment]
waterfull

**Comment by mojiansheng** [comment]
Does bungeercord also need to be installed? I didn't find the plugin.

**Comment by mojiansheng** [comment]
Is it the same file as that in spot?

**Comment by creatorfromhell** [comment]
> > 
> 
> I don't understand

There is a plugin for the spigot/paper server then one for waterfall/bungee to share balances across servers. Obviously the waterfall/bungee one is not installed. I.em it's not a TNE bug it's just it's not installed.

**Comment by mojiansheng** [comment]
> > > 
> > 
> > 
> > I don't understand
> 
> There is a plugin for the spigot/paper server then one for waterfall/bungee to share balances across servers. Obviously the waterfall/bungee one is not installed. I.em it's not a TNE bug it's just it's not installed.

Where can I download it? I don't see any introduction in the wiki

**Comment by creatorfromhell** [comment]
> > > > 
> > > 
> > > 
> > > I don't understand
> > 
> > 
> > There is a plugin for the spigot/paper server then one for waterfall/bungee to share balances across servers. Obviously the waterfall/bungee one is not installed. I.em it's not a TNE bug it's just it's not installed.
> 
> Where can I download it? I don't see any introduction in the wiki

https://cdn.discordapp.com/attachments/788817936793468969/921553674742952007/TNE-Bungee-1.0.0-PRE-1.jar

**Comment by mojiansheng** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I don't understand
> > > 
> > > 
> > > There is a plugin for the spigot/paper server then one for waterfall/bungee to share balances across servers. Obviously the waterfall/bungee one is not installed. I.em it's not a TNE bug it's just it's not installed.
> > 
> > 
> > Where can I download it? I don't see any introduction in the wiki
> 
> https://cdn.discordapp.com/attachments/788817936793468969/921553674742952007/TNE-Bungee-1.0.0-PRE-1.jar

I installed it, but I still can't

**Comment by creatorfromhell** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > I don't understand
> > > > 
> > > > 
> > > > There is a plugin for the spigot/paper server then one for waterfall/bungee to share balances across servers. Obviously the waterfall/bungee one is not installed. I.em it's not a TNE bug it's just it's not installed.
> > > 
> > > 
> > > Where can I download it? I don't see any introduction in the wiki
> > 
> > 
> > https://cdn.discordapp.com/attachments/788817936793468969/921553674742952007/TNE-Bungee-1.0.0-PRE-1.jar
> 
> I installed it, but I still can't

This is correctly working when I test it locally, must be a configuration issue. Recheck your configuration appropriately

**Comment by mojiansheng** [comment]
This problem still hasn't been solved. Won't the corresponding configuration file be generated on BC,

**Comment by creatorfromhell** [comment]
> This problem still hasn't been solved. Won't the corresponding configuration file be generated on BC,

No, each server has to be configured appropriately
