### ISSUE TITLE
[BUG]: Commands & Transactions are heavily delayed

### ISSUE THREAD

**Issue by Castafers** [TheNewEconomy/TNE-Bukkit#499]
### TNE Version

0.1.1.17-PRE-2

### Spigot Version

1.18

### Your config.yml

https://pastebin.com/g9rB5sUj

### Your latest server log

https://pastebin.com/5M6jZSnz

### What part of TNE is the bug affecting?

Transactions, Other Plugin Support

### Is your server using online mode?

Yes

### Bug description

ANY command that has to do with checking, or changing any currency. This includes anything that actually checks for changes or does changes, such as the player gaining or losing currency.

Whenever any of this happens ^

There is a delay from 1 to 5 seconds long between each change.

(I tried this with H2 & MySQL databases)

### How to reproduce

Install TNE

Use my config

Play on the server, and experience the massive delay

**Comment by creatorfromhell** [comment]
Timings report?

**Comment by heuerleon** [comment]
I also experience delays when doing transactions. This only appears to happen after making a transaction once after a while, but further transactions in a short period of time seem to work for me.

**Comment by creatorfromhell** [comment]
Seems like this issue has been corrected in the recode that I'm currently testing.
