### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by creatorfromhell** [TheNewEconomy/TNE-Bukkit#50]
The functionality to save, and then allow server owners/permissible users to browse previous transactions should be implemented to better allow for more specialized moderation.

What should be tracked? Everything.
This includes, but is not limited to:
Shop sales, purchases,  and trades,
Money given using the give command,
Money paid to other players,
Bank withdrawal/deposit history,
Money earned and how it was earned(killing mobs, etc),
Money spent and how it was spent(crafting items, brewing potions, etc)

**Comment by Oruss7** [comment]
Must Have :) ChestShop transactions will be logged too ?

**Comment by creatorfromhell** [comment]
Short answer, yes. Long answer, the new transaction system introduced in Alpha 3.0 makes it as simple as calling a method. It also allows for adding more transaction types in the future with ease.
