### ISSUE TITLE
When Conversion-0.0.1.4.jar place in modules folder TNE wont loaad

### ISSUE THREAD

**Issue by txtrapline** [TheNewEconomy/TNE-Bukkit#500]
### TNE Version

TNE-0.1.1.17-PRE-2.jar & TNE-0.1.1.17-PRE-3.jar

### Spigot Version

1.18.2

### Your config.yml

https://pastebin.com/qUrZcvCY

### Your latest server log

https://bin.bloom.host/waxijabayu

### What modules are you using?

Conversion

### What part of TNE is the bug affecting?

Won't Startup

### Is your server using online mode?

No

### Bug description

When Conversion-0.0.1.4.jar is placed in the modules folder TNE won't load. /tne /convert commands aren't recognized and no welcome message.

### How to reproduce

Install latest prerelease and drop conversion in the modules folder.

**Comment by creatorfromhell** [comment]
The conversion module you're attempting to use is outdated, use the one located on the discord.
