### ISSUE TITLE
[BUG]: Transaction issues causes TPS drop

### ISSUE THREAD

**Issue by Mattew31** [TheNewEconomy/TNE-Bukkit#503]
### TNE Version

0.1.1.17-PRE-2

### Spigot Version

1.17.1

### Your config.yml

https://pastebin.com/Mqi9uCqt

### Your latest server log

https://pastebin.com/Vx8R87hk

### What modules are you using?

Conversion

### What part of TNE is the bug affecting?

Transactions

### Is your server using online mode?

Yes

### Bug description

When you try to set a player's balance or if you try to add money it takes like 5 seconds for it to go through. Then, it drops the server TPS down to 12-14.

### How to reproduce

1. Have EssentialsX installed
2. Have Vault installed
3. have TNE installed
4. Run the command /economy give <player> <amount> OR DO /money give <player> <amount>

**Comment by creatorfromhell** [comment]
Try using the TNE command /money give.

**Comment by Mattew31** [comment]
I tried and it still did the same thing, and also I found another bug. It doesn't add the letter after the number (e.g. 2.4k).

**Comment by creatorfromhell** [comment]
Fixed in recode.
