### ISSUE TITLE
[FEAT]: Collecting Taxes

### ISSUE THREAD

**Issue by ChatpKSK** [TheNewEconomy/TNE-Bukkit#504]
### Feature Description

A module for taxes collecting from players’ balances.

### 1. Collecting Taxes

Able to collect taxes in the scheduled times.

### 2. Offline Taxes Collecting

Able to collect taxes even when the player is offline.

### 3. Fully Customizable 

- Separating tax collecting group such as from all players, group permission, etc.
- Separating the currency for the tax collection
- Able to choose between Fixed and Percent type of tax collecting
- Able to set the tax collecting method to Progressive Tax
- Set an account for collecting money from tax collection.
- Able to set intervals for tax collection in day, hour, minute, and second unit.
- Able to set a delay (Batch Processing) to decrease impacts on the performance.
- Have a notification system when collecting taxes such as tax total, tax percentage, remaining balance, or set the placeholder for a manual customization. 
- Run other commands when collecting taxes.
- Saving log files for every tax collecting transactions such as time, username, UUID, total of tax collection, remaining balance (Collecting each log separately)

### Reasoning

This is very essential for the server that needs a balance in the economic system to prevent the inflation. Actually, these ideas are from **Taxes plugin in Spigot**. It is a good plugin and it can be used as a guide for the requested one but it has abandoned for a long time so it can’t be used with the latest version (and maybe not compatible with TNE also).

**Comment by creatorfromhell** [comment]
Looking over this for the recode that is happening.. What happens if the player is unable to pay their taxes?

**Comment by creatorfromhell** [comment]
Moved to recode repository.
