### ISSUE TITLE
[BUG]: data can't sync in different server

### ISSUE THREAD

**Issue by mojiansheng** [TheNewEconomy/TNE-Bukkit#509]
### TNE Version

0.1.1.17-Pre-2

### Spigot Version

paper1.19

### Your config.yml

http://52mc.top:5879/config.yml

### Your latest server log

http://52mc.top:5879/latest.log

### What part of TNE is the bug affecting?

Transactions

### Is your server using online mode?

No

### Bug description

Does anyone use this plug-in on BC
The number of currencies of server a and server B are different

### How to reproduce

A BC
TWO paper1.19(serve A,server B)
mysql8.0
player A is op
1.player A have money 500.He use command "/money give A 1" at server A
2.He use command "/money balance" at server A.He can see He have money 501
3.He tp server B.He use command "/money balance" at server B.He can see He have money 500
4.restart server B.player A joined server B,He use command "/money balance" at server B.He can see He have money 501
what's happen?500?why not 501?

**Comment by creatorfromhell** [comment]
Alright so I finally go to the bottom of this.. this seems to be a limitation implemented by spigot/minecraft
so apparently plugin channels don't allow messaging to a server when there are no players online, i.e. if you have no players on the one server it won't send the update.

**Comment by mojiansheng** [comment]
Looking forward to repair.
