### ISSUE TITLE
[BUG]: WHY DO YOU GET THE PLAYER'S UUID BY THE INTERNET 

### ISSUE THREAD

**Issue by ClayCoffee** [TheNewEconomy/TNE-Bukkit#510]
### TNE Version

0.1.1.16

### Spigot Version

1.18.2

### Your config.yml

！

### Your latest server log

！

### What part of TNE is the bug affecting?

Transactions

### Is your server using online mode?

Yes

### Bug description

WHY DO YOU GET THE PLAYER'S UUID BY THE INTERNET 
THIS CAUSES SUDDEN TPS DROP

### How to reproduce

~

**Comment by ClayCoffee** [comment]
https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/TNE/src/net/tnemc/core/common/uuid/UUIDAPI.java
WHY?

**Comment by creatorfromhell** [comment]
The class you're referencing is a fallback system that is used as a last resort if spigot has no data for the specified player. However, spigot's alternative method also uses the web request for UUIDs. This is all seen in the IDFinder class, which you'll notice utilizes the spigot method first. Also, as a side note, professional dialogue should be utilized in these issues. However, you are also free to make a PR for a change if you have a method that doesn't utilize the spigot internals, which also defaults to the Mojang web API.

**Comment by creatorfromhell** [comment]
Closing this now as I've updated the system in the r code repository to utilize a different strategy and deny any transactions or kick players whose uuid cannot be found without a web request.
