### ISSUE TITLE
[BUG]:  Command /currency generates error

### ISSUE THREAD

**Issue by ConaII** [TheNewEconomy/TNE-Bukkit#516]
### TNE Version

TNE-0.1.1.17-PRE-2.jar

### Spigot Version

1.17.1

### Your config.yml

https://pastebin.com/HxBj1YiN

### Your latest server log

https://pastebin.com/ZQB4rq7v

### What part of TNE is the bug affecting?

Transactions

### Is your server using online mode?

Yes

### Bug description

When using /currency editor, an error appears

### How to reproduce

1. Try using /currency editor

**Comment by creatorfromhell** [comment]
/currency command set is not intended for use currently and a release will be made to remove it until the recode release.
