### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by haxbob12345** [TheNewEconomy/TNE-Bukkit#517]
### TNE Version

0.1.1.17-PRE-2

### Spigot Version

1.17.1

### Your config.yml

https://pastebin.com/d22WLCDp

### Your latest server log

Can't upload

### What part of TNE is the bug affecting?

Transactions, Other Plugin Support

### Is your server using online mode?

Yes

### Bug description

When a bedrock player (Geyser with floodgate) buys from a shop (quickshop remake), the transaction goes through but when the transaction completed, the shop owner gets the gold, but the bedrock player who bought from the shop also kept the gold and basically causing a dupe.

### How to reproduce

1. Have TNE, Quickshop, Geyser and Floodgate installed on the server.
2. Join the server with both Bedrock and Java Accounts
3. Make a shop using quickshop
4. Complete a transaction to the shop using the bedrock account
5. Check if both accounts have the gold.

Use the config used above

**Comment by creatorfromhell** [comment]
There's been quite a few strange things with geyser users.. I wouldn't recommend utilizing TNE on geyser. This is an issue I've highlighted to test on the recode.

**Comment by haxbob12345** [comment]
I currently have a server using an item based currency along wiht bedrock players and I don't want to eliminate the whole bedrock player base.

**Comment by creatorfromhell** [comment]
> I currently have a server using an item based currency along wiht bedrock players and I don't want to eliminate the whole bedrock player base.

As stated above I'm going to have a look at geyser support with the recode so we will see what happens as I'm not entirely sure what geyser does internally that could cause it.

**Comment by haxbob12345** [comment]
When is an estimated time you think you can get a solution?

**Comment by creatorfromhell** [comment]
Well I have no eta on the recode release.

**Comment by creatorfromhell** [comment]
This has been validated as working in the recode now.
