### ISSUE TITLE
[FEAT]: Please add a way to customise the note item.

### ISSUE THREAD

**Issue by MeDavoo** [TheNewEconomy/TNE-Bukkit#519]
### Feature Description

Please add a way to customise the note item (lore, description, title, enchanted glow or not) im begging ;-;

### Reasoning

would make it look way better PLS

**Comment by creatorfromhell** [comment]
There's some leeway with it already, I'll look add the lore options. https://github.com/TheNewEconomy/TNE-Bukkit/blob/49154b9f345d94b8e282c264b919000730507549/TNE/src/net/tnemc/resources/config.yml#L245

**Comment by MeDavoo** [comment]
🙏🏼 ty ur a king
