### ISSUE TITLE
Plugin Documentation

### ISSUE THREAD

**Issue by creatorfromhell** [TheNewEconomy/TNE-Bukkit#54]
Documentation for using TNE is a bit sparse at this point in time. A video should be created on installation, basic features, and more.

**Comment by Oruss7** [comment]
Videos are great, but not quick to find somethings. 

I suggest to make a "/doc" repo on your project source (with .md file as README.md) and when you add/edit something, you update the doc in the same commit. For users, it ensure doc is up-to-date with the plugin version (if you tag each version of course).

You can see https://github.com/slipcor/pvparena plugin, i import myself the documentation and now everybody is happy =)
