### ISSUE TITLE
Multi World Support Brocken/Non-existent. Please add.

### ISSUE THREAD

**Issue by tomtehtom** [TheNewEconomy/TNE-Bukkit#56]
I have looked at the worlds.yml on github and it has shared options but the generated configuration does not. Please fix/add support for multiple worlds with multiple shared worlds. This is how it should be done. But even if the worlds.yml worked it would only support 1 extra shared world so I have compensated by adding a share for each world. Here is what I want.
InPrison:
- Prison
- PrisonPlots
OutPrison:
- PrisonFree
- world_nether
- world_the_end
Hub:
- Spawn
Skyblock:
- SkyBlock
- SkyBlock_nether

Here is what I have and still nothing with shared worlds works. All it does is seperate every single world from every other one.

`# The New Economy v0.0.2.4
# Author: creatorfromhell
# License: AGPLv3
# If you would like to contribute to the plugin
# you can do so via Github at https://github.com/TheNewEconomy/TNE-Bukkit

Worlds:
  Prison:
    ChangeFee: 0.0
    Balance: 0.0
    Shorten: true
    ShareAccounts: true
    ShareWorld: PrisonPlots
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Bank:
      Enabled: false
      Sign: false
      Command: true
      NPC: false
      Cost: 20.0
      Rows: 3
      Interest:
        Enabled: false
        Rate: 0.2
  PrisonPlots:
    ChangeFee: 0.0
    Balance: 0.0
    Shorten: true
    ShareAccounts: true
    ShareWorld: Prison
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Bank:
      Enabled: false
      Sign: false
      Command: true
      NPC: false
      Cost: 20.0
      Rows: 3
      Interest:
        Enabled: false
        Rate: 0.2
  PrisonFree:
    ChangeFee: 0.0
    Balance: 0.0
    Shorten: true
#Whether or not you want this world to share accounts with another
    ShareAccounts: true
#The world to share accounts with if ShareAccounts is true
    ShareWorld: world_nether
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Bank:
      Enabled: false
      Sign: false
      Command: true
      NPC: false
      Cost: 20.0
      Rows: 3
      Interest:
        Enabled: false
        Rate: 0.2
  world_nether:
    ChangeFee: 0.0
    Balance: 0.0
    Shorten: true
#Whether or not you want this world to share accounts with another
    ShareAccounts: true
#The world to share accounts with if ShareAccounts is true
    ShareWorld: PrisonFree
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Bank:
      Enabled: false
      Sign: false
      Command: true
      NPC: false
      Cost: 20.0
      Rows: 3
      Interest:
        Enabled: false
        Rate: 0.2
  world_nether:
    ChangeFee: 0.0
    Balance: 0.0
    Shorten: true
#Whether or not you want this world to share accounts with another
    ShareAccounts: true
#The world to share accounts with if ShareAccounts is true
    ShareWorld: world_the_end
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Bank:
      Enabled: false
      Sign: false
      Command: true
      NPC: false
      Cost: 20.0
      Rows: 3
      Interest:
        Enabled: false
        Rate: 0.2
  world_the_end:
    ChangeFee: 0.0
    Balance: 0.0
    Shorten: true
#Whether or not you want this world to share accounts with another
    ShareAccounts: true
#The world to share accounts with if ShareAccounts is true
    ShareWorld: world_nether
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Bank:
      Enabled: false
      Sign: false
      Command: true
      NPC: false
      Cost: 20.0
      Rows: 3
      Interest:
        Enabled: false
        Rate: 0.2
  Spawn:
    ChangeFee: 0.0
    Balance: 0.0
    Shorten: true
#Whether or not you want this world to share accounts with another
    ShareAccounts: false
#The world to share accounts with if ShareAccounts is true
    ShareWorld: PrisonPlots
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Bank:
      Enabled: false
      Sign: false
      Command: true
      NPC: false
      Cost: 20.0
      Rows: 3
      Interest:
        Enabled: false
        Rate: 0.2
  Skyblock:
    ChangeFee: 0.0
    Balance: 0.0
    Shorten: true
#Whether or not you want this world to share accounts with another
    ShareAccounts: true
#The world to share accounts with if ShareAccounts is true
    ShareWorld: Skyblock_nether
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Bank:
      Enabled: false
      Sign: false
      Command: true
      NPC: false
      Cost: 20.0
      Rows: 3
      Interest:
        Enabled: false
        Rate: 0.2
  Skyblock_nether:
    ChangeFee: 0.0
    Balance: 0.0
    Shorten: true
#Whether or not you want this world to share accounts with another
    ShareAccounts: true
#The world to share accounts with if ShareAccounts is true
    ShareWorld: Skyblock
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Dollar
        Plural: Dollars
      MinorName:
        Single: Cent
        Plural: Cents
    Bank:
      Enabled: false
      Sign: false
      Command: true
      NPC: false
      Cost: 20.0
      Rows: 3
      Interest:
        Enabled: false
        Rate: 0.2
`

**Comment by creatorfromhell** [comment]
Currently the ShareAccounts feature is in the Gothic worlds.yml because it's a planned feature for Alpha 3.0. Currently multi-world support doesn't allow for account sharing

**Comment by creatorfromhell** [comment]
Closing due to specified issue being related to a future feature that isn't in any officially released/support version.
