### ISSUE TITLE
[Feature] /pay

### ISSUE THREAD

**Issue by Oruss7** [TheNewEconomy/TNE-Bukkit#64]
Hi Daniel,

Amazing plugin you made!

I ask you a little feature, can you add /pay commande as alias for /money pay please ?
I have essentials eco and need a plugin for multi-world support. Players use /pay

Thank you

**Comment by creatorfromhell** [comment]
Will definitely look into this when I get home, but I don't see why it can't be done.

**Comment by Oruss7** [comment]
Great, thanks. Also, /bal (/balance) return essentials too instead of The New Economy

**Comment by creatorfromhell** [comment]
we use /money, but it should also be stated that this can be modified via 3rd party plugins.

**Comment by Oruss7** [comment]
Ok, /balance show me vault =TNE, I understand =)

**Comment by quiquelhappy** [comment]
hello, did this ever get implemented? I can't use /pay on 1.18, I have to use /money pay
