### ISSUE TITLE
[Error] Catch bad format for decimals values

### ISSUE THREAD

**Issue by Oruss7** [TheNewEconomy/TNE-Bukkit#65]
Hi,

In france, we use `,` to separate decimals (ex: 10,99€). But The New Economy use `.`
When we attempts to use `,`, an error is throw on the console instead of catch by you.

That's not an urgent fix, but it's more appreciable to have a error message from plugin =)

**Comment by creatorfromhell** [comment]
This is not handles appropriately because it hasn't really been an issue, plus I was planning on allowing server owners to configure what they use in place of a decimal(in need be).

**Comment by Oruss7** [comment]
Perfect. Let me known when the config is ser :)
