### ISSUE TITLE
[Questions] Somes question about TNE

### ISSUE THREAD

**Issue by Oruss7** [TheNewEconomy/TNE-Bukkit#66]
- Can i with console command give money for a specific world ?
(If player are on world2, i want give him 100$ on the world1)

- Is minor mandatory ? Can i disable minor for a specific world ?

- How work interests ? Is configurable per world ? Is every days or every hours ?

- As OP, is exist an command to set player balance ? I see give/take but not set ?

Thanks you!

**Comment by creatorfromhell** [comment]
1. Not being able to give money to a player's balance for a specific world is something that was apparently overlooked when multi-world support was added in. I'm actually surprised nobody else, nor myself, noticed this earlier. This will definitely be added though.
2. Minor displayed from the plugin is mandatory, but you don't have to add a minor amount in commands do /money pay 50.00, you could do /money pay 50 and it'll work fine.
3 Interest is configured by seconds as seen here: https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/config.yml#L198. It is not configurable per world, but this will most likely change soon. I plan to make all configurations per-world.
4. A set balance command is definitely something that could be added for administrative purposes.

**Comment by Oruss7** [comment]
Thank you for your quick response.  Thats's an excellent work !
