### ISSUE TITLE
Disabling Shops

### ISSUE THREAD

**Issue by Carisus** [TheNewEconomy/TNE-Bukkit#69]
Instead of [sending a message that shops are disabled](https://github.com/TheNewEconomy/TNE-Bukkit/blob/780f70d6c7e447477eb7e88d5d3ece3fbf71426a/src/com/github/tnerevival/commands/shop/ShopCommand.java#L66), can we just let the command pass by? This will release the /shop command for other plugins. I know I could use the commands.yml to choose which plugin actually gets the command, but it seems better to just let the command go. 

Another option would be to ask if we are using some other shop plugin, and then release if true. 

Either way, taking control of a command we aren't going to use doesn't seem like the best way to go.

**Comment by Carisus** [comment]
The shop command still isn't being let go. It is probably the plugin.yml registering it on load. I am currently overriding it in the commands.yml, but with as many servers as we will be running this will get difficult to keep track of.

**Comment by creatorfromhell** [comment]
Hmm, this means that commands will have to be dynamically registered with reflection.. I'm very interested in this idea.
