### ISSUE TITLE
/pay and /money pay not working

### ISSUE THREAD

**Issue by Oruss7** [TheNewEconomy/TNE-Bukkit#79]
I use TNE alpha 3.3 (spigot), when i use pay commands, i have only `/pay <player> <amount>` message display.

I try with /money pay test1 2.0, /money pay test1 2 and /pay test1 2.0 as OP with permission node also ^^

Thanks

**Comment by Oruss7** [comment]
But /bal now display same as /money \o/

**Comment by creatorfromhell** [comment]
I use TNE alpha 3.3 (spigot), when i use pay commands, i have only /pay <player> <amount> message display.
- Not sure what you mean here, but everything seems to be working on my end

But /bal now display same as /money \o/
- As expected :P

/money give don't working too
- What's not working about it? Any messages displayed?

**Comment by creatorfromhell** [comment]
Everything seems to be working(not sure if it had anything to do with the new command changes added post 3.3).
