### ISSUE TITLE
Advanced Currency Formatting

### ISSUE THREAD

**Issue by creatorfromhell** [TheNewEconomy/TNE-Bukkit#83]
The main feature we'll be gaining form this is the ability to add currency symbols. As a whole, however, this will allow us to put the formatting into a single method, cleanup the formatting methods, and allow server owners even more control over their economy.

Example:
```
Balance is currently 1200.02

CurrencyFormat: {currency.symbol}{currency.major}{shorten=true}
Result: $1k Dollars

CurrencyFormat: {currency.major}{shorten=true}
Result: 1k Dollars

CurrencyFormat: {currency.symbol}{currency.major}{currency.decimal}{currency.minor}{shorten=false}
Result: $1200,02 Dollars

CurrencyFormat: {currency.symbol}{currency.major}{currency.decimal}{currency.minor}{shorten=true}
Result: $1,2k Dollars
```

**Comment by Eredrim** [comment]
Excellent ! A very good idea this expression system to define currency 👍

**Comment by creatorfromhell** [comment]
17f0482c5e53dbeb16873afae7882aaa6a9cae7a Finished.
