### ISSUE TITLE
Help Suggestion

### ISSUE THREAD

**Issue by Carisus** [TheNewEconomy/TNE-Bukkit#88]
I think it would be neat if the help was a little more helpful. After typing `/tne help`:

 A hover event when you hover over the command with a little more explanation of that command

A click event that "suggests" the command. Places the command in chat where all you have do is replace the variables.

An example of what I am talking about is [Holographic Displays](https://dev.bukkit.org/bukkit-plugins/holographic-displays/).

[Fast reference photo](https://gyazo.com/4b9a9107eb1c34598fa4e10ac5f94c15)

**Comment by creatorfromhell** [comment]
This is definitely something worth looking into, although I'll probably use Fanciful. It'll be optional of course, because adding any dependencies isn't too ideal.
