### ISSUE TITLE
Changing name of crafted items

### ISSUE THREAD

**Issue by Carisus** [TheNewEconomy/TNE-Bukkit#91]
When crafting items, TNE renames them causing them to not be stack-able with the same item if that item is un-crafted. IE: Purchased, placed and then broken, etc.

[This item stack](https://gyazo.com/42e40daf45982f177cd48739663ea439) cannot be combined with [this item stack](https://gyazo.com/313381dd10964817e42c0432286a6c8e).

**Comment by creatorfromhell** [comment]
Yeah it should be keeping the crafting cost of the item. Will check into this.

**Comment by Carisus** [comment]
I have crafting cost turned off. It is still putting the tag on the item as 0.0.

**Comment by creatorfromhell** [comment]
Even still it shouldn't keep the crafting cost no matter the price.

**Comment by creatorfromhell** [comment]
What exactly did you do so that I am able to reproduce this bug? Currently when I craft an item it works as expected.

**Comment by Carisus** [comment]
Shift-click the items out of the crafting area. Both from the player inventory and from the workbench. [Here](http://pastebin.com/citjsAj6) is my config.yml and [this](http://pastebin.com/XiESRJHT) is my objects.yml.

**Comment by creatorfromhell** [comment]
Do you have the Materials.yml? That's the one that controls crafting cost?

**Comment by creatorfromhell** [comment]
Nvm, reproduced, at least when I shift click out of the player's crafting inventory. However shift-clicking from workbench is working as intended on my end.
