### ISSUE TITLE
Change config and reload

### ISSUE THREAD

**Issue by CCCCarsten** [TheNewEconomy/TNE-Bukkit#94]
Hi!
Every change in the configs of TNE does not have effects if you do it without stopping the server before. What does - in this case - /tne reload mean??
Ciao, Carsten

**Comment by creatorfromhell** [comment]
This was already addressed and fixed in #80. Closing.

**Comment by Oruss7** [comment]
Hi CCCCarsten !
Apparently we use same plugins xD

**Comment by CCCCarsten** [comment]
:D Hm.... seems that we are looking for high quality only! :D
Unfortunately I have problems with TNE, because there are big errors with MySQL...  server logfile says that there is an unknown column 'username' in 'field list'. So TNE does not function... It is a pain to find a good economy plugin for bungee cord. But it is a bigger pain to find some plugin finally and then it doesn't function :(.
There is no success if I delete the SQL-tables. After restart the errors appear again.

**Comment by creatorfromhell** [comment]
I have given you ways to fix the issues, as TNE functions on every other server using MySQL it must be your configuration.
