### ISSUE TITLE
Where download dev builds ? Is spigot web site up-to-date ?

### ISSUE THREAD

**Issue by Oruss7** [TheNewEconomy/TNE-Bukkit#96]
Hi Daniel, 

We only have alpha 3.3 on https://www.spigotmc.org/resources/the-new-economy.7805/updates

Can you update with the latest version please ?

Thanks you !

PS: is your plugin working with offline servers ?

**Comment by creatorfromhell** [comment]
Dev builds are on GitHub only and aren't meant for production in any way, shape or form. Theyre also not guaranteed to be backwards compatible. Offlonr servers should work, but you should probably set uuid to false in the configurations.
