### ISSUE TITLE
SQL unknown column "username" in "field list"

### ISSUE THREAD

**Issue by CCCCarsten** [TheNewEconomy/TNE-Bukkit#97]
Hi,

that is the error: http://pastebin.com/8BX5BG1q

That is my config.yml: 
Core:
  UUID: true
  Multiworld: true
  Balance: 1000.0
  Shorten: false
  Metrics: false
  Pins:
    Enabled: false
    Force: true
  Commands:
    PayShort: true
    BalanceShort: true
  Update:
    Check: false
    Notify: true
  AutoSaver:
    Enabled: true
    Interval: 600
  Currency:
    Decimal: .
    ItemCurrency: false
    ItemMajor: GOLD_INGOT
    ItemMinor: IRON_INGOT
    MajorName:
      Single: Coin
      Plural: Coins
    MinorName:
      Single: Cent
      Plural: Cents
  Shops:
    Enabled: false
    Cost: 10.0
    Max: 5
    Rows: 3
    Shoppers: 10
    Shares:
      Enabled: true
      Max: 3
  Signs:
    Bank:
      Enabled: false
      Place: 20.0
      Use: 20.0
    Shop:
      Enabled: false
      Place: 20.0
      Use: 20.0
  Death:
    Lose: false
  Bank:
    Enabled: true
    Command: true
    NPC: true
    Connected: false
    Cost: 20.0
    Rows: 3
    Interest:
      Enabled: false
      Rate: 0.2
      Interval: 1800
  World:
    EnableChangeFee: false
    ChangeFee: 5.0
  Database:
    Type: MySQL
    Prefix: TNE
    Backup: true
    FlatFile:
      File: economy.tne
    MySQL:
    H2:
      File: Economy
    SQLite:
      File: economy.db

Do you need anything more?

Ciao, Carsten

**Comment by creatorfromhell** [comment]
Everything looks alright for what TNE is concerned about. However, you may have to manually create the table. It's hard for me to say exactly from work, however.

**Comment by CCCCarsten** [comment]
Perhaps some user should try the command /money give playername amount. Yes, I am wonder why nobody has this error. But I see there are only 82 users which have downloaded your last version. But however, I have created a small server (another hoster, only standalone, not bungee, very easy). 

**latest.log** (start server): http://pastebin.com/2nGrGsWk
You can see the plugins there: Only HomeSpawnPlus, PermissionsEX, Vault, ProtocolLib, CommandSign, TNE.

Then I start the command: /money give Magnifizienz 11111. First error: The user who has given the command gets the money (not Magnifizienz). My original server configuration shows the same error.

And - then the very known error: http://pastebin.com/YGh9Z5be

I have some hard copies and I have no fun to look for a hardcopy poster. I will send it to you in a few minutes (Spigot PM).
In the next time I would like it if you believe me only a little bit.

Ciao, Carsten

**Comment by creatorfromhell** [comment]
I have installed this on multiple platforms, with multiple OSs and cannot recreate this issue. My suggestion is to add the row manually at this point.

**Comment by creatorfromhell** [comment]
Before I jump all over saying "Can't Reproduce", I figured I should elaborate. With the Alpha 4.0 progress I have rewritten some core components to the save system. I'm presuming that during these improvements I somehow inadvertently fixed the bug you're reporting before you started reporting it, thus bringing us to this situation of "not being able to reproduce it." Alpha 4.0 should be out by Monday, test it when that's released and report your findings back here, if you would.

**Comment by CCCCarsten** [comment]
I will not test this buggy plugin. I have found an economy plugin which is thousand of times better than yours. I have spend enough time for you. Good luck and good bye.

**Comment by creatorfromhell** [comment]
You have a good day too, since TNE is in Alpha I'm not entirely sure what you expected.

**Comment by maxlxl** [comment]
I had exactly the same problem. The source is, that the plugin is trying to save a uuid as username. I have fixed the error manually in the MySQL database, where I enlarged the size of the field username up to 128 bytes. It's not efficient I know, but it's temporary a solution.
I think the uuid comes from BungeeCord, but I'm may be wrong.
